libp2p/rust-libp2p

multistream-select/Cargo.toml
multistream-select/src/length_delimited.rs
multistream-select/src/lib.rs
multistream-select/src/protocol/dialer.rs
multistream-select/src/protocol/listener.rs

The way tokio-io splits a stream of data into individual frames is that it pulls a big chunk of data and runs it through what they call a "decoder". The problem with this approach is that if we later remove the `FramedRead` to get back the underlying socket, then we lose data that was read but not decoded.
This is a problem for `multistream-select`, because we send a bunch of length-delimited frame then immediately treat any follow-up data as being part of the negotiated protocol. Therefore by unwrapping tokio's `FramedRead` we would lose data that is part of this negotiated protocol.
This PR fixes it by reimplementing an alternative to `FramedRead` that only pulls the minimum required amount of data from the stream.

Fix multistream-select into_inner()

---

libp2p-peerstore/src/json_peerstore.rs
multihash/src/lib.rs

To fit the Rust naming convention. Also no longer drains the input multihash, so we don't have to clone it.

Rename Multihash::as_bytes() to to_bytes()

---

multistream-select/README.md
multistream-select/src/lib.rs

#51 for multistream-select
Unfortunately the `#[doc(include = "file.md")]` attribute is not stable yet, so I simply copy-pasted the content of the README to the crate root. In the future we will be able to do that more properly.
Note that multistream-select is not finished yet because it needs a varint library for correct implementation.

Documentation for multistream-select

---

example/examples/echo-server.rs
libp2p-swarm/src/transport.rs
libp2p-tcp-transport/src/lib.rs

Necessary so that we can for example turn `/ip4/127.0.0.1/tcp/0` into `/ip4/127.0.0.1/tcp/12345`. If we don't handle that at this level, then there is no way to know on which port we're listening on.

Transport::listen_on now returns a new Multiaddr on success

---

example/examples/echo-dialer.rs
example/examples/echo-server.rs
libp2p-tcp-transport/README.md
libp2p-tcp-transport/src/lib.rs

#51 for tcp-transport
Also:
- Renames `Tcp` to `TcpConfig` for clarity.
- `TcpConfig::new` no longer returns a `Result` because it no longer make sense now that the tokio reactor is passed externally.

Add a README and documentation for libp2p-tcp-transport

---

libp2p-peerstore/Cargo.toml
libp2p-peerstore/src/lib.rs
libp2p-peerstore/src/peerstore_tests.rs
libp2p-secio/Cargo.toml
libp2p-secio/src/codec/mod.rs
libp2p-secio/src/handshake.rs
libp2p-secio/src/lib.rs
libp2p-swarm/Cargo.toml
multistream-select/Cargo.toml
multistream-select/src/lib.rs
multistream-select/src/protocol/dialer.rs
multistream-select/src/protocol/listener.rs
multistream-select/src/tests.rs

Remove the tokio-core dependency where not necessary

---

libp2p-swarm/src/muxing.rs
libp2p-swarm/src/transport.rs

This PR implements `StreamMuxer` for the object that dispatches between two outputs when choosing between two connection upgrades.
Implementing `StreamMuxer` for `T where T: AsyncRead + AsyncWrite` was in fact not a good idea, because it conflicts with that.

Make it possible to use or_upgrade with stream muxers

---

example/examples/echo-dialer.rs
example/examples/echo-server.rs
libp2p-swarm/src/lib.rs
libp2p-swarm/src/transport.rs

Removes the `UpgradedNode::or_upgrade` method method, because it is contrary to good API practices.
Instead the user is now supposed to build a `OrUpgrade` object manually. This is slightly more cumbersome for now, and may be improved in the future.
The other reason for this change is that I couldn't think of a design for the future p2p-circuit protocol (which is a key element of the API design) that could use the current API. Using p2p-circuit will most likely require having an equivalent to `OrUpgrade` specifically for it.

Remove or_upgrade and let users build OrUpgrade manually

---

multistream-select/Cargo.toml
multistream-select/src/lib.rs
multistream-select/src/protocol/dialer.rs
multistream-select/src/protocol/error.rs
multistream-select/src/protocol/listener.rs
multistream-select/src/tests.rs

Now that `varint` is available, we can remove this `unimplemented!()` and unignore the test.

Implement the ls command for multistream-select

---

example/examples/echo-dialer.rs
example/examples/echo-server.rs
libp2p-swarm/src/transport.rs

Allows passing the multiaddr as the first parameter to the examples.
Also adds documentation, and the `into_connection_reuse()` method on `UpgradedNode`.

Allow customizing the address in the examples, plus minor improvements

---

example/examples/echo-server.rs
libp2p-swarm/src/connection_reuse.rs
libp2p-swarm/src/transport.rs
libp2p-tcp-transport/src/lib.rs

Right now the way the `Transport` trait works is that it produces a stream of sockets over which modifiers are applied in order to negotiate a protocol. Unfortunately an overlook of this design is that elements of a stream are polled serially, and not in parallel. The consequence is that right now a server cannot accept any further client while a client is already being negotiated.
This PR fixes that by changing the item yielded by the `Listener` stream from a `Result<impl AsyncRead + AsyncWrite, IoError>` to a `impl Future<Item = impl AsyncRead + AsyncWrite, Error = IoError>`.
Two notes:
- This doesn't change the various `dial_and_listen` methods because a general improvement of multiplexing is needed anyway.
- The changes to `ConnectionReuse` introduced by this PR are very …

Change API to allow multiple simultaneous clients

---

example/examples/echo-dialer.rs
example/examples/echo-server.rs
libp2p-swarm/Cargo.toml
libp2p-swarm/src/connection_reuse.rs
libp2p-swarm/src/lib.rs
libp2p-swarm/src/transport.rs
libp2p-tcp-transport/src/lib.rs

Based over #80 
Right now the `MuxedTransport` trait provides three methods: `dial`, `listen_on` and `dial_and_listen`. The difference between `dial` and `dial_and_listen` is that the latter allows you to handle the substreams that are opened by the node you dialed.
Whenever you use a muxed transport, you are strongly encouraged to use `dial_and_listen` instead of just `dial`.
This PR simplifies this design by removing `dial_and_listen` entirely, and replacing it with a `next_incoming` method that will consume the transport and return the next opened substream. Since the transport is generally clonable, you can easily turn that into a stream of incoming connections.

Change the MuxedTransport trait 

---

example/examples/echo-dialer.rs
example/examples/echo-server.rs
libp2p-swarm/Cargo.toml
libp2p-swarm/README.md
libp2p-swarm/src/connection_reuse.rs
libp2p-swarm/src/lib.rs
libp2p-swarm/src/swarm.rs
libp2p-swarm/src/transport.rs
libp2p-tcp-transport/src/lib.rs

Based over #81 
Adds the `swarm` function, which takes an upgraded `Transport` and a closure. The closure is called whenever a new node or a new substream of a node connected to us, and must turn the result of the upgrade into a `Future<Item = ()>`.
The function returns a `SwarmController` and a `Future`. The controller can be used to control the behaviour of the swarm, and the `Future` must be driven to completion.

Implement the swarm

---

Cargo.toml
README.md
libp2p-identify/Cargo.toml
libp2p-identify/regen_structs_proto.sh
libp2p-identify/src/lib.rs
libp2p-identify/src/structs_proto.rs
libp2p-identify/structs.proto

Based over #75 
The `identify` protocol is a way for a dialer to know who it is. Once the protocol has been negotiated, the listener side immediately sends a message to the dialer side indicating various information such as the addresses by which the dialer is observed.

Implement the identify protocol

---

example/Cargo.toml
example/src/lib.rs

Fills a peer store with the default bootstrap nodes of IPFS. For example purposes.

Add an ipfs_bootstrap function to fill the peer store

---

libp2p-identify/src/lib.rs
libp2p-ping/src/lib.rs
libp2p-secio/src/lib.rs
libp2p-swarm/src/transport.rs
multiplex-rs/src/lib.rs

Right now the user of the library has to specify in advance the value of `observed_addr` that will be sent to the remotes that connect to us, which doesn't make sense as the `observed_addr` is supposed to the address that the server sees for the dialer.
This PR modifies the API of `ConnectionUpgrade` and adds a parameter to `upgrade` indicating the address of the remote. This is then used by the identify protocol in order to send the correct value.

Correctly report the address of the dialer in the identify protocol

---

example/Cargo.toml
example/README.md
example/examples/ping-client.rs

cc @diasdavid 
Based over #88 
Adding this example indeed revealed a bug in the code, which is that incoming substreams would behave as if they were dialers instead of listeners when negotiating a protocol.
It also revealed another issue, which is that error handling in the swarm is too strict. It is possible right now to kill a server by triggering an error. Will fix that separately.

Add an example that pings an IPFS node

---

multistream-select/src/protocol/listener.rs
varint-rs/src/lib.rs

Fix `varint::encode` allocating for small inputs 

---

Cargo.toml
libp2p-dns/Cargo.toml
libp2p-dns/README.md
libp2p-dns/src/lib.rs

Adds `libp2p-dns`. Provides the `DnsConfig` type which implements `Transport` and wraps around another implementation of `Transport`.
Any attempt to dial to a multiaddr which contains `tcp4` or `tcp6` that goes through `DnsConfig` will be resolved.

Implement libp2p-dns

---

.editorconfig

The current settings differ from rustfmt which is used during CI runs to check the source code format. In particular, rustfmt will replace tabs with spaces, therefore this commit attempts to use the same settings already for editing.

Update .editorconfig to align with rustfmt.

---

Cargo.toml
dns/Cargo.toml
example/Cargo.toml
floodsub/Cargo.toml
identify/Cargo.toml
kad/Cargo.toml
peerstore/Cargo.toml
ping/Cargo.toml
swarm/Cargo.toml
tcp-transport/Cargo.toml
websocket/Cargo.toml

...in order to fix compilation problems regrading Multiaddr.

Bump multiaddr to 0.3 and remove patch in Cargo.toml

---

floodsub/Cargo.toml
identify/Cargo.toml
kad/Cargo.toml
secio/Cargo.toml

CI is failing because protobuf v1.6 broke backward compatibility, so let's pin to 1.4.
Eventually the correct solution is #183

Pin protobuf to 1.4

---

mplex/src/lib.rs
mplex/src/read.rs
mplex/src/shared.rs
mplex/tests/two_peers.rs
swarm/src/connection_reuse.rs
swarm/src/either.rs
swarm/src/muxing.rs
swarm/tests/multiplex.rs

Currently, connection substreams are added to `connection_reuse::Shared::active_connections`, but never removed. This is not least because the `StreamMuxer` trait defines its inbound and outbound substream futures to always yield a substream and contains no provision to signal that no more substreams can be created, which would allow client code (e.g. `ConnectionReuse`) to detect this and purge its caches.
This PR defines the `StreamMuxer` trait to optionally yield inbound/outbound substreams and changes `libp2p-mplex` to handle stream EOFs by marking the underlying resource as closed. `ConnectionReuse` will remove stream muxers from its active connections cache if a `None` substream is returned.

connection_reuse: drop dead connections.

---

core/src/connection_reuse.rs
core/src/swarm.rs
core/src/transport/and_then.rs
core/src/transport/choice.rs
core/src/transport/mod.rs
core/src/transport/upgrade.rs
dns/src/lib.rs
ratelimit/src/lib.rs

There's no reason to use `IntoFuture` except for ergonomics, but we don't really care about ergonomics when it comes to writing implementations of `Transport` because that happens so rarely.

Change Transport::Dial to be Future and not IntoFuture

---

core/src/connection_reuse.rs
core/src/swarm.rs
core/src/upgrade/apply.rs
dns/src/lib.rs
floodsub/src/lib.rs
identify/src/protocol.rs
identify/src/transport.rs
kad/src/query.rs
mplex/src/read.rs
mplex/src/shared.rs
mplex/src/write.rs
multistream-select/src/dialer_select.rs
multistream-select/src/listener_select.rs
multistream-select/src/protocol/listener.rs
ping/src/lib.rs
ratelimit/src/lib.rs
secio/src/codec/decode.rs
secio/src/handshake.rs
secio/src/lib.rs
tcp-transport/src/lib.rs
websocket/src/browser.rs
websocket/src/desktop.rs

The default uses crate + module path anyway, so `target` has been redundant, causes more work when renaming crates and makes log lines longer.

Remove all `target`s from log statements.

---

core/src/swarm.rs
kad/src/high_level.rs
libp2p/examples/echo-dialer.rs
libp2p/examples/floodsub.rs
libp2p/examples/ping-client.rs
libp2p/examples/relay.rs

I've never felt good about this function.
Now that you can use `.map()` on transports and upgrades, it's now always possible to dispatch every single connection to the handler passed to `swarm()`, and dispatch the behaviour at runtime.

Remove dial_custom_handler

---

libp2p/Cargo.toml
libp2p/src/lib.rs

`CommonTransport` now works and returns two different things for emscripten and non-emscripten.
Moves `ratelimit` to emscripten-only for now, because of #204.

Make the libp2p facade compilable for emscripten

---

libp2p/Cargo.toml
secio/Cargo.toml
secio/src/handshake.rs
secio/src/lib.rs

The `secp256k1` library, similarly to `ring`, can conflict if it's used by another project.

Make secp256k1 optional

---

datastore/src/json_file.rs

Having a `JsonFileDatabase` alive supposes that we will be able to store its content to the target.
Therefore we create the parent directory, even if we create the file only at flushing time.

Create the parent directory of a JSON datastore

---

core/src/lib.rs
core/src/peer_id.rs
core/src/public_key.rs
identify/keys.proto
identify/regen_structs_proto.sh
identify/src/keys_proto.rs
identify/src/lib.rs
identify/src/protocol.rs
secio/src/handshake.rs
secio/src/lib.rs

Based on #269 
It turns out that the public key in `IdentifyInfo` is not the raw public key, but a protobuf struct.

Fix the public key format in the IdentifyInfo

---

core/src/transport/and_then.rs

The major consequence is that if you used `upgrade::apply`, it would wait for a protocol selection from the remote instead of doing the protocol selection itself.

Fix wrong endpoint in and_then

---

secio/Cargo.toml
secio/src/lib.rs

This is something a Parity-egoistical pull request, but Polkadot uses the `eth-secp256k1` library, which cannot be linked at the same time as `secp256k1` because it uses the same symbols.
This PR makes secp256k1 usable in Polkadot.

Use eth-secp256k1 instead of secp256k1

---

core/src/upgrade/mod.rs
core/src/upgrade/toggleable.rs

Adds `upgrade::toggleable` that wraps around a connection upgrade and makes it possible to disable it.
I initially wanted to add an enum, so that you could choose between an upgrade or a `DeniedConnectionUpgrade`, but a toggleable upgrade makes more sense to me.

Add upgrade::toggleable

---

libp2p/examples/echo-dialer.rs
libp2p/examples/echo-server.rs
libp2p/examples/floodsub.rs
libp2p/examples/kademlia.rs
libp2p/examples/ping-client.rs
secio/src/handshake.rs
secio/src/lib.rs

Changes the API of secio to produce a `SecioOutput` that contains the stream, remote public key, and ephemeral key.

Give access to secio ephemeral key

---

kad/src/kad_server.rs
kad/src/protocol.rs

cc #295 
Avoids crashing the server with `unimplemented!()` if we receive a `PUT_VALUE` or `GET_VALUE` message from a Kademlia remote.

Remove exposed unimplemented!() in the Kad server

---

kad/src/kbucket.rs

Skip over buckets older than `ping_timeout`.

---

tcp-transport/Cargo.toml
tcp-transport/src/lib.rs

[The documentation of TcpListener](https://docs.rs/tokio-tcp/0.1.1/tokio_tcp/struct.TcpListener.html#errors) suggests doing what this PR does.
The `TcpListener` can sometimes produce an error which would just close the listener.
I think handling this directly in the TCP transport is the right location. There might be valid reasons why a listener produces an error, therefore the upper layers should continue to drop the listener if an error happens.

Use tk_listen to absorb errors on the TcpListener

---

tcp-transport/Cargo.toml
tcp-transport/src/lib.rs

Beginning of an effort to remove boxes from the crate. cc #369 
You can review commit by commit, especially as there's a `cargo fmt` in the middle of the stack.

Tcp refinements

---

cid/src/error.rs
cid/src/lib.rs
cid/src/to_cid.rs
cid/tests/lib.rs
core/src/peer_id.rs
kad/src/kbucket.rs
libp2p/examples/kademlia.rs
multihash/src/errors.rs
multihash/src/hashes.rs
multihash/src/lib.rs
multihash/tests/lib.rs

In order to use it in `Multiaddr` eventually, instead of the `Cid`.
Can be reviewed commit by commit.

Rework the multihash crate

---

datastore/Cargo.toml
datastore/src/json_file.rs
secio/Cargo.toml

I'm trying compile libp2p on my Windows 10 1803 PC, but got error
```
error: failed to run custom build command for `ring v0.12.1`
process didn't exit successfully: `C:\Users\jasl9\Workspaces\Rust\rust-libp2p\ta                                                   rget\debug\build\ring-4c88590251fb12fa\build-script-build` (exit code: 101)
--- stderr
thread '<unnamed>' panicked at 'execution failed', C:\Users\jasl9\.cargo\registr                                                   y\src\github.com-1ecc6299db9ec823\ring-0.12.1\build.rs:636:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'execution failed', C:\Users\jasl9\.cargo\registr                                                   y\src\github.com-1ecc6299db9ec823\ring-0.12.1\build.rs:636:9
thread …
```

Fix compiling error on windows

---

mplex/src/lib.rs
secio/src/codec/decode.rs
secio/src/codec/encode.rs
secio/src/codec/mod.rs
secio/src/stream_cipher.rs

Some cosmetic fix and the missing copyright for #386

Complements to #389

---

protocols/floodsub/src/lib.rs

Fix rust-libp2p issue #429 (floodsub fails to decode PeerId)

---

misc/multistream-select/src/protocol/listener.rs
misc/multistream-select/src/tests.rs

#438 did not consider the `\n` character for element lengths (cf. https://github.com/multiformats/multistream-select#ls-example-in-detail).

multistream-select: Include `\n` in length.

---

muxers/mplex/src/codec.rs

Instead of transferring the bytes to the local state, we just grow the buffer allocated by tokio.

Simplify the mplex codec implementation

---

core/src/connection_reuse.rs
core/src/transport/mod.rs
core/src/transport/upgrade.rs
core/tests/multiplex.rs
examples/echo-dialer.rs
examples/echo-server.rs
examples/floodsub.rs
examples/kademlia.rs
examples/ping-client.rs
examples/relay.rs

As per IRL discussion, we decided to merge the changes I made for substrate into master.
This is more or less the same as #355 plus some changes to `UniqueConnec` and connection reuse's API.
This is a breaking change, as the methods of `UniqueConnec` changed name, and `ConnectionReuse` now requires the input to be of the format `(a, muxer)` and will produce a `(a, substream)`. The `a` is simply cloned around and can be used to pass data through (such as the node's public key).

Merge the changes from polkadot-2 into master

---

muxers/mplex/src/lib.rs

A small practical change. Don't allocate too much space in the buffer, so that we can set the maximum buffer length to a very high value without any problem.

Cap the allocated buffer capacity in mplex

---

protocols/secio/Cargo.toml

This is unfortunately a Parity-specific change, but all of our codebase uses ring 0.12 and versions of ring are incompatible with one another. Therefore we need to downgrade ring in libp2p.

Downgrade ring to 0.12

---

core/src/lib.rs
core/src/swarm.rs
core/src/transport/memory.rs
core/src/unique.rs
core/tests/lots_of_connec.rs
examples/echo-dialer.rs
examples/echo-server.rs
examples/floodsub.rs
examples/kademlia.rs
examples/ping-client.rs
examples/relay.rs

The future returned by `swarm()` is now a stream of events that happen during the process of the stream.
This allows the user to know more precisely what happens.

The SwarmFuture is now a Stream

---

muxers/mplex/src/codec.rs
muxers/mplex/src/lib.rs

A low hanging fruit w.r.t. #451: clone without copies.

Use `Bytes` instead of `BytesMut` in mplex.

---

muxers/mplex/src/lib.rs

Fix #452 
See the issue for a description of why this PR

Fix mplex notifications system

---

protocols/secio/Cargo.toml
protocols/secio/src/algo_support.rs
protocols/secio/src/codec/mod.rs
protocols/secio/src/handshake.rs
protocols/secio/src/lib.rs
protocols/secio/src/stream_cipher.rs

Adds support for the twofish cipher mode.
There are random data corruption in polkadot right now, and that might be a problem in the `aes` library.
Let's add support for twofish in secio, and later, once it's deployed, we can try using it in our local node to see if the data corruption goes away.

Add support for twofish cipher

---

muxers/mplex/src/lib.rs

Upload only chunks of 1024 bytes at a time.
This means that we have higher chances of being able to write without waiting for the underlying socket.
Also makes interleaving more likely to happen, although work may need to be done in this regard.
Successfully tested on substrate when replacing 1024 with 2.

Limit upload frame sizes to 1024 in mplex

---

protocols/secio/src/algo_support.rs

Allows using it with one element.

Minor fix for concat_comma

---

core/src/transport/boxed.rs
core/src/transport/mod.rs

Based on top of #458 
Adds an abstract implementation of `MuxedTransport`, so that we can put a transport in a Box-like structure.

Add BoxedMuxed transport

---

protocols/secio/Cargo.toml
protocols/secio/src/algo_support.rs
protocols/secio/src/codec/decode.rs
protocols/secio/src/codec/encode.rs
protocols/secio/src/codec/mod.rs
protocols/secio/src/error.rs
protocols/secio/src/handshake.rs
protocols/secio/src/lib.rs
protocols/secio/src/stream_cipher.rs

With all the corrupt data issues we've been having, let's take the conservative approach to revert back to `rust-crypto` which we know was working.
This reverts commit 73996885cb2d645ee91361204c33e7039290aabc.
This is not a "strict revert", more like an "adjusted revert" where I kept the good parts and threw away the switch to the `rust_crypto` orga.
In the future when substrate is stable we can experiment locally by reverting this PR.

Revert "remove rustc-serialize (#359) (#386)"

---

protocols/secio/src/error.rs
protocols/secio/src/handshake.rs

Given that echoing back our local key and nonce would result in equal digest values, we should treat this as an error instead of panicking (cf. #479).

secio: don't panic in `agree_ephemeral`.

---

protocols/secio/Cargo.toml
protocols/secio/src/algo_support.rs
protocols/secio/src/codec/decode.rs
protocols/secio/src/codec/encode.rs
protocols/secio/src/codec/mod.rs
protocols/secio/src/error.rs
protocols/secio/src/lib.rs
protocols/secio/src/stream_cipher.rs

Reverts #466.
We deployed the switch back to `rust-crypto` in Substrate and still get corrupted data, so let's revert that change.

Revert "Revert "remove rustc-serialize (#359) (#386)" (#466)"

---

core/src/nodes/collection.rs
core/src/nodes/handled_node.rs
core/src/nodes/mod.rs
core/src/nodes/swarm.rs

Concerns the new swarm system.
cc #484 
Right now the swarm produces events when substreams are opened on the nodes we're connected to. The user of the swarm is supposed to handle the substreams themselves.
This pull request adds a `NodeHandler` trait whose implementation must act as a "sink" for what happens on a node, and handles the behavior of the substreams. The handler communicates with the outside through events. The user of the swarm is supposed to implement this trait the way they want, but helpers will be proposed in the future.
In terms of performances, this allows the substreams handler to run in the same task as the node, which is obviously better.
Changes:
- `node.rs` is untouched.
- Adds `handled_node.rs` that contains the `NodeHandler` trait, and a `HandledNode` struct …

Add a NodeHandler trait

---

protocols/ping/src/lib.rs

`needs_close` is set to true, but then nothing is done.

Fix the ping dialer never closed

---

core/Cargo.toml
misc/multistream-select/Cargo.toml
protocols/floodsub/Cargo.toml
protocols/kad/Cargo.toml

`smallvec 0.5.x` use `MPL-2.0` which is incompatible with `MIT`, upgrade to `smallvec 0.6.x` to fix this issue.

Upgrade smallvec version

---

misc/multihash/Cargo.toml
misc/multihash/src/errors.rs
misc/multihash/src/hashes.rs
misc/multihash/src/lib.rs
misc/multihash/tests/lib.rs

* Depend on `unsigned-varint` 0.2 without default features.
* Depend on `blake2` crate 0.7 with no default features.
* Add support for BLAKE2b-512 and BLAKE2s-256.
* Fix hash codes and enum variants for BLAKE2 to follow the standard (see issue #524).
* Use proper unsigned variable integers to indicate hash algorithm instead of a single initial byte.
* Change hash code type from `u8` to `u16`.
* Update included tests to check BLAKE2b-512 and BLAKE2s-256.
* Run `cargo fmt` on `multihash` crate.
* Bump `tiny-keccak` to version 1.4.
Fixes #524.

Use unsigned-varints, add BLAKE2 support in multihash

---

core/src/nodes/collection.rs
core/src/nodes/handled_node.rs
core/src/nodes/handled_node_tasks.rs
core/src/nodes/listeners.rs
core/src/nodes/swarm.rs

Modifies the API of `CollectionStream`. Whenever we successfully reach a node, the node goes into a "pending" state and first needs to be accepted before its events are propagated.
This is enforced by making `poll()` mutably borrow the collection stream, and generate a `CollectionReachEvent` struct with an `accept()` method. If the `CollectionReachEvent` is dropped before being accepted, the node is denied and the connection is dropped without generating any further event. It is only when accepting that we can potentially replace an existing connection.
In practice, this means that the swarm can check whether there is a public key mismatch before an existing connection is replaced. This therefore fixes #502 
Under the hood, a node being denied still spawns a task and starts processing. If …

Make it possible to accept/deny nodes in CollectionsStream

---

Cargo.toml
protocols/secio/Cargo.toml
protocols/secio/src/algo_support.rs
protocols/secio/src/codec/decode.rs
protocols/secio/src/codec/encode.rs
protocols/secio/src/codec/mod.rs
protocols/secio/src/exchange.rs
protocols/secio/src/exchange/impl_ring.rs
protocols/secio/src/exchange/impl_webcrypto.rs
protocols/secio/src/exchange/mod.rs
protocols/secio/src/handshake.rs
protocols/secio/src/lib.rs
src/lib.rs

Close #499 
~~Disclaimer: this doesn't actually compile because emscripten doesn't support i128 operations. However on the Rust side everything works, and one can argue that this PR is a good first step. I'm also fine with leaving this PR on ice for some time.~~
For some reason this works now.
Disclaimer: the crypto library I used (`ed25519-dalek`) is not audited, but neither is ring.
This PR replaces most of the usages of `ring` with the `ed25519-dalek`, `hmac` and `sha2` crates. The only remaining usage is for ECDH, because I'm not aware of any other library that supports this. For emscripten, the implementation uses `WebCrypto`. The `WebCrypto` path is unfortunately untested, as the code doesn't actually compile.
This adds a `rsa` feature to secio which makes it support RSA public …

Make secio almost compile for asmjs/wasm

---

misc/multistream-select/Cargo.toml
misc/multistream-select/src/length_delimited.rs
misc/multistream-select/src/lib.rs
misc/multistream-select/src/protocol/dialer.rs
misc/multistream-select/src/protocol/listener.rs

Motivated by the recent deprecation of `tokio_io::codec::length_delimited`.

multistream-select: Use `FramedWrite` from `tokio-codec`.

---

misc/multiaddr/src/lib.rs
misc/multiaddr/tests/lib.rs

Append to the existing vector instead of allocating a temporary one and copying bytes over.

Optimise `Multiaddr::append`.

---

muxers/mplex/src/lib.rs
muxers/yamux/src/lib.rs

mplex gets a new flag `is_shutdown` to keep track of when `shutdown` has been called. We need to make certain that after the shutdown no more `Sink::poll_complete` or `Sink::start_send` calls are being made which may result in a panic.

Shut down yamux and fix mplex shutdown.

---

core/src/muxing.rs
core/src/nodes/handled_node.rs
core/src/nodes/node.rs

Add `NodeStream::shutdown` to allow triggering the shutdown process, and `NodeStream::poll_shutdown` as the internal way to drive any potential shutdown to completion.
Also shutdown the `NodeStream` in `Node::shutdown`.
Fixes #551.

Add shutdown functionality to `NodeStream`.

---

core/src/nodes/listeners.rs

I would consider `listeners.rs` as final or almost final, so let's add documentation to it.

Add some documentation to listeners stream

---

core/src/transport/mod.rs
misc/multiaddr/src/lib.rs
transports/tcp/src/lib.rs
transports/websocket/src/browser.rs
transports/websocket/src/desktop.rs

Transports should consider only the relevant address prefix.
Fixes #544.

Change some `nat_traversal`s to consider a prefix.

---

core/src/nodes/handled_node.rs

Fix the tests failing in https://github.com/paritytech/substrate/pull/931

Fix the polling process in handled node

---

core/src/nodes/collection.rs
core/src/nodes/handled_node.rs
core/src/nodes/handled_node_tasks.rs
core/src/nodes/raw_swarm.rs
muxers/mplex/src/lib.rs
protocols/floodsub/src/lib.rs
protocols/identify/src/protocol.rs
protocols/kad/src/high_level.rs
protocols/kad/src/protocol.rs
protocols/kad/src/query.rs
protocols/ping/src/lib.rs
protocols/secio/src/handshake.rs
protocols/secio/src/lib.rs
stores/datastore/src/lib.rs
transports/dns/src/lib.rs
transports/websocket/src/desktop.rs

Done by creating a `foo` folder, moving all non-hidden / `.*` folders & files into `foo`, then  `cd foo; find ./ -type f -exec sed -i 's/\ ;/;/g' {} \;` then moving everything back out of foo.

Remove spaces before semicolons

---

Cargo.toml
src/lib.rs

We're exposing the `Multihash` type in the API, so we should reexport the crate.

Reexport multihash from the facade

---

transports/websocket/Cargo.toml

Integrates https://github.com/websockets-rs/rust-websocket/pull/185 (which is why we were using a fork) and https://github.com/websockets-rs/rust-websocket/pull/186
cc #593

Use websocket 0.21.0

---

core/src/lib.rs
core/src/transport/mod.rs
core/src/upgrade/traits.rs
misc/multiaddr/src/protocol.rs
misc/multistream-select/src/length_delimited.rs
misc/multistream-select/src/lib.rs
misc/multistream-select/src/listener_select.rs
protocols/identify/src/protocol.rs
protocols/kad/src/kad_server.rs
stores/peerstore/src/lib.rs
stores/peerstore/src/peerstore.rs

What I did:
```bash
sudo python3.7 get-pip.py7;
sudo pip2.7 install repren # add a hyphen with pip-2.7 if not using Ubuntu or Arch Linux / Manjaro.
repren -n  -p ../repren/eg-ie.txt --literal --full . # dry run
repren -p ../repren/eg-ie.txt --literal --full .
```
eg-ie.txt:
```
eg.	e.g.
ie.	i.e.
Eg.	E.g.
Ie.	I.e.
```

eg. -> e.g.; ie. -> i.e. via repren

---

core/src/muxing.rs
core/src/nodes/node.rs
core/src/tests/dummy_muxer.rs

Does the same as #562 but the way I imagined it.

Fix stack overflow when printing a SubstreamRef

---

core/src/nodes/protocols_handler.rs
protocols/identify/src/periodic_id_handler.rs
protocols/ping/src/dial_handler.rs
protocols/ping/src/listen_handler.rs

I was initially considering passing an event by reference so that multiple handlers can be combined and the same event sent to multiple handlers.
In practice, however, it is unlikely or even harmful for multiple handlers to process the same event.
In practice, as well, combining two handlers in a generic way consists in dispatching the event to the correct handler and not sending it to both.
For these reasons, let's change injecting events to taking the event by value.

Inject event by value in ProtocolsHandler

---

core/src/lib.rs
core/src/nodes/mod.rs
core/src/nodes/raw_swarm.rs
core/src/nodes/swarm.rs
core/src/topology/mod.rs

- Adds a `Swarm` struct that wraps around a transport, a network behaviour, and a topology.
- Adds a `Topology` trait that is equivalent to the former `Peerstore`.
- Adds a `NetworkBehaviour` trait that is designed to add behaviours to the network as a whole.
Ultimately the user is supposed to combine multiple network behaviours into one through a custom derive, then put it in a `Swarm` to use it.
Note that the `Swarm` derefs to the behaviour, and provides methods that take a `&mut Self` (similar to what `Arc` does). I expect the user to use these fairly rarely, as the behaviour should handle everything automatically.

Add back the Swarm

---

protocols/secio/Cargo.toml
protocols/secio/src/handshake.rs
protocols/secio/src/lib.rs

The question implied here is: why did we fork `rust-secp256k1` and are those reasons still valid? Can we get back to the mainline crate? There is [ongoing work on our fork](https://github.com/paritytech/rust-secp256k1/pull/16) to make it `no_std` but I'm not sure what the end-goal of that effort is.
Part of https://github.com/libp2p/rust-libp2p/issues/593

Use upstream rust-secp256k1

---

Cargo.toml
src/lib.rs

Since it indirectly depends on OpenSSL, it is IMO a good idea to make it optional.

Make libp2p-websocket optional

---

protocols/kad/src/kbucket.rs

Collect a little more info if/when creating PeerIds fail.
Tries to address https://github.com/libp2p/rust-libp2p/issues/496

Use expect rather than unwrap

---

protocols/identify/Cargo.toml
protocols/identify/src/lib.rs
protocols/identify/src/listen_handler.rs
protocols/identify/src/listen_layer.rs

I forgot to add it in #579 
This is the listening side. You set the information ahead of time, and the behaviour automatically handles requests.

Add an IdentifyListen behaviour

---

protocols/floodsub/src/layer.rs

After a peer connects they send us the list of the topics they're subscribed to. This causes a NodeEvent to be emitted. This PR makes sure we update the subscription info we have on the newly connected peer.

Update connected peers' topics on NodeEvent

---

core/src/protocols_handler.rs
core/src/upgrade/map.rs
core/src/upgrade/mod.rs

The current implementation of `MapUpgrade` implements `InboundUpgrade` and `OutboundUpgrade` and applies the transformation in both cases which means that mapping is always applied to inbound and outbound upgrades. This commit uses separate `MapInboundUpgrade` and `MapOutboundUpgrade` types which implements both traits but only map in one direction.

Fix mapping of upgrade.

---

core/src/nodes/collection.rs
core/src/nodes/handled_node_tasks.rs
core/src/peer_id.rs
misc/multihash/Cargo.toml
misc/multihash/src/lib.rs
protocols/kad/src/kad_server.rs
protocols/kad/src/protocol.rs
stores/peerstore/src/json_peerstore.rs
stores/peerstore/src/lib.rs
stores/peerstore/src/peerstore_tests.rs

This method is needed surprisingly often.
I went with a single method instead of implementing traits from `rand`, so that we don't have to depend on a third-party crate to generate a random ID. I think this is a good idea considering that there many versions of `rand` in the wild.

Add PeerId::random()

---

protocols/identify/src/protocol.rs

The user needs to be able to build instances of `IdentifyInfo` to send back to remotes.

Remove _priv from IdentifyInfo

---

core/src/protocols_handler/select.rs
misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

Fixes the fact that the `InboundUpgrade` and `OutboundUpgrade` were required to have the same `Output`, which doesn't make sense. And it turns out this was an arbitrary restriction, because nothing broke when I removed the bounds.
Also fixes the tests of `core-derive`, which were not checking that `Foo` was indeed implementing `NetworkBehaviour`.

Fix the custom derive

---

misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

Apparently we were accidentally outputting `impl ... for ... where, Foo: Bar` (notice the extra `,`).
The latest versions of Rust no longer accept that.
Also fixes the commented-out test.

Fix core-derive

---

transports/relay/src/transport.rs

Fixes deprecation warning related to `Rng::shuffle` which recommends `SliceRandom::shuffle` instead.

relay: Use `SliceRandom::shuffle`.

---

muxers/yamux/Cargo.toml
muxers/yamux/src/lib.rs

Remove the need for an extra mutex. Requires https://github.com/paritytech/yamux/pull/24 for tests to pass.

Don't wrap yamux::Connection in a mutex

---

core/src/swarm.rs
examples/chat.rs
examples/ipfs-kad.rs

Adds `Swarm::local_peer_id`, `PollParameters::listened_addresses`, `PollParameters::local_public_key`, `PollParameters::local_peer_id`.
The consequence is that the user now needs to pass the `PublicKey` when creating the `Swarm`.

Add a few more methods to Swarm and PollParameters

---

misc/mdns/src/lib.rs
muxers/mplex/tests/two_peers.rs
protocols/kad/src/protocol.rs

- mdns: unused `Result` which must be used
- kad: unused import
- mplex: use of deprecated item

Avoid some warnings.

---

examples/chat.rs
misc/core-derive/tests/test.rs
protocols/floodsub/src/layer.rs
protocols/floodsub/src/lib.rs
protocols/identify/src/lib.rs
protocols/identify/src/listen_handler.rs
protocols/identify/src/listen_layer.rs
protocols/identify/src/periodic_id_handler.rs
protocols/identify/src/periodic_id_layer.rs
protocols/identify/src/protocol.rs
protocols/ping/src/dial_layer.rs
protocols/ping/src/lib.rs
protocols/ping/src/listen_layer.rs

And no longer expose upgrades and handlers at the root of the protocol libraries.
Makes it easier for users to figure out what to use.
cc #596

Rename all the network behaviours to more basic names

---

core/src/nodes/raw_swarm.rs
core/src/swarm.rs

Fix #752 
When a connection is incoming with a peer ID which we're already connected to by dialing, if our local peer ID is inferior to the remote ID then we refuse the new connection.

Add a dial priority system

---

Cargo.toml
core/Cargo.toml
core/src/nodes/listeners.rs
muxers/mplex/Cargo.toml
muxers/mplex/tests/two_peers.rs
protocols/identify/Cargo.toml
protocols/identify/src/protocol.rs
protocols/kad/Cargo.toml
protocols/kad/src/protocol.rs
protocols/ping/Cargo.toml
protocols/ping/src/lib.rs
protocols/secio/Cargo.toml
protocols/secio/src/lib.rs
src/lib.rs
transports/dns/Cargo.toml
transports/dns/src/lib.rs
transports/tcp/Cargo.toml
transports/tcp/src/lib.rs
transports/websocket/Cargo.toml
transports/websocket/src/desktop.rs
transports/websocket/src/lib.rs

For consistency with the other crate names.

Rename libp2p-tcp-transport to libp2p-tcp

---

misc/multiaddr/Cargo.toml
misc/multihash/Cargo.toml

The corresponding `README.md` files don't exist.

Remove readme = entries in Cargo.toml

---

misc/core-derive/Cargo.toml

Right now `libp2p-core-derive` is using `syn` with `default-features=false` and doesn't enable the `clone-impls` feature even though it needs it to compile.
However in practice it always compiles because it has an indirect dependency on `serde-device`, which depends on `syn` with `clone-impls` enabled. Hence why we have never realized the problem.

Fix compilation with syn 0.15.23

---

protocols/ping/src/dial_handler.rs

Instead of returning this awkward `Unresponsive` event, produce an error.
Importantly, this will instantly destroy the stream instead of trying to shut it down properly.

Produce an error if a node is unresponsive

---

protocols/kad/src/protocol.rs

Now that the Kademlia protocol is unidirectional, let's remove these assertions.

Remove assertions in kad protocol

---

core/src/swarm.rs
core/src/topology/mod.rs

Close #793 
Let the topology know when we are connected or disconnected or failed to reach an address.

Add more methods on Topology

---

protocols/secio/Cargo.toml
protocols/secio/benches/bench.rs
protocols/secio/benches/test.rs

It looks like secio is quite slow:
```
running 8 tests
test raw_tcp_connect_and_send_hello  ... bench:     111,883 ns/iter (+/- 36,509)
test raw_tcp_connect_and_send_one_kb ... bench:      90,428 ns/iter (+/- 16,667)
test raw_tcp_connect_and_send_one_mb ... bench:     205,261 ns/iter (+/- 65,605)
test raw_tcp_connect_and_send_two_mb ... bench:     424,672 ns/iter (+/- 118,419)
test secio_connect_and_send_hello    ... bench:  84,179,869 ns/iter (+/- 860,216)
test secio_connect_and_send_one_kb   ... bench:  84,131,584 ns/iter (+/- 819,757)
test secio_connect_and_send_one_mb   ... bench: 128,193,827 ns/iter (+/- 12,361,897)
test secio_connect_and_send_two_mb   ... bench: 143,293,226 ns/iter (+/- 22,052,017)
```

Add some benchmarks for secio

---

protocols/secio/Cargo.toml

Apparently `ring` doesn't compile with this feature, but we enable it indirectly with our `rsa` feature and therefore we don't notice.

Fix compilation of ring

---

Cargo.toml
src/lib.rs
src/simple.rs
src/transport_ext.rs

Switches the facade crate to edition 2018 and improves the appearance of the generated documentation.
The documentation will now inline the documentation of the sub-crates (`core`, `mplex`, `ping`, etc.) instead of just showing a line saying `extern crate libp2p_core as core;`
Also added the libp2p icon.

Improve doc aesthetics

---

core/src/nodes/collection.rs
core/src/nodes/handled_node_tasks.rs
core/src/nodes/raw_swarm.rs
core/src/protocols_handler/mod.rs
core/src/protocols_handler/node_handler.rs
core/src/protocols_handler/select.rs
core/src/swarm.rs
misc/core-derive/src/lib.rs

Fix #824 
Instead of providing directly an implementation of the `NodeHandler` and/or `ProtocolsHandler` trait, a user can now provide an implementation of `IntoNodeHandler` or `IntoProtocolsHandler`.
The object will be sent to the background task dedicated to a node, and once the connection is established we call `into_handler` with the `PeerId`.

Add IntoNodeHandler and IntoProtocolsHandler traits

---

misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

When injecting the users where clause we need to ensure a comma is
inserted between the users where clause and ours.
Fixes: #754

Fix custom derive when using a where clause

---

core/src/nodes/raw_swarm.rs

Fix #773 
API changes:
- Adds a variant to `IncomingError`.
- Changed the `TransportError` into a `UnknownPeerDialErr` for unknown peers dialing errors.
Internal changes:
- The internal error that can happen when trying to reach a remote is now `InternalReachErr` and contains all the possible variants of all the possible errors.
- We "hijack" the futures and add a check that the `PeerId` is different than the local one.
I went with the approach of hijacking the futures instead of handling it in the `RawSwarm` so that the handler never sees a "bad" `PeerId`.

Deny connection with local PeerId

---

protocols/floodsub/Cargo.toml
protocols/floodsub/src/handler.rs
protocols/floodsub/src/layer.rs
protocols/floodsub/src/protocol.rs
protocols/floodsub/src/topic.rs
protocols/identify/Cargo.toml
protocols/identify/src/id_transport.rs
protocols/identify/src/protocol.rs
protocols/kad/Cargo.toml
protocols/kad/src/behaviour.rs
protocols/kad/src/handler.rs
protocols/kad/src/kbucket.rs
protocols/kad/src/protocol.rs
protocols/kad/src/query.rs
protocols/kad/src/topology.rs
protocols/observed/Cargo.toml
protocols/plaintext/Cargo.toml
transports/dns/Cargo.toml
transports/dns/src/lib.rs
transports/ratelimit/Cargo.toml
transports/tcp/Cargo.toml
transports/uds/Cargo.toml

Update the protocols and transport subdirectories to the 2018 edition.
NB: The websocket transport cannot be moved to 2018 edition due to
websocket-rs's use of the keyword async as the name of a module.
Relates to: #866

Update protocols and transport to 2018 edition

---

misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

Properly handle trailing commas in `derive(NetworkBehaviour)`
Fixes: #861

derive(NetworkBehaviour) handles trailing commas

---

core/src/swarm.rs
misc/core-derive/src/lib.rs
misc/mdns/src/behaviour.rs
protocols/floodsub/src/layer.rs
protocols/identify/src/identify.rs
protocols/kad/src/behaviour.rs
protocols/ping/src/lib.rs

Adds a `inject_dial_failure` method that is called when we fail to reach a node.

Add inject_dial_failure and make addresses_of_peer mut

---

protocols/noise/Cargo.toml

Compiling master failed for me, because `libp2p-noise` uses some features that were added in later versions of `rand`.

Use rand 0.6.5 in libp2p-noise

---

core/Cargo.toml
core/src/nodes/raw_swarm.rs
core/src/nodes/raw_swarm/tests.rs
core/tests/raw_swarm_simult.rs

Fixes maybe #883, I'm not sure.
Right now, when we dial a node and receive an incoming connection from that same node, we cancel the outgoing attempt.
The problem is that this outgoing attempt may have already succeeded (and we don't know yet), in which case the remote has maybe cancelled its own connection. The outcome is no connection at all.
There is a dialing priority system in place, but it applied only if we receive a new connection from a node we are already connected to.
This PR does the following:
- We no longer cancel outgoing attempts when we receiving an incoming connection. However we remove the addresses in the queue.
- Closing an open connection also cancels the outgoing connection attempt.
- We can now receive `DialError` events from nodes we are connected to. In order to …

Fix the dialing priority system

---

core/src/swarm.rs
misc/core-derive/src/lib.rs
protocols/kad/src/behaviour.rs
protocols/kad/src/query.rs

Instead of calling "disconnected" followed with "connected", allows implementers to override an `inject_replaced` method.
The Kademlia behaviour needs this so that it can re-send the RPC query without marking the node as unreachable.

Add NetworkBehaviour::inject_replaced

---

protocols/kad/Cargo.toml
protocols/kad/src/protocol.rs

cc https://github.com/paritytech/substrate/issues/1645
The number of results is 20.
A message of 4kiB is enough to transfer 20 nodes with around 15 addresses each. Nodes typically don't have 15 addresses.

Limit Kademlia messages to 4kiB

---

misc/core-derive/Cargo.toml
misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

Right now, writing `#[behaviour(out_event = "Vec<String>")]` is refused because `Vec<String>` is parsed an `Ident` instead of a `Type`.

Fix generics in out_event type in derive

---

core/Cargo.toml
core/src/swarm.rs

We're checking for duplicates at one place, but not there.

Fix duplicate external addresses inserted

---

core/src/upgrade/mod.rs
core/src/upgrade/transfer.rs
protocols/floodsub/src/protocol.rs

Adds a `read_respond` function that reads one message then responds.
Also adds a user parameter everything so that we can express the type of the structs in associated types.

Improvements to the helpers in upgrade::transfer

---

core/src/upgrade/transfer.rs

The `read_one` method expects a length prefix before the received message.
If we receive an EOF before the length prefix has been successfully read, we return an error.
This PR adds a small tweak: if the substream contains zero data (ie. the first read ever produces EOF), we don't return an error but an empty `Vec` instead.

Accept empty substreams in read_one

---

core/src/protocols_handler/fuse.rs

The `poll()` method is surprisingly high in benchmarks in debug mode, probably because we memcpy `self.inner` twice every time we poll.

Minor optimisation in Fuse::poll

---

misc/multiaddr/src/lib.rs

Apparently `serde_cbor` returns back multiaddresses as "sequences".

Decode multiaddresses from visit_seq

---

misc/multiaddr/src/lib.rs
src/lib.rs

Moves the `multiaddr!` macro in the `multiaddr` crate.
Re-exports it under the name `build_multiaddr!` in `libp2p`, so that we solve the conflict with the `multiaddr` module reexport.

Fix the multiaddr reexport

---

core/src/nodes/collection.rs
core/src/nodes/collection/tests.rs
core/src/nodes/handled_node_tasks.rs
core/src/nodes/raw_swarm.rs

Continuation of #917 
Makes it possible to store a "user data" when we accept a node in the `CollectionStream`. The user data can later be queried.
Also modifies the events of `CollectionStream` to include the user data when a connection is closed, and to produce a borrowed `Peer` instead of a `PeerId` when an event happens.

Add a user data to `CollectionStream`

---

core/Cargo.toml
core/src/nodes/listeners.rs
core/src/nodes/raw_swarm/tests.rs
core/src/transport/memory.rs
core/src/transport/mod.rs
misc/multiaddr/src/protocol.rs
misc/multiaddr/tests/lib.rs

Makes it possible to use the `MemoryTransport` as a drop-in replacement for `TcpConfig`, except that the addresses are of the form `/memory/N` (where `N` is a u64), instead of `/ip4/.../tcp/...`.
Close #913

Rewrite the MemoryTransport to be similar to the TcpConfig

---

core/src/protocols_handler/fuse.rs
core/src/protocols_handler/select.rs

When shutting down, we were looping infinitely as long as `self.proto1` is not shut down.
This is a mistake, it should loop infinitely as long as `self.proto1` is not in the process of shutting down (in practice, it should only ever loop once).

Fix an infinite loop in ProtocolsHandlerSelect

---

core/src/either.rs
core/src/muxing.rs
core/src/nodes/collection.rs
core/src/nodes/handled_node.rs
core/src/nodes/handled_node_tasks.rs
core/src/nodes/handled_node_tasks/tests.rs
core/src/nodes/node.rs
core/src/nodes/raw_swarm.rs
core/src/tests/dummy_muxer.rs
core/tests/raw_swarm_simult.rs
muxers/mplex/src/lib.rs
muxers/yamux/src/lib.rs

It turns out that the `raw_swarm_simultaneous_connect` test had an issue: we were only applying the muxer as outbound. This was causing the test to erroneously succeed.
It turns out that fixing it was quite complicated. The underlying issue is that when we have two connections to the same remote, and one of them has a higher priority, immediately closing the one with the lower priority is a bad idea, because the remote might not know that the one with the higher priority has been open yet. There's no quick and easy fix to that, as the end of the handshake of the higher-prio connection might get lost or take a shorter path than the closing of the lower-prio connection. The only way to reliably do that is to wait for some data from the remote on the higher priority connection, which …

Fix simultaneous dialing test

---

CHANGELOG.md
Cargo.toml
protocols/noise/Cargo.toml

I forgot to bump the version of libp2p-noise.
Very stupid mistake, but since I've already tagged and released v0.4.0, we should do a v0.4.1 for that.

Fix version of noise

---

protocols/identify/src/periodic_id_handler.rs

Right now we report that the connection is useless right after we send the identify request.
Instead, we should wait for the answer.

Disconnect only after the identify answer

---

protocols/ping/src/handler.rs
protocols/ping/src/lib.rs

#884 simplified ping too much by removing the system that was actually periodically pinging nodes.
This reintroduces a handler that wraps around the `OneShotHandler` and adds back the mechanism.

Ping wasn't working anymore

---

core/src/nodes/handled_node_tasks.rs

If no tokio executor is available, we fall back to executing tasks directly.
This is mostly for #23

Fall back if no tokio executor available

---

misc/rw-stream-sink/Cargo.toml
misc/rw-stream-sink/src/lib.rs

Right now, `RwSinkStream::read` tries to pull as many items as possible from the underlying stream.
Unfortunately, if an error happens while we have already read some data, the current implementation returns `Ok(num_bytes_read)` instead of returning the error.
This PR changes the code `RwSinkStream` to:
- Be way more simple, and thus with way fewer possible sources of issues.
- Stop reading after the current item is done, instead of pulling the following one. It will still skip over empty items so as to not accidentally return `Ok(0)` when there are more items remaining.

Fix error being ignored in RwSinkStream

---

muxers/yamux/src/lib.rs

Related: https://github.com/paritytech/yamux/pull/44

Call `Connection::close` in `StreamMuxer::shutdown`.

---

protocols/kad/src/behaviour.rs
protocols/kad/src/kbucket.rs

Right now the API of k-buckets is pretty much magic. There are tons of corner cases that aren't covered.
This PR makes the API clearer so that the behaviour behaves properly.
Work-in-progress because this needs a review pass from me, and because more tests are needed.
Also we probably want to make time management from the k-buckets part of the API, for better testability and for WASM.

Rewrite the Kademlia k-buckets to be more explicit

---

protocols/kad/src/addresses.rs
protocols/kad/src/behaviour.rs
protocols/kad/src/kbucket.rs

Based on top of #996 
Rewrites the `Addresses` struct to be just a simple list of addresses.
Now that the k-buckets struct is more robust, we can reliably know whether we are connected or not to that node and don't need to have the information in `Addresses` anymore.

Simplify the Addresses

---

protocols/kad/src/behaviour.rs

Based on top of #1012 
Adds a method for querying the list of known peers.

Add Kademlia::kbuckets_entries()

---

misc/multihash/Cargo.toml
misc/multihash/src/lib.rs

You already use two hash crates from RustCrypto and it's a bit strange to use `sha1` and `tiny-keccak` instead of `sha-1` and `sha3`. Also migrating to them simplifies code a bit.

Replace sha1 and tiny-keccak with RustCrypto crates

---

core/src/swarm.rs
misc/core-derive/src/lib.rs
protocols/kad/src/behaviour.rs

The current API of `NetworkBehaviour` has some pretty big flaws:
- If we try to dial a node but we don't know any address for it, we ignore the problem and nothing happens (nothing is reported back).
- On dial failure, there's no way to know if the swarm is still trying to connect to a node through a different address or if it's no longer trying.
- Similarly, a dial failure kind of implies that we're not connected to the node, while it is possible, in the case of simulatenous dialing, that we report a dial failure *after* the connection.
This PR fixes that by splitting `inject_dial_failure` in two: `inject_dial_failure` only takes a `PeerId` and is called when we are no longer trying to dial, while `inject_addr_reach_failure` is called when we fail to reach a specific address. If this was …

Split address reach error and node reach error

---

protocols/kad/Cargo.toml
protocols/kad/src/behaviour.rs
protocols/kad/src/kad_hash.rs
protocols/kad/src/kbucket.rs
protocols/kad/src/lib.rs

We currently use `PeerId` directly as a key into a Kademlia table because it happens to be a hash of the address of a peer. However, the reference implementation uses a hash of the hash. This PR introduces a new struct, `KadHash` that is to be used instead as key.
There are actually two use cases for `PeerId`: as key into the Kademlia table and as an actual identifier of a peer. `KadHash` supports both by storing the `PeerId` and the new hash together.
Function `Kademlia::initialize()` has become obsolete and has been removed.
Function `Kademlia::without_init()` has been marked deprecated.
This PR includes minor fixes for warnings.
Addresses: #694

[Kademlia] Rehash PeerId before inserting in a KBucketsTable

---

README.md

Adds [Lighthouse](https://github.com/sigp/lighthouse) to the list of projects using rust-libp2p :).

Add lighthouse to list of projects

---

core/src/transport/memory.rs

Partially addresses issues #973. 
To replace unbounded channels in `handled_node_tasks` would have implications that warrant further consideration, recommend to revisit at a later time.

Use bounded channels in transport

---

core/src/swarm.rs
core/src/swarm/toggle.rs

Allows having a disabled `NetworkBehaviour`.
This PR also adds implementations of `ProtocolsHandler` and `IntoProtocolsHandler` that can be disabled, but they remain "private" (as in, they can't be constructed).
This is because they accept events but will panic if they receive one, which can be a very unintuitive behaviour.

Add a Toggle NetworkBehaviour

---

core/src/identity/secp256k1.rs

A small oversight discovered while looking through https://github.com/libp2p/rust-libp2p/pull/1029. Now the function implementation actually does what was already written in its documentation.

Add missing zeroize() call for secp256k1::SecretKey::from_bytes.

---

protocols/noise/src/io.rs

This is a patch extracted from https://github.com/libp2p/rust-libp2p/pull/1027 concerning the reading and writing of frame lengths, since the fate of that PR it still unclear.

Patch reading/writing frame lengths in libp2p-noise.

---

core/src/transport/mod.rs
muxers/mplex/tests/two_peers.rs
protocols/identify/src/protocol.rs
transports/tcp/Cargo.toml
transports/tcp/src/lib.rs

Wildcard IP addresses (e.g. 0.0.0.0) are used to listen on all host interfaces. To report those addresses such that clients know about them and can actually make use of them we use the `get_if_addrs` crate and maintain a collection of addresses. We report the whole expansion at the
very beginning of the listener stream with `ListenerEvent::NewAddress` events and add new addresses should they come to our attention.
What remains to be done is to potentially allow users to filter IP addresses, for example the local loopback one, and to detect expired addresses not only if a new address is discovered.

Expand wildcard IP addresses in TCP transport.

---

misc/multiaddr/src/util.rs
misc/multiaddr/tests/lib.rs

The current implementation does not properly reserve enough space for `Write::write_all` to succeed. The property test has been improved to trigger that issue.

Fix `multiaddr::util::BytesWriter`.

---

core/src/protocols_handler/mod.rs
core/src/protocols_handler/node_handler.rs

Small addendum to #1072:
* Missed two review comments related to documentation.
* Avoid creating new `Delay`s when possible, e.g. when the deadline did not change or only changed to a different instant, since they're not exactly cheap (an `Arc`ed  [Entry](https://github.com/tokio-rs/tokio/blob/master/tokio-timer/src/timer/entry.rs#L110-L120)) and returning `KeepAlive::Until(t)` with the same or a different instant `t` over a prolonged period of time is common. If the instant is the same, this is now a no-op and if they're different it uses [Delay::reset()](https://docs.rs/tokio-timer/0.2.10/tokio_timer/struct.Delay.html#method.reset).

Small addendum to #1072.

---

core/src/protocols_handler/dummy.rs
core/src/protocols_handler/mod.rs
core/src/protocols_handler/node_handler.rs
core/src/protocols_handler/one_shot.rs
core/src/swarm/toggle.rs
core/tests/raw_swarm_dial_error.rs
core/tests/raw_swarm_simult.rs
protocols/identify/src/listen_handler.rs
protocols/identify/src/periodic_id_handler.rs
protocols/kad/src/handler.rs
protocols/ping/src/handler.rs

Rename `KeepAlive` constructors as suggested in #1072:
* `KeepAlive::Now` => `KeepAlive::No`
* `KeepAlive::Forever` => `KeepAlive::Yes`
This branch sits on top of https://github.com/libp2p/rust-libp2p/pull/1077. The only new commit is  d5323ef .

Rename `KeepAlive::Now` and `KeepAlive::Forever`.

---

examples/ping.rs
protocols/ping/src/handler.rs
protocols/ping/tests/ping.rs

Admittedly a bit of a back-and-forth, but this is now a very simple option serving multiple purposes:
* It allows for stable (integration) tests involving a Swarm, which
are otherwise subject to race conditions due to the connection being
allowed to terminate at any time with `KeepAlive::No`
(which remains the default).
* It makes for a more entertaining ping example which continuously
sends pings.
* Maybe someone wants to use the ping protocol for application-layer
connection keep-alive after all.
See also the discussion in https://github.com/libp2p/rust-libp2p/pull/1086.

Add back simple, optional keep-alive to libp2p-ping.

---

protocols/kad/src/behaviour.rs

In `Kademlia`, two similar methods: `add_providing` and `remove_providing` take different types. There is no need for `add_providing` to take a `PeerId`, it can take a `&Multihash` just like `remove_providing`.

Replace PeerId with Multihash for interface consistency

---

core/src/swarm.rs
core/src/swarm/behaviour.rs
core/src/swarm/registry.rs
core/src/swarm/swarm.rs

Keep external addresses in a ranked collection and ensure iteration is performed in order from highest to lowest rank. The implementation assumes that iteration dominates over modification and optimises for the former.
For context see issue #794.

Add ranked address collection.

---

protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/handler.rs
protocols/kad/src/query.rs

Addresses https://github.com/libp2p/rust-libp2p/issues/341 which is the cause for one of the observations made in https://github.com/libp2p/rust-libp2p/issues/1053. However, the latter is not considered to be fully addressed by these changes and needs further investigation.
Currently, whenever a search for a key yields a response containing the initiating peer as one of the closest peers known to the remote, the local node attempts to dial itself. That attempt is [ignored by the Swarm](https://github.com/libp2p/rust-libp2p/blob/master/core/src/swarm/swarm.rs#L185), but the Kademlia behaviour now believes it still has an RPC ongoing which will eventually time out. That timeout delays successful completion of the query. Hence, any query where a remote responds with the ID of the local node …

Fix self-dialing in Kademlia.

---

src/lib.rs

I forgot to add that when adding the WASM external transport.

Reexport libp2p-wasm-ext from the libp2p facade

---

protocols/kad/src/behaviour.rs

Although not explicitly mentioned in the paper, it seems clear that including an entry for the requesting peer in a `FIND_NODE` response never gives useful information and just occupies a result slot that may have been better filled with another peer that the requestor may not know about.
There is one explicit mention that this is the desired behavior in a somewhat dated design document of another p2p framework [1]:
"The recipient of a FIND_NODE should never return a triple containing the nodeID of the requestor."
The same reasoning supposedly applies to the libp2p-specific `GET_PROVIDERS` request.
I haven't checked whether the js or go implementations do this but am interested to learn whether they do this or not and for what reasons.
[1] …

Filter requesting peer from results.

---

core/src/nodes/raw_swarm.rs
core/src/protocols_handler/mod.rs
core/src/protocols_handler/node_handler.rs
core/src/protocols_handler/select.rs
core/src/swarm/toggle.rs

Fix #1054 
This works by having the `RawSwarm` pass `(TConnInfo, ConnectedPoint)` instead of `TConnInfo` to the lower layers, so that lower layers don't know who we are connected to (as should be the case).
There's one design issue remaining: we create a dummy protocols handler in `Swarm` in order to determine which protocols we support. In this PR, I pass a dummy `ConnectedPoint` when doing so. This is obviously a bad solution that should be fixed by not creating a dummy protocols handler.

Pass the ConnectedPoint to into_handler()

---

core/src/either.rs
core/src/muxing.rs
core/src/muxing/singleton.rs
core/src/transport/dummy.rs
misc/multistream-select/src/lib.rs
misc/rw-stream-sink/src/lib.rs
muxers/mplex/src/lib.rs
muxers/yamux/src/lib.rs
protocols/noise/Cargo.toml
protocols/noise/src/io.rs
protocols/noise/src/io/handshake.rs
src/bandwidth.rs
transports/ratelimit/Cargo.toml
transports/ratelimit/src/lib.rs
transports/tcp/Cargo.toml
transports/tcp/src/lib.rs
transports/wasm-ext/src/lib.rs
transports/websocket/Cargo.toml
transports/websocket/src/browser.rs

Fixes #1080 
Most of the CPU usage is in `memcpy` (EDIT: and `memset`), so this should hopefully give a speed boost to the library.
Also adds `prepare_uninitialized_buffer` to the `StreamMuxer` trait.

Add implementations of prepare_uninitialized_buffer and read_buf where relevant

---

core/src/lib.rs

This type is used extremely often, and it's nested deep in `nodes::raw_swarm`. Let's re-export it at a more convenient location.

Reexport ConnectedPoint at the root

---

core/src/transport/mod.rs
core/src/transport/optional.rs

Basically a glorified `Option<T>`.
The reason for this, is that in a WASM context you want to pass an external transport, but in a non-WASM context you want not to.
Thanks to an `OptionalTransport<wasm_ext::ExtTransport>`, you can share the same code between WASM and non-WASM.

Add an OptionalTransport type

---

core/src/identity/ed25519.rs

The ED25519 verify method wasn't checking if the actual verification was successful, but was only checking if the signature decoding was successful. 
The RSA and Secp256k1 keys logic looks valid.

Fix ED25519 signature validation

---

core/src/identity/secp256k1.rs

Has been removed during the switch to `libsecp256k1` and there's no replacement.

Add secp256k1::SecretKey::to_bytes

---

core/src/swarm/swarm.rs
examples/ipfs-kad.rs
protocols/kad/src/addresses.rs
protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/kbucket.rs
protocols/kad/src/kbucket/bucket.rs
protocols/kad/src/kbucket/entry.rs
protocols/kad/src/kbucket/key.rs
protocols/kad/src/lib.rs
protocols/kad/src/protocol.rs
protocols/kad/src/query.rs

Based on https://github.com/libp2p/rust-libp2p/pull/1108.
The current implementation for finding the entries whose keys are closest to some target key in the Kademlia routing table involves copying the keys of all buckets into a new `Vec` which is then sorted based on the
distances of the entries to the target and turned into an iterator from which only a small number of elements (by default 20) are drawn.
This commit introduces an iterator for finding the closest keys (or entries) to a target that visits the buckets in the optimal order, based on the information contained in the distance bit-string representing the distance between the local key and the target (introduced in https://github.com/libp2p/rust-libp2p/pull/1108). I.e. the needed contents of the respectively next bucket are …

Kademlia: Optimise iteration over closest keys / entries.

---

protocols/kad/src/behaviour.rs

This is a minimal patch extracted from https://github.com/libp2p/rust-libp2p/pull/1154 that may be worthwhile incorporating on its own. Currently, when a connection to a peer is established, only the first pending RPC found for that peer is sent, although there may be multiple (from concurrent queries). I chose the simplest possible fix (`if let` -> `while let`) as the list of pending RPCs is assumed to be small, if not empty. An alternative may be to partition the list into two new `SmallVec`s, keeping one and iterating over the other to send the RPC events, but I really can't say if that is worthwhile doing as I haven't benchmarked.

Kademlia: Send all pending RPCs for a peer on established connection.

---

protocols/kad/src/query.rs

This is a minimal fix for https://github.com/libp2p/rust-libp2p/issues/1105 extracted from https://github.com/libp2p/rust-libp2p/pull/1154 that may be worthwhile incorporating on its own and potentially useful for https://github.com/libp2p/rust-libp2p/pull/1144 (context https://github.com/montekki/rust-libp2p/pull/1#issuecomment-497923800).

Kademlia: Fix premature query termination.

---

core/src/nodes/collection.rs
core/src/nodes/handled_node_tasks.rs
core/src/nodes/raw_swarm.rs

Makes it possible to inject an already-open connection into the `RawSwarm`.
This is a step towards #1134. When we get a new connection through a relay, we want to inject it in the `RawSwarm` as if it was a full connection.

Allow injecting an existing connection in the RawSwarm

---

core/src/nodes/collection.rs
core/src/nodes/raw_swarm.rs
core/src/protocols_handler/node_handler.rs
core/src/swarm/swarm.rs

Close #1084
Allows parametrizing the `Swarm` with a `TConnInfo`. Later you can then call `Swarm::connection_info` to retrieve the information of an existing connection.

Allow customizing the Swarm with TConnInfo

---

core/src/protocols_handler/select.rs

Removes a redundant loop in `ProtocolsHandler::Select`. 
This then allows `Clippy` to run over libp2p.

Remove redundant loop

---

core/Cargo.toml
protocols/noise/Cargo.toml

The `libp2p-noise` crate presently seems to be one of the biggest users of zeroize v0.8 by downloads.
I'm trying to phase out (and eventually yank) v0.8 for reasons it isn't impacted by: namely it included an implicit Drop impl in its custom derive support, and I'm trying to backtrack on that and ensure it's always explicit. But before that, I want to make sure nobody is expecting an explicit Drop impl when one won't be provided.
Before I yank it, I want to ensure existing users are up-to-date. This crate doesn't use `zeroize_derive`, but to phase out the old API I need to get everyone on v0.9.

zeroize: Upgrade to v0.9

---

Cargo.toml
src/lib.rs
transports/websocket/Cargo.toml
transports/websocket/src/framed.rs
transports/websocket/src/lib.rs

Due to the way feature resolution works in cargo today, the `deflate` feature of `soketto` will include `flate2` with feature `zlib` which is then also active for the `flate2` that `libp2p-deflate` depends on. This leads to compilation failures for WASM targets. This PR therefore moves `libp2p-deflate` to the crates which are not available on WASM.

Update soketto and enable deflate extension.

---

protocols/kad/src/behaviour.rs
protocols/kad/src/query.rs

This is a suggested refactoring of iterative queries (`query.rs`). It addresses the following issues:
1. Queries no longer terminate prematurely due to counting results from peers farther from the target while results from closer peers are still pending. (#1105).
2. Queries no longer ignore reported closer peers that are not duplicates just because they are currently not among the `num_results` closest. The currently `num_results` closest may contain peers marked as failed      or pending / waiting. Hence all reported closer peers that are not duplicates must be considered candidates that may still end up among the `num_results` closest that successfully responded.
3. Bounded parallelism based on the `active_counter` was not working correctly, as new (not yet contacted) peers closer to …

Kademlia: Refactor iterative queries.

---

core/src/muxing.rs
muxers/mplex/tests/async_write.rs

Documentation of `tokio::io::AsyncWrite::shutdown` says "Invocation of a shutdown implies an invocation of flush." But `SubstreamRef`'s impl of `AsyncWrite` did not.
This caused `Floodsub` (which uses `WriteOne` that justifiably assumes this invariant of `AsyncWrite` and `shutdown`s socket after writing) to fail to communicate via mplex.

Make `<SubstreamRef as AsyncWrite>::shutdown` imply flush

---

core/src/nodes/handled_node_tasks.rs

Instead of using `status()`, we can directly use `execute()` and get back the future on failure.
It wasn't done before because tokio's `spawn()` method returns an error that doesn't yield back the future.

Small cleanup in spawning tasks

---

transports/tcp/src/lib.rs

The transport should be able to continue processing other connections. An error to determine a socket's address is not a fatal condition but may happen when a connection is immediately reset after being established. By the time the programme asks for the remote address, the socket may already be gone.
Fixes #1182.

libp2p_tcp: Ignore sockets without local/remote addr.

---

misc/multihash/Cargo.toml
misc/multihash/src/hashes.rs
misc/multihash/src/lib.rs

To improve the efficiency of cloning multi-hashes (e.g. as the representation of `PeerId`s), this PR replaces the `Vec<u8>` representation with `Bytes`. The API is largely kept backwards compatible and does not leak the representation type.

multihash: Use `Bytes` instead of `Vec<u8>` internally.

---

core/src/nodes/network.rs
core/src/translation.rs
misc/multiaddr/src/lib.rs
swarm/src/lib.rs

When receiving an observed address on a tcp connection that we initiated, the
observed address contains our tcp dial port, not our tcp listen port. We know
which port we are listening on, thereby we can replace the port within the
observed address. This is done in `core/src/translation`.
So far `fn address_translation` would drop any non ipv4 or ipv6 protocols. This
is problematic in the following setup:
A multi node Substrate cluster where nodes discover each other via their dns
addresses. After A innitiated a connection to B, B sends a indentification
request to A. B is listed in A's `observed_addresses` by its dns address, as A
initiated the connection, thereby it sends back the dns address of B. When B
receives the response it runs it through the `address_translation` function to …

 core/src/translation: Support dns4 and dns6

---

muxers/mplex/src/lib.rs

Addresses https://github.com/libp2p/rust-libp2p/issues/1206 by always registering the current task before calling `poll_*_notify` functions. This is in the same spirit as the corresponding fix for yamux in https://github.com/paritytech/yamux/pull/54.
Also adds missing registration of the current task in `close()` and `flush_all()`, which have been observed to cause stalls when trying to do a graceful connection shutdown / close in certain tests. This is the issue I was running into in the context of some other work and which caused me to submit this patch to cover https://github.com/libp2p/rust-libp2p/issues/1206 as well.

[mplex] Fix missed task notifications.

---

misc/multistream-select/Cargo.toml
misc/multistream-select/src/dialer_select.rs
misc/multistream-select/src/error.rs
misc/multistream-select/src/length_delimited.rs
misc/multistream-select/src/lib.rs
misc/multistream-select/src/listener_select.rs
misc/multistream-select/src/protocol/dialer.rs
misc/multistream-select/src/protocol/error.rs
misc/multistream-select/src/protocol/listener.rs
misc/multistream-select/src/protocol/mod.rs
misc/multistream-select/src/tests.rs

In preparation for the eventual switch from tokio to std futures, this PR removes the `tokio-codec` dependency from `multistream-select`. This includes some initial refactoring / cleanup in preparation for further work on `multistream-select` in the larger context of https://github.com/libp2p/rust-libp2p/issues/659 - I'm just trying to work in small(er) increments to make the changes more digestible.

Remove tokio-codec dependency from multistream-select.

---

protocols/kad/Cargo.toml
protocols/kad/src/kbucket.rs
protocols/kad/src/kbucket/key.rs

The `bigint` crate is deprecated and has been superseded by the `uint` crate for a while. It is only used by `libp2p-kad`.

[libp2p-kad] Replace usage of deprecated bigint crate.

---

protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs

Ensure that any still pending RPCs related to a query are removed once the query terminates (successfully or through timeout). It seemed most appropriate to scope pending RPCs to queries so that any such remaining events are dropped together with the query when the query terminates (for whatever reason).

[libp2p-kad] Scope pending RPCs to queries.

---

protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/handler.rs
protocols/kad/src/jobs.rs
protocols/kad/src/protocol.rs
protocols/kad/src/record.rs
protocols/kad/src/record/store.rs
protocols/kad/src/record/store/memory.rs

This PR proposes a generalization of record keys from `Multihash` to a new opaque `record::Key` type, as previously mentioned and discussed in [the context of PR #1189](https://github.com/libp2p/rust-libp2p/pull/1189/files#r299686846).

[libp2p-kad] Generalise record keys.

---

misc/multistream-select/Cargo.toml
misc/multistream-select/src/negotiated.rs

This addresses https://github.com/libp2p/rust-libp2p/issues/1227. The wrong argument was being passed to `BytesMut::split_off`. The properties of the `remaining` buffer, in particular that it never increases, are now checked.

[multistream-select] Fix restoring remaining buffer on write error in Negotiated I/O streams.

---

misc/multistream-select/src/negotiated.rs

The current `Display` impl for `NegotiationError` is pointless, since it uses `Error::description` which is both deprecated and not overridden for `NegotiationError`, thus the the `Display` impl produces  the unhelpful message: "description() is deprecated; use Display". This is corrected in this PR.

[multistream-select] Fix Display impl for NegotiationError.

---

core/src/nodes/tasks/manager.rs
muxers/mplex/src/lib.rs
swarm/src/lib.rs

Addresses some reviewing in #1196

Address some reviewing

---

core/src/transport/mod.rs
core/src/transport/upgrade.rs
core/src/upgrade/apply.rs
core/src/upgrade/mod.rs
core/tests/network_dial_error.rs
core/tests/network_simult.rs
core/tests/transport_upgrade.rs
misc/multistream-select/src/dialer_select.rs
misc/multistream-select/src/lib.rs
misc/multistream-select/src/listener_select.rs
misc/multistream-select/src/negotiated.rs
misc/multistream-select/src/protocol.rs
misc/multistream-select/src/tests.rs
muxers/mplex/tests/async_write.rs
muxers/mplex/tests/two_peers.rs
protocols/deflate/tests/test.rs
protocols/identify/src/identify.rs
protocols/identify/src/protocol.rs
protocols/kad/src/behaviour/test.rs
protocols/noise/src/lib.rs
protocols/noise/tests/smoke.rs
protocols/ping/src/protocol.rs
protocols/ping/tests/ping.rs
protocols/secio/src/algo_support.rs
protocols/secio/src/lib.rs
src/lib.rs
swarm/src/protocols_handler/mod.rs
swarm/src/protocols_handler/node_handler.rs
swarm/src/protocols_handler/select.rs

This is a proposal for making the multistream-select protocol (version) configurable both on transport upgrades as well as for individual substreams. It adds a new "lazy" version of multistream-select 1.0 that is identical on the wire but delays sending of negotiation protocol frames as much as possible, which is only safe to use under additional assumptions that go beyond what is required by the multistream-select v1 specification (see the inline doc-comment on `Version::V1Lazy` and the discussion in https://github.com/libp2p/rust-libp2p/pull/1212).
There are a couple of motivations behind this:
1. It will arguably be necessary eventually to be able to specify the multistream-select protocol version to use, at least as a dialer, to ever support 0-RTT negotiation in the presence of …

Configurable multistream-select protocol. `V1Lazy` variant.

---

transports/tcp/src/lib.rs

These options were tokio-specific and are not available on the `async_std::TcpStream`. They aren't available either in [the stdlib's `TcpStream`](https://doc.rust-lang.org/stable/std/net/struct.TcpStream.html). I had commented them out for now, but let's remove them!

Remove some config on the TcpConfig

---

examples/chat.rs

`use`ing more items at the start makes the code a bit more concise (`AsyncRead + AsyncWrite` vs  `libp2p::tokio_io::AsyncRead + libp2p::tokio_io::AsyncWrite` etc).

Improve the code readability of the chat example

---

transports/tcp/src/lib.rs

I embedded the logic of the `Listener` within the `TcpListener` in order to make it work with async/await, therefore I have no real choice but to remove the corresponding test.

Make the TCP tests compile again

---

protocols/kad/Cargo.toml
protocols/kad/src/behaviour.rs
protocols/kad/src/handler.rs
protocols/kad/src/jobs.rs
protocols/kad/src/protocol.rs

I didn't check if the tests were working (they're most likely not) because they depend on `libp2p-yamux`, which isn't upgraded yet.

Upgrade libp2p-kad to stable futures

---

.circleci/config.yml

I suspect https://hub.docker.com/r/parity/rust-builder to be old.

Try fix CI

---

misc/multiaddr/Cargo.toml
misc/multiaddr/src/protocol.rs
transports/websocket/Cargo.toml

This brings `url` and `percent-encoding` up to latest.
For `percent-encoding` I followed the [upgrading guide](https://github.com/servo/rust-url/blob/master/UPGRADING.md#upgrading-from-percent-encoding-1x-to-2x) to address the resulting API breakage.

Upgrade url and percent-encoding deps to 2.1.0

---

core/Cargo.toml
misc/rw-stream-sink/Cargo.toml
misc/rw-stream-sink/src/lib.rs
transports/websocket/Cargo.toml
transports/websocket/src/framed.rs
transports/websocket/src/lib.rs
transports/websocket/src/tls.rs

Currently pointing to twittner's repo until the corresponding PR is merged. Also forces futures-preview to alpha.18 dues to breaking changes w.r.t. AsyncRead's initializer API.

Upgrade websocket transport to soketto 0.3.0.

---

protocols/noise/Cargo.toml

Fixes https://github.com/RustSec/advisory-db/pull/192

[noise]: `sodiumoxide ^0.2.5`

---

examples/ipfs-kad.rs

The `Kademlia::without_init` function was removed in https://github.com/libp2p/rust-libp2p/pull/1174/. This commit removes the outdated comment in the `examples/ipfs-kad.rs` file.

examples/ipfs-kad.rs: Remove outdated reference to `without_init`

---

core/Cargo.toml
core/src/nodes/listeners.rs
core/src/transport/memory.rs
core/tests/network_dial_error.rs
core/tests/network_simult.rs
core/tests/transport_upgrade.rs
core/tests/util.rs

Fixes the tests in `libp2p-core`.
As a consequence, the `MemoryTransport` now uses `Vec<u8>` instead of `Bytes`, because it wouldn't be compatible with secio otherwise.

[stable-futures] Switch MemoryTransport to Vec<u8> and fix tests

---

.circleci/config.yml

PR tests were failing on CircleCI due to an account limitation (no support for Docker Layer Caching).
Fix: Removed the DLC flag.
Side effects: Tests take longer to run (~15 minutes for the `test` workflow, ~2 minutes for the `integration-test` workflow, ~3 minutes for `test-wasm`).
Better slow than never? 😅

CircleCI Test Fix

---

core/Cargo.toml
protocols/noise/Cargo.toml

v1.0 final release is out. Release notes:
https://github.com/iqlusioninc/crates/pull/279

zeroize: Upgrade to v1.0

---

core/Cargo.toml

Fixes `libp2p-core` not compiling when compiled alone.

Enable the std feature of ring

---

core/src/identity/ed25519.rs
core/src/identity/secp256k1.rs

Sidenote: I see a bunch of deprecated functions, Rust 2015 stuff and `std::mem::uninitialized`. Is anyone going to update this project?

Implement Debug for (ed25519/secp256k1)::(Keypair|SecretKey)

---

protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs

Fixes https://github.com/libp2p/rust-libp2p/issues/1290. When the number of active queries exceeds the (internal) JOBS_MAX_QUERIES limit, which is only supposed to bound the number of concurrent queries relating to background jobs, an arithmetic overflow occurs. This is fixed by using saturating subtraction.

Fix possible arithmetic overflow in libp2p-kad.

---

protocols/plaintext/src/lib.rs

Following up on https://github.com/libp2p/rust-libp2p/pull/1277 this pull requests adds a basic example explaining how to upgrade a `Transport` with `PlainText1Config`.

protocols/plaintext: Add example on how to upgrade with PlainTextConfig1

---

protocols/noise/src/io.rs
protocols/noise/src/io/handshake.rs

Adapt libp2p's noise implementation to breaking changes of snow 0.16. Follow up to https://github.com/libp2p/rust-libp2p/pull/1265 for the *stable-futures* branch.
In addition fix wrong import path for protobuf structs introduced in https://github.com/libp2p/rust-libp2p/pull/1275.

protocols/noise: Adapt to breaking changes in snow 0.16 and proto generation

---

protocols/identify/Cargo.toml
protocols/identify/src/handler.rs
protocols/identify/src/identify.rs

It turns out that nightly Rust ICEs when using enum with zero variants.
See https://github.com/rust-lang/rust/issues/65462
We were hoping that this ICE would eventually be fixed, but it's about to hit stable and it still isn't fix.
The solution now is unfortunately to remove using empty enums from our API.
Should be merged before #1294

Remove using void to bypass ICE

---

muxers/mplex/Cargo.toml

Signed-off-by: koushiro <koushiro.cqx@gmail.com>
Seems to forget to upgrade the `parking_lot` dep of the `mplex` to v0.9

Update parking_lot to v0.9

---

muxers/yamux/Cargo.toml
muxers/yamux/src/lib.rs

This PR uses the Yamux development version which is based on futures-preview 0.3.0-alpha.19. Since we use a boxed version of the incoming `futures::stream::Stream` of substreams, we offer two sets of upgrades, one which requires a `Send` bound on the underlying I/O resource, and one which does not. If memory serves me well, we have some upgrades such as secio whose output is `!Send`. If we do not plan to support `!Send`, we can of course remove half of this PR.

Update yamux to development version.

---

muxers/yamux/Cargo.toml

Upstream has been updated so we can use futures-0.3 now.

yamux: Use futures-0.3.

---

transports/uds/Cargo.toml
transports/uds/src/lib.rs

Switched from `romio` (which is unmaintained and is still using futures-preview) to `async-std`.

Update libp2p-uds to futures 0.3

---

CHANGELOG.md
protocols/plaintext/Cargo.toml
protocols/plaintext/src/handshake.rs
protocols/plaintext/src/lib.rs
protocols/plaintext/tests/smoke.rs
protocols/secio/src/codec/mod.rs

The plaintext 2.0 specification requires to use unsigned varints for
frame length delimiting instead of fixed 4 byte integer frame length
delimiting. This commit aligns the implementation with the
specification.

protocols/plaintext: Move to stable futures and use unsigned varints

---

transports/websocket/Cargo.toml
transports/websocket/src/framed.rs
transports/websocket/src/lib.rs

Updates to a soketto version that uses futures-0.3.x. Depends on https://github.com/paritytech/soketto/pull/8 and https://github.com/paritytech/quicksink/pull/1.

Use soketto's `reader-writer-split` branch.

---

Cargo.toml
src/bandwidth.rs
src/lib.rs
src/simple.rs
transports/dns/src/lib.rs

Mostly mechanical. Creating a `CommonTransport` yields an `io::Result<_>` now since creating the `DnsConfig` may fail with an `io::Error` when creating the `ThreadPool`.
The `BandwithLogging` `Transport` impl requires `Unpin` for everything. This could potentially be optimised at some point.
The `DnsConfig` `Transport` impl had to be changed slightly:
(a) PR [[1311]] requires some `Send` bounds.
(b) The async block had to be changed to work around lifetime inference issues which resulted in an "one type is more general than the other" error.
[1311]: https://github.com/libp2p/rust-libp2p/pull/1311

Update root crate to use futures-0.3.

---

transports/websocket/Cargo.toml
transports/websocket/src/framed.rs
transports/websocket/src/lib.rs

`websocket::framed::Connection` (formerly `websocket::framed::BytesConnection`) now uses the more structured types `IncomingData` and `OutgoingData` which mirror the data types in soketto (which are not exposed). This allows adding `Connection::send_ping` and `Connection::send_pong` methods.
The toplevel websocket transport defines `websocket::BytesConnection` as a wrapper around `websocket::framed::Connection` and handles only binary data.
Depends on https://github.com/paritytech/soketto/pull/9.

Add support for PINGs and PONGs to websockets.

---

misc/mdns/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/jobs.rs
protocols/noise/Cargo.toml

This pull request adjusts the Kademlia tests to the *stable future* refactoring.
(+ 2 minor fixes in noise and mdns)

protocols/kad: Fix tests

---

protocols/identify/Cargo.toml

The WASM CI build should be green again now.

Fix identify not compiling for wasm

---

protocols/secio/Cargo.toml
protocols/secio/src/codec/decode.rs
protocols/secio/src/codec/len_prefix.rs
protocols/secio/src/codec/mod.rs
protocols/secio/src/handshake.rs
protocols/secio/src/lib.rs

The secio spec states that each frame must be prefixed with a 32-bit big endian length prefix so we can not use an unsigned varint here.

secio: Back to 4-byte BE length prefix.

---

misc/multistream-select/src/length_delimited.rs
misc/multistream-select/src/negotiated.rs

Due to not taking into account `buf.len()` when computing `written`, it may be incorrectly judged less than `buf.len()`, which can result in duplicate data being written as well as potentially arithmetic overflow. This is essentially a backport of what was fixed for the `stable-futures` branch [here](https://github.com/libp2p/rust-libp2p/pull/1335#discussion_r355373145). However, instead of removing the optimisation of writing out the entire data in one go, as done there, this just corrects the oversight of not taking `buf.len()` into account when computing `written` in the `io::Write` impl of `LengthDelimitedReader`. The rest of the diff just adds some debug assertions for further clarity.
I'm not opposed to removing this kind of optimisation entirely, as it is evidently non-trivial to …

Fix possible incorrect return value from <LengthDelimitedReader as io::Write>::write().

---

misc/multistream-select/src/negotiated.rs

For consistency with what was already done in https://github.com/libp2p/rust-libp2p/pull/1335 but only for the `LengthDelimitedReader`. Since this diff is identical to the one proposed for `master` in https://github.com/libp2p/rust-libp2p/pull/1338, there shouldn't be any new conflicts.

[stable-futures] Remove a write optimisation in Negotiated.

---

misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

The custom derive lets you specify an extra "poll" function. We should pass the `&mut Context` to it.

Pass &mut std::task::Context to poll

---

protocols/noise/src/io.rs

Fixes `poll_flush` not calling the underlying `poll_flush` function.
Additionally, fixed `poll_close` to also flush, as required by the function.
Should be backported to master.

Fix noise/io.rs not flushing the underlying stream

---

core/Cargo.toml
core/src/either.rs
core/src/lib.rs
core/src/transport/choice.rs
core/src/transport/map.rs
core/src/transport/map_err.rs
core/src/transport/timeout.rs
core/src/upgrade/either.rs
core/src/upgrade/map.rs
core/src/upgrade/mod.rs
core/src/upgrade/select.rs

Removes a few left-overs, and lots of `Unpin` trait bounds replaced with `pin-project`.

Cleanups in libp2p-core in stable-futures branch

---

swarm/Cargo.toml
swarm/src/lib.rs

This is just a small PR that:
1. Adds logging for `NodeClosed` events, as otherwise the contained `error` is forever lost. I chose `trace` level for, but I guess `debug` would be ok, too. This is primarily useful when troubleshooting connection issues.
2. Simplifies some trait bounds.

[swarm] Log connection close in swarm. Simplify some bounds.

---

core/src/transport/mod.rs

The auto-linking didn't work properly as there is a method called `upgrade`
within the transport module.

Fix link to upgrade::Builder

---

core/Cargo.toml
protocols/floodsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/kad/Cargo.toml
protocols/noise/Cargo.toml
protocols/plaintext/Cargo.toml
protocols/secio/Cargo.toml

For the sake of it, let's force users to not use prost 0.6.0 that has a security vulnerability.

Force prost 0.6.1

---

protocols/noise/src/io.rs
transports/wasm-ext/src/lib.rs

This got lost in translation when converting from the `Read` trait (where `WouldBlock` is the equivalent of `Pending`) to the `AsyncRead` trait.

Fix WouldBlock being returned in wasm-ext

---

transports/tcp/Cargo.toml
transports/tcp/src/lib.rs
transports/uds/Cargo.toml
transports/uds/src/lib.rs

This adds two new structs `TokioTcpConfig` and `TokioUdsConfig` that are available when the `tokio` feature is enabled in respectively `libp2p-tcp` and `libp2p-uds`.
Additionally, the `TcpConfig` and `UdsConfig` struct now require the `async-std` feature to be enabled. It is enabled by default in `libp2p-tcp` and `libp2p-uds`.
See #1318 for context
What this PR does is wrap all the code within a macro named `codegen!` that is then invoked once for async-std and once for tokio. In the end this is the less bad solution in my opinon.
I went for leaving everything at indentation level 0 despite being within a macro, but that could be changed.

Support tokio in libp2p-tcp and libp2p-uds

---

protocols/ping/src/protocol.rs

Tiny one. This is so that pinging a rust-libp2p node from ipfs works even without passing -n 1
Before:
```
$ ipfs ping /ip4/127.0.0.1/tcp/33542/ipfs/12D3KooWRpXY8AwbhF9syneVPb6cyrsC9KYSjRywLPWb4mRNaqMu
PING 12D3KooWRpXY8AwbhF9syneVPb6cyrsC9KYSjRywLPWb4mRNaqMu.
Pong received: time=6.79 ms
Ping error: EOF
Ping error: stream reset
Ping error: stream reset
```
After:
```
$ ipfs ping  /ip4/127.0.0.1/tcp/39053/ipfs/12D3KooWFewRGcMQTDJEtYrCkAFfqXDEBQNG7BHgisfJHS9Fqt2S
PING 12D3KooWFewRGcMQTDJEtYrCkAFfqXDEBQNG7BHgisfJHS9Fqt2S.
Pong received: time=2.01 ms
Pong received: time=1.35 ms
Pong received: time=2.62 ms
Pong received: time=2.00 ms
Pong received: time=2.33 ms
Pong received: time=2.10 ms
Pong received: time=2.16 ms
Pong received: time=2.13 ms
Pong received: time=2.43 ms
Pong received: …
```

Allow multiple pings over one connection

---

protocols/floodsub/src/layer.rs
protocols/gossipsub/src/behaviour.rs

It seems they were copied from `Identify` and left unchanged.

Fix copy-paste error in doc string

---

misc/multiaddr/tests/lib.rs

Exclude port 0 which is not a valid port number for onion addresses.

multiaddr: Fix generation of arbitrary onion addr.

---

CHANGELOG.md
Cargo.toml
core/Cargo.toml
misc/core-derive/Cargo.toml
misc/mdns/Cargo.toml
misc/multiaddr/Cargo.toml
misc/multistream-select/Cargo.toml
misc/peer-id-generator/Cargo.toml
muxers/mplex/Cargo.toml
muxers/yamux/Cargo.toml
protocols/deflate/Cargo.toml
protocols/floodsub/Cargo.toml
protocols/gossipsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/kad/Cargo.toml
protocols/noise/Cargo.toml
protocols/ping/Cargo.toml
protocols/plaintext/Cargo.toml
protocols/pnet/Cargo.toml
protocols/secio/Cargo.toml
swarm/Cargo.toml
transports/dns/Cargo.toml
transports/tcp/Cargo.toml
transports/uds/Cargo.toml
transports/wasm-ext/Cargo.toml
transports/websocket/Cargo.toml

Bumps everything to 0.16.0, *including crates who version number was different*. For instance, libp2p-swarm was at 0.5.0 but I bumped it to 0.16.0 in order to remove possible confusions.
Since I've prepared this PR, I'm opening it now.
However some testing on Polkadot shows that random Kademlia queries no longer work, so we should fix that before publishing.

Publish 0.16.0

---

swarm/src/lib.rs

The stream for swarm will never terminate, and therefore does not have to
keep track of termination.
Implementing Fused markers can be done for several other futures as well, e.g. next() and next_event(). However, this would require turning them into structs that implicitly provide Future instead of async fns, which means a sea of type constraint boilerplate. Not sure if it is worth it...

Implement FusedStream for Swarm

---

CHANGELOG.md

This was almost a release without any mistake, except that I forgot to merge https://github.com/libp2p/rust-libp2p/pull/1454

Remove change that didn't make it

---

misc/core-derive/src/lib.rs

Since version 1.16, when the NetworkBehaviour derive macro, an error arises about an ambiguity when generating ProtocolsHandlerSelect, the compiler can't decide between `IntoProtocolsHandler::select` and `ProtocolsHandler::select`:
```
error[E0034]: multiple applicable items in scope
--> balthernet/src/wrapper.rs:28:10
|
28  | #[derive(NetworkBehaviour)]
|          ^^^^^^^^^^^^^^^^ multiple `select` found
|
note: candidate #1 is defined in an impl of the trait `libp2p::libp2p_swarm::ProtocolsHandler` for the type `balthazar::handler::Balthandler<_>`
--> balthernet/src/balthazar/handler.rs:82:1
|
82  | / impl<TUserData> ProtocolsHandler for Balthandler<TUserData>
83  | | where
84  | |     TUserData: fmt::Debug + Send + 'static,
85  | | {
...   |
344 | |     }
345 | | }
| |_^
= note: …
```

NetworkBehaviour derive fix IntoProtocolsHandler/ProtocolsHandler::select ambiguity

---

misc/multiaddr/src/onion_addr.rs

Because the `Self` type is `Onion3Addr<'a>` and the return type uses `'b`, the usage of `Self` as a constructor is illegal as per https://crater-reports.s3.amazonaws.com/pr-69340/try%239ff4d07208097950831ed4ea9d76feb1eafc8baa/reg/libp2p-plaintext-0.15.0/log.txt and the bug fix in https://github.com/rust-lang/rust/pull/69340. This PR fixes that problem for you.

Onion3Addr::acquire: fix bug due to differing lifetimes

---

.circleci/config.yml
core/src/connection/error.rs
core/src/connection/pool.rs
core/src/network.rs
core/src/network/event.rs
core/src/network/peer.rs
core/tests/network_dial_error.rs
swarm/src/lib.rs

https://github.com/libp2p/rust-libp2p/pull/1440 introduced a regression w.r.t. the reporting of dial errors. In particular, if a connection attempt fails due to an invalid remote peer ID, any remaining addresses for the same peer would not be tried (intentional) but the dial failure would not be reported to the behaviour, causing e.g. libp2p-kad queries to potentially stall.
In hindsight, I figured it is better to preserve the previous behaviour to still try alternative addresses
of the peer even on invalid peer ID errors on an earlier address. In particular because in the context of libp2p-kad it is not uncommon for peers to report localhost addresses while the local node actually has e.g. an ipfs node running on that address, obviously with a different peer ID, which is the scenario …

Fix regression w.r.t. reporting of dial errors.

---

protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/handler.rs

Within `Behaviour::record_received` the exponentially decreasing
expiration based on the distance to the target for a record is
calculated as following:
1. Calculate the amount of nodes between us and the record key beyond
the k replication constant as `n`.
2. Shift the configured record time-to-live `n` times to the right to
calculate an exponentially decreasing expiration.
The configured record time-to-live is a u64. If `n` is larger or equal
to 64 the right shift will lead to an overflow which panics in debug
mode.
This patch uses a checked right shift instead, defaulting to 0 (`now +
0`) for the expiration on overflow.
Fixes https://github.com/libp2p/rust-libp2p/issues/1491.

protocols/kad: Fix right shift overflow panic in record_received 

---

protocols/kad/src/behaviour.rs

`Kademlia::record_received` calculates the expiration time of a record
before inserting it into the record store. Instead of inserting the
record into the record store in any case, with this patch the record is
only inserted if it is not expired. If the record is expired a
`KademliaHandlerIn::Reset` for the given (sub) stream is triggered.
This would serve as a tiny defense mechanism against an attacker trying
to fill a node's record store with expired records before the record
store's clean up procedure removes the records.
---
This is a follow up for https://github.com/libp2p/rust-libp2p/pull/1492#discussion_r391765926. Instead of an issue I created a pull request right away given that the change set should be reasonably small.
**Major discussion point: Should we trigger a …

protocols/kad: Do not attempt to store expired record in record store

---

protocols/kad/src/record/store.rs

Right now it isn't possible to use `MemoryStore::with_config` from outside of `libp2p-kad`, because you can't build a `MemoryStoreConfig`.

Reexport MemoryStoreConfig

---

core/Cargo.toml
core/tests/network_dial_error.rs
core/tests/util.rs

This PR cleans up the integration tests in `libp2p-core` by removing the dependency on `libp2p-swarm`, which should make the tests a bit clearer since they no longer refer to either unused or unnecessary notions from `libp2p-swarm` and its `ProtocolsHandler`.

Clean up libp2p-core tests.

---

core/src/connection/listeners.rs
core/src/network.rs
core/src/network/event.rs
swarm/src/lib.rs

We would like to be able expire addresses when a listener closes.
Add an `addresses` field to the `ListenersEvent` and the `ListenerClosed` to hold the addresses of a listener that has just closed.  When we return a `ListenerClosed` network event, loop over the addresses and call `inject_expired_listen_address()` on each one.
Fixes: https://github.com/libp2p/rust-libp2p/issues/1482

Add addresses field for closing listeners

---

swarm/src/lib.rs

This addresses a potential issue with `notify_all` in the swarm discovered on another review of the code triggered by https://github.com/libp2p/rust-libp2p/pull/1509: If at least one connection was not ready (i.e. pending), only those (i.e. the pending) connections would be returned and considered on the next task wakeup, whereas those which were ready should also remain in the list of connections to notify on task wakeup and retry of `notify_all`. I admit that this deserves better testing, as does `libp2p-swarm` in general, which I hope to spend some more time on soon.

[libp2p-swarm] Correct returned connections from notify_all.

---

protocols/kad/src/behaviour.rs

Given that the order of `PeerId`s within the `GetProvidersOk.providers`
set is irrelevant but duplication is at best confusing this commit makes
use of a `HashSet` instead of a `Vec` to return unique `PeerId`s only.
---
Fixes https://github.com/libp2p/rust-libp2p/issues/1507.

protocols/kad/behaviour: Use HashSet to deduplicate GetProviders

---

core/src/connection/manager.rs
core/src/connection/manager/task.rs
core/src/connection/pool.rs
core/src/network.rs

The `Network::poll_broadcast` function has not proven to be useful. This
commit removes the mechanism all the way down to the connection manager.
With `poll_broadcast` gone there is no mechanism left to send commands
to pending connections. Thereby command buffering for pending
connections is not needed anymore and is thus removed in this commit as
well.
---
Fixes #1465.
Replaces https://github.com/libp2p/rust-libp2p/pull/1501.

core/src: Remove poll_broadcast connection notification mechanism

---

swarm/src/lib.rs
swarm/src/protocols_handler.rs
swarm/src/protocols_handler/one_shot.rs

This is supposed to address the issues I ran into with the recent introduction of `OneShotHandlerConfig`: https://github.com/libp2p/rust-libp2p/pull/1521#issuecomment-607254753.

Re-export OneShotHandlerConfig. Make fields public.

---

Cargo.toml
core/Cargo.toml
misc/multiaddr/Cargo.toml

Here's the situation:
- `parity-multiaddr` v0.7.2 on crates.io depends on `parity-multihash`.
- `parity-multiaddr` on the master branch depends on `multihash`.
- `libp2p-core` on the master branch depends on both `parity-multiaddr` v0.7.2 and `multihash` (not `parity-multihash`).
This causes compilation issues in `libp2p-mdns` because `libp2p_core::multihash::Multihash` is not the same type as `libp2p_core::multiaddr::multihash::Multihash`.
I noticed this issue while publishing version 0.17.0. Version 0.17.0 has been published except for `libp2p-mdns` (which has this compilation error) and `libp2p`.
Therefore this PR properly bumps `parity-multiaddr` to v0.8, and bumps `libp2p-core` to 0.17.1 in order to publish a fixed version.

Bump parity-multiaddr

---

protocols/kad/src/behaviour.rs

A node receiving a `GetRecord` request first checks whether it has the given record. If it does have the record it does not return closer nodes. (See https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/src/behaviour.rs#L1268-L1287)
A node that knows the record for the given key is likely within a neighborhood of nodes that know the record as well. In addition the node likely knows its neighboorhood well.
When querying for a key with a quorum of 1 the above behavior of only returning the record but not any close peers is fine. Once one queries with a higher quorum having a node respond with the record as well as close nodes is likely going to speed up the query, given that the returned peers probably know the record as well.
This patch aligns the behavior of the `GetRecord` …

protocols/kad/behaviour: Return peers independent of record existence

---

CHANGELOG.md
protocols/floodsub/src/layer.rs
protocols/floodsub/src/lib.rs
protocols/floodsub/src/protocol.rs

minor feature to allow mimicing the behaviour expected by ipfs http api tests. default behaviour is not changed.

feat: allow sent messages seen as subscribed

---

CHANGELOG.md
transports/wasm-ext/src/websockets.js

cc @expenses 
This JS code hasn't really been properly reviewed by anyone unfortunately, and jumped a bit suddenly from "quickly written code to prototype" to "thing that we expect to be robust".
One consequence is that for some reason we checked `parsed != null` only after using `parsed`.

Fix parsed is null error

---

CHANGELOG.md
misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

There is a gnarly edge-case with the custom-derive where rustc cannot disambiguate the call if:
- The NetworkBehaviourEventProcess trait is imported
- We nest NetworkBehaviours that use the custom-derive
Without this patch, the test errors with:
```
error[E0034]: multiple applicable items in scope
--> misc/core-derive/tests/test.rs:219:14
|
219 |     #[derive(NetworkBehaviour)]
|              ^^^^^^^^^^^^^^^^ multiple `inject_event` found
|
note: candidate #1 is defined in an impl of the trait `libp2p_swarm::behaviour::NetworkBehaviourEventProcess` for the type `nested_derives_with_import::Foo`
--> misc/core-derive/tests/test.rs:225:9
|
225 |         fn inject_event(&mut self, _: libp2p::ping::PingEvent) {
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 …
```

Disambiguate calls to NetworkBehaviour::inject_event

---

core/src/connection/error.rs
core/src/connection/pool.rs
core/src/network.rs
core/src/network/event.rs

Currently connection limit errors emitted by a `Pool` when the per-peer connection limit is reached are emitted as `ConnectionError`s as soon as background task reports the connection as established, i.e. there is never a `ConnectionEstablished` event emitted in these cases. This is problematic for two reasons:
1. The `Network` code itself actually relies on an outgoing connection attempt to finish either with `PendingConnectionError` or `ConnectionEstablished`, otherwise there may even be a leak of entries in `self.dialing` which never get removed.
2. It actually was the intention that `Network::ConnectionEstablished` events are always paired up 1-1 with `Network::ConnectionError` events (though the latter should probably be renamed to `ConnectionClosed`). The `Swarm` relies on this …

Treat connection limit errors as pending connection errors.

---

CHANGELOG.md
Cargo.toml
core/Cargo.toml
misc/core-derive/Cargo.toml
misc/peer-id-generator/Cargo.toml
muxers/mplex/Cargo.toml
muxers/yamux/Cargo.toml
protocols/deflate/Cargo.toml
protocols/floodsub/Cargo.toml
protocols/gossipsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/kad/Cargo.toml
protocols/mdns/Cargo.toml
protocols/noise/Cargo.toml
protocols/ping/Cargo.toml
protocols/plaintext/Cargo.toml
protocols/pnet/Cargo.toml
protocols/secio/Cargo.toml
swarm/Cargo.toml
transports/dns/Cargo.toml
transports/tcp/Cargo.toml
transports/uds/Cargo.toml
transports/wasm-ext/Cargo.toml
transports/websocket/Cargo.toml

We're publishing 0.18.0 as it turns out that #1546 is a pretty important fix.
To be merged on top of https://github.com/libp2p/rust-libp2p/pull/1546

Publish 0.18.0

---

protocols/kad/src/query/peers/closest.rs

When not making progress for `parallelism` time a `ClosestPeersIter`
becomes `State::Stalled`. When stalled an iterator is allowed to make
more parallel requests up to `num_results`. If `num_results` is smaller
than `parallelism` make sure to still allow up to `parallelism` requests
in-flight.

protocols/kad/query/peers/closest: Make at_capacity use max 

---

CHANGELOG.md
Cargo.toml
swarm/Cargo.toml
swarm/src/lib.rs

Context: https://github.com/paritytech/substrate/issues/5684
There is an assumption right now in Substrate's code (and probably other) that, after we call `dial` or emit a `DialPeer`, the `inject_dial_failure` method is called if we know that we won't be able to reach the given node.
This is not the case right now in the situation where `addresses_of_peer` returns an empty list. In that situation, we ask the `Swarm` to connect to a node, and don't get any event whatsoever about that node ever again.
This PR modifies `dial` to emit the event if necessary, and simplifies the handling of `DialPeer` to rely more on the behaviour of `dial`.
In generally, I wish it was precisely documented and explained what happens in which situation, and that it is possible in any situation to track the state …

Make sure inject_dial_failure is called

---

CHANGELOG.md
transports/tcp/Cargo.toml
transports/tcp/src/lib.rs

The current behaviour of listening on an IPv6 address varies depending on the operating system's IP address stack implementation. Some support IPv4-mapped IPv6 addresses (e.g. Linux and newer versions of Windows) so a single IPv6 address would support IPv4-mapped addresses too. Others do not (e.g. OpenBSD). If they do, then some support them by default (e.g. Linux) and some do not (e.g. Windows).
This PR attempts to implement the same behaviour accross operating systems. The strategy is as follows:
Disable IPv4-mapped IPv6 addresses, hence the socket option IPV6_V6ONLY is always set to true.
This allows binding two sockets to the same port and also avoids the problem of comparing mixed addresses which leads to issues such as #1552.

tcp: Set IPV6_V6ONLY for IPv6 listeners.

---

misc/core-derive/src/lib.rs
misc/core-derive/tests/test.rs

Macro was using field_n (field index including ignored fields) for calculations instad of
enum_n (field index excluding ignored fields). When calculating the nesting the calculation
was made between the number of non-ignored fields and a field_n that lead to integer overflow.
Fixes #1553

fix: NetworkBehaviour crash if ignoring a non-last struct field

---

CHANGELOG.md
protocols/noise/src/io/handshake.rs
protocols/noise/src/io/handshake/payload.proto
protocols/noise/src/lib.rs
protocols/noise/src/protocol.rs
protocols/noise/src/protocol/x25519.rs
protocols/noise/src/protocol/x25519_spec.rs
protocols/noise/tests/smoke.rs

This PR is a proposal for adding a [libp2p-spec compliant](https://github.com/libp2p/specs/pull/260) Noise `Protocol` implementation for `x25519`, called `X25519Spec`. The differences to the existing `X25519` protocol are:
1. The spec-compliant protocol neither supports `IK` nor `IX`.
2. The spec-compliant protocol adds the `noise-libp2p-static-key:` prefix for signing and verifying static DH keys, i.e. a domain separator.
3. The spec-compliant protocol uses just `/noise` as the name for the protocol upgrade.
Please shout if I missed something required for spec compliance.
As an upgrade path, both a `NoiseConfig::xx` based on a `Keypair<X25519Spec>` as well as some other `NoiseConfig` based on a `Keypair<X25519>` could be used with a `SelectUpgrade`.
The protobuf changes are purely …

Spec-compliant Noise Protocol

---

protocols/kad/src/query/peers/fixed.rs

Make sure to decrease `num_waiting` when being notified of a peer
failure to allow an additional peer to be queried.
Given that `FixedPeersIter` is initialized with `replication_factor` by
`QueryPool` this bug will not surface today.

protocols/kad/query/fixed: Decrease num_waiting on failure

---

CHANGELOG.md
core/src/connection/pool.rs
core/src/network.rs
core/src/network/peer.rs
core/tests/network_dial_error.rs
swarm/src/behaviour.rs
swarm/src/lib.rs

This is a follow-up to https://github.com/libp2p/rust-libp2p/pull/1440 and relates to https://github.com/libp2p/rust-libp2p/issues/925. This PR permits multiple dialing attempts per peer.  The essence of the changes are that the `Peer` API in `libp2p-core` now provides `Peer::dial()`, i.e. regardless of the state in which the peer is. Previously dialing was only permitted on a `ConnectedPeer` or `DisconnectedPeer`. A dialing attempt is always made up of one or more addresses tried sequentially, as before, but now there can be multiple dialing attempts per peer. A configurable per-peer limit for outgoing connections and thus concurrent dialing attempts is also included. A `NetworkBehaviour` can now always request a new dialing attempt via `DialPeerCondition::Always` in …

Permit concurrent dialing attempts per peer.

---

protocols/kad/src/query/peers/closest.rs

Instead of creating unconstrained random number generators in quickcheck
tests to generate test data, have quickcheck provide a `Seed` to seed
those random number generators and thus make the test execution
deterministic / reproducible.

protocols/kad/query/closest: Make quickcheck deterministic

---

protocols/kad/src/behaviour.rs
protocols/kad/src/query.rs
protocols/kad/src/query/peers/fixed.rs

`FixedPeersIter` requires the initial set of peers to be passed as
`PeerId`s and not as `Key<PeerId>`s. This commit removes the unnecessary
conversion.
(*I would expect rustc or llvm to optimize this away anyways. I find it still worth
it to reduce complexity.*)

protocols/kad: Remove unnecessary PeerId conversion for fixed iter

---

protocols/pnet/src/lib.rs

This was an oversight of the original impl. Currently the only way to make a PSK is by parsing a PSK file. But sometimes you already have the raw bytes.
The raw bytes are just random data, so there is no harm in having a method to create a PreSharedKey
from the raw bytes.

Add a method to create a pre shared key when you have the raw bytes

---

CHANGELOG.md
core/src/connection/manager.rs
core/src/connection/pool.rs
core/src/network.rs
swarm/src/lib.rs

cc https://github.com/paritytech/substrate/issues/6009
Hints seem to indicate that we have some CPU issues in Substrate from the low number of events that can be buffered. This PR makes this limit configurable.
Additionally, this PR increases these values: the channel size from tasks to the swarm is now 32 (instead of 1!), and the channel size from the swarm to each task is now 7 (so 8 in practice).
When reviewing, keep in mind that channels reserve an extra element for each active sender, as documented: https://docs.rs/futures/0.3.5/futures/channel/mpsc/fn.channel.html
(I also slightly fixed the CHANGELOG to be alphabetically-ordered)

Make the number of events buffered to/from tasks configurable

---

CHANGELOG.md
core/src/translation.rs
misc/multiaddr/src/from_url.rs
misc/multiaddr/src/protocol.rs
misc/multiaddr/tests/lib.rs
transports/dns/src/lib.rs
transports/websocket/src/framed.rs

The `/dns` protocol has been added to the spec and has had a de-facto meaning for years (citing https://github.com/multiformats/multiaddr/pull/100)
This adds address parsing and encoding support for `/dns` to the multiaddr library.

Support /dns protocol in multiaddr

---

protocols/ping/src/protocol.rs

although 32 is prefect fine in our case, it would be consistent to use the const value PING_SIZE.

Keep consistency with Upgrade Inbound by using PING_SIZE

---

CHANGELOG.md
core/src/peer_id.rs

The `Debug` and `Display` implementations call `to_base58()`.
This PR transitions `to_base58()` to the "proper" string representation of the `PeerId`.
In other words, identity `PeerId`s will now start with `1...` rather than `Qm...`

Display the identity hash of PeerIds when relevant

---

.github/workflows/ci.yml

Try to fix the intra-link doc tests by pinning to an earlier nightly.
Note that the `Build and test` check will not pass because of #1588. I'm only testing `Check rustdoc intra-doc links`.

Try revert to nightly-2020-05-20

---

Cargo.toml
core/Cargo.toml
misc/multistream-select/Cargo.toml
muxers/mplex/Cargo.toml
protocols/deflate/Cargo.toml
protocols/gossipsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/mdns/Cargo.toml
protocols/noise/Cargo.toml
protocols/ping/Cargo.toml
protocols/secio/Cargo.toml
transports/tcp/Cargo.toml
transports/uds/Cargo.toml

This PR temporarily and conservatively bounds all `async-std` dependencies in libp2p to `< 1.6` as at least the noise smoke tests seem to stall with `1.6`. This is just a temporary defensive measure to stabilise CI and avoid surprises in releases, until the underlying issue has been figured out and https://github.com/libp2p/rust-libp2p/issues/1588 has been resolved.

Temporarily bound all async-std dependencies.

---

misc/core-derive/src/lib.rs

Currently writing code where one defines a type alias named `Result` combined with a type that uses `#[derive(NetworkBehaviour)]` sometimes leads to [E0107](https://doc.rust-lang.org/error-index.html#E0107).
```rust
type Result<T> = std::result::Result<T, Error>;
struct Error {}
#[derive(NetworkBehaviour)]
struct Behaviour<TStore> {
mdns: Mdns,
kad: Kademlia<TStore>,
}
// NetworkBehaviourEventProcess implementations...
```
```texterror[E0107]: wrong number of type arguments: expected 1, found 2
--> src/lib.rs:223:10
|
223 | #[derive(NetworkBehaviour)]
|          ^^^^^^^^^^^^^^^^ unexpected type argument
|
= note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
In my estimation this happens due to the use of `Result` in the …

Fully qualified std::result::Result in macro

---

protocols/noise/Cargo.toml
protocols/noise/src/protocol/x25519_spec.rs

This readds the (non-standardised/specced) `UpgradeInfo` implementations for `IK` and `IX` to `X25519Spec` which got lost in the back-and-forth of https://github.com/libp2p/rust-libp2p/pull/1545. It also enables the `async-std` feature for the `libp2p-tcp` dependency in the tests, so that the `libp2p-noise` tests compile again on their own.

Readd lost noise upgrades.

---

protocols/kad/src/lib.rs

You can't see their documentation on `docs.rs` at the moment.

Fix some libp2p-kad types not being reexported

---

README.md

Not sure if it is notable enough, but it is open source and looking for contributors, so it would be cool to have it listed here.

Add rust-ipfs to the list of notable users in the README.md

---

Cargo.toml
core/Cargo.toml
misc/multistream-select/Cargo.toml
muxers/mplex/Cargo.toml
protocols/deflate/Cargo.toml
protocols/gossipsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/mdns/Cargo.toml
protocols/ping/Cargo.toml
protocols/secio/Cargo.toml
transports/tcp/Cargo.toml
transports/uds/Cargo.toml

It turns out that Cargo has some issues with our `<1.6` requirement. If you have a project with both `libp2p` and a dependency on `async-std 1.0` (such as, for example, Polkadot), then Cargo will resolve libp2p's requirements as `async-std 0.99`.
Let's instead go with using the `~`, documented here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements
It is equivalent to `>=1.5.0, <1.6.0`.

Pin async-std in a different way

---

Cargo.toml
core/Cargo.toml
core/src/either.rs
misc/multistream-select/Cargo.toml
misc/multistream-select/src/negotiated.rs
protocols/pnet/Cargo.toml
protocols/secio/Cargo.toml

pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*

Remove uses of pin_project::project attribute

---

protocols/ping/src/protocol.rs

Not doing so may result in FIN/RST frames being sent and received before earlier data frames. See https://github.com/paritytech/yamux/pull/81#issuecomment-643169973. This seems to be the cause for https://github.com/paritytech/substrate/issues/6311 as it creates a possible race whereby FIN/RST frames may be received before data frames, causing ping upgrade failures.

[libp2p-ping] Properly close the substream in the InboundUpgrade.

---

protocols/ping/CHANGELOG.md
protocols/ping/Cargo.toml

Prepare bugfix release of `libp2p-ping`.

Add CHANGELOG and increment version to 0.19.2

---

core/src/connection.rs
core/src/connection/substream.rs
core/src/either.rs
core/src/muxing.rs
core/src/muxing/singleton.rs
muxers/mplex/src/lib.rs
muxers/yamux/src/lib.rs

This method was only used for the "simultaneous dialing system" in case two nodes were dialing each other at the same time.
This system has been removed a long time ago (#1440) and we can thus deprecate the corresponding method.

Deprecate StreamMuxer::is_remote_acknowledged

---

protocols/kad/src/query/peers/closest/disjoint.rs

[Type inference failed previously](https://gitlab.parity.io/parity/substrate/-/jobs/564937):
```
error[E0283]: type annotations needed for `(usize, &mut query::peers::closest::ClosestPeersIter)`
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.20.0/src/query/peers/closest/disjoint.rs:117:22
|
116 |             for (i, iter) in &mut self.iters.iter_mut().enumerate() {
|                              -------------------------------------- the element type for this iterator is not specified
117 |                 if i != (*initiated_by).into() {
|                      ^^ cannot infer type for type `usize`
|
= note: cannot satisfy `usize: std::cmp::PartialEq<_>`
error[E0283]: type annotations needed for `(usize, &mut query::peers::closest::ClosestPeersIter)`
--> …
```

kad: Avoid from/into `IteratorIndex`.

---

Cargo.toml
protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/kad/CHANGELOG.md
protocols/kad/Cargo.toml

- Update `libp2p-kad` CHANGELOG and increment version to 0.20.1.
- Update `libp2p` version to 0.20.1.
- Fix some linter warning in `libp2p-gossipsub` and increment version to 0.19.3 and update CHANGELOG.

Release v0.20.1

---

transports/dns/src/lib.rs

Now that `/dns/` is supported, it should be mentioned in the documentation as well.

Update libp2p-dns doc to include /dns/ support

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/kbucket.rs
protocols/kad/src/kbucket/bucket.rs
protocols/kad/src/kbucket/entry.rs

This implements option(s) `1.` and `2.` from https://github.com/libp2p/rust-libp2p/issues/1560 and possibly even allows implementing the role management in option `3.` from https://github.com/libp2p/rust-libp2p/issues/1352 externally.
It is now possible to disable automatic insertions of peers into the routing table via a new`KademliaBucketInserts` configuration option. The default is `OnConnected`, but it can be set to `Manual`, in which case `add_address` must be called explicitly. In order to communicate all situations in which a user of `Kademlia` may want to manually update the routing table, two new events are introduced:
* `KademliaEvent::RoutablePeer`: When a connection to a peer with a known listen address is established
which may be added to the routing table. This is also …

[libp2p-kad] More control & insight for k-buckets.

---

protocols/kad/src/handler.rs

There exists a configuration option for the connection keep-alive timeout, but we didn't use it everywhere.

Use self.config.idle_timeout in Kademlia handler

---

protocols/kad/src/lib.rs

In order to call `KademliaConfig::set_kbucket_inserts` one needs to be able to instantiate a `KademliaBucketInserts`.

protocols/kad/src/lib: Expose  KademliaBucketInserts

---

protocols/kad/src/behaviour.rs

This is a follow-up to (and thus branched off from) https://github.com/libp2p/rust-libp2p/pull/1628 - see the discussion there. It probably shouldn't be rushed in order to give users a chance to voice their concerns here early, in case there are any.

[libp2p-kad] Remove the `Discovered` event.

---

transports/wasm-ext/CHANGELOG.md
transports/wasm-ext/Cargo.toml
transports/wasm-ext/src/lib.rs
transports/wasm-ext/src/websockets.js

Reworks a bit the binding between `libp2p-wasm-ext` and the browser's `WebSocket` object.
I've used https://html.spec.whatwg.org/multipage/web-sockets.html to review the current code and make it more robust.
Notably:
- We now directly ask the browser to produce `ArrayBuffer` objects rather than obtaining `Blob` objects and converting them manually into `ArrayBuffer`.
- The threshold for sending more data is now 8kiB. In other words, as long as the out buffer (the one handled by the browser and whose length is accessed through `bufferedAmount`) is smaller than 8kiB, we report to the upper layers that we are ready to accept more data.
- `onclose` and `onerror` now unconditionally irreversibly shut down both the opening attempt and the incoming stream of bytes, without checking the state of …

Improve the code of the WebSocket browser binding

---

swarm/CHANGELOG.md
swarm/src/lib.rs
swarm/src/registry.rs

Dialing attempts of a local node to one of its own addresses for what appears to be a different peer ID are futile and bound to fail with an `InvalidPeerId` error. To avoid such futile dialing attempts, filter out the node's own addresses from the addresses
reported by the `NetworkBehaviour` for any peer.
There can be a few reasons why a `NetworkBehaviour` may think an address belongs to a different peer, e.g.:
1. In the context of e.g. `libp2p-kad`, the local node may have changed its network identity (e.g. key rotation)
and "discovers" its former identity in the DHT, with the same address(es).
2. Another peer may erroneously or intentionally, possibly even maliciously, report one of the local node's addresses as its own, making the node try to connect to itself.
Note: It is already the …

[libp2p-swarm] Ignore a node's own addresses on dialing.

---

transports/websocket/CHANGELOG.md
transports/websocket/Cargo.toml

The `async-tls` patch release `0.7.1` bumped its `rustls` dependency from `0.17` to `0.18`. `libp2p-websocket` has an explicit dependency on `rustls-0.17`, thus both versions get be pulled in resulting in problems like
```rust
error[E0277]: the trait bound `async_tls::connector::TlsConnector: std::convert::From<std::sync::Arc<rustls::client::ClientConfig>>` is not satisfied
--> transports/websocket/src/tls.rs:73:47
|
73 |             client: Arc::new(client_config()).into(),
|                                               ^^^^ the trait `std::convert::From<std::sync::Arc<rustls::client::ClientConfig>>` is not implemented for `async_tls::connector::TlsConnector`
|
= help: the following implementations were found:
<async_tls::connector::TlsConnector as …
```

Update rustls dependency.

---

misc/multiaddr/src/lib.rs

So you can use it in ordering based containers like BTreeSet/BTreeMap etc. without a newtype wrapper.

Add ord for multiaddr

---

protocols/request-response/CHANGELOG.md
protocols/request-response/Cargo.toml
protocols/request-response/src/handler/protocol.rs

Since forgetting to properly `close()` a substream may result in subtle problems that can be difficult to diagnose properly (see e.g. https://github.com/libp2p/rust-libp2p/pull/1606) it may be better to avoid this pitfall for implementations of `RequestResponseCodec` by always `close()`ing the substream in the `InboundUpgrade` and `OutboundUpgrade` explicitly.

[request-response] Close substream after writing request/response.

---

src/lib.rs

It looks like the code was changed at some point, but the explanation following it wasn't, leaving it inconsistent.
(I'm new to rust-libp2p, so maybe check that what I've altered it to actually does make sense, and is true.)

Align explanation with previously altered example code

---

core/CHANGELOG.md
core/Cargo.toml
core/src/identity/ed25519.rs

This PR upgrades `ed25519-dalek` to `1.0.0-pre.4` to address recent build errors (see [here](https://github.com/libp2p/rust-libp2p/pull/1658/checks?check_run_id=880828051)). Since a) the changes seem to be uncritical, i.e. primarily https://github.com/dalek-cryptography/ed25519-dalek/commit/6e0667d4298fdf9cb0d3c3cd65c39ba52f0ec702 as far as changes to the public API are concerned, and `libp2p-core` fully encapsulates its use of `ed25519-dalek` I propose a simple patch release here. For a full changelog of `ed25519-dalek` from `pre.3` to `pre.4` see [here](https://github.com/dalek-cryptography/ed25519-dalek/compare/1.0.0-pre.3...1.0.0-pre.4).

Upgrade ed25519-dalek to pre.4

---

CHANGELOG.md
Cargo.toml
src/bandwidth.rs
src/transport_ext.rs

At the moment, the bandwidth logging system in libp2p automatically tries to perform a 5-seconds average of the number of bytes that are transferred through its sockets.
This PR completely reworks that system and instead makes the bandwidth logging system only count and report the number of bytes. The user can later grab this number of bytes and perform their own 5-seconds-average if they need to.
This reason for this change is that users wouldn't be able to plug the `BandwidthLogging` struct on a QUIC transport. In order to make it possible for users to measure the bandwidth of QUIC connections, we would have to duplicate the averaging-algorithm of the `BandwidthLogging` inside of the QUIC transport itself.
I think it is an overall better approach to simply measure the number of bytes. …

Refactor the bandwidth logging to be less magic

---

misc/core-derive/CHANGELOG.md
misc/core-derive/Cargo.toml
misc/core-derive/src/lib.rs

If the users define a custom poll method also named in `poll` like
`#[behaviour(poll_method = "poll")`, it will cause issues as the wrong
`poll` method being called.
So use full qualified name to avoid ambiguity.
Fixes #1679.

core-derive: use full qualified name when polling NetworkBehaviour

---

protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/mcache.rs
protocols/gossipsub/src/protocol.rs

To assist looking into https://github.com/libp2p/rust-libp2p/issues/1671
Not sure if the nicer debug output is worth the extra dependency. For me it is, but YMMV. I can remove this if you see this differently.
Edit: I added truncation of the message bytes to ensure that the debug output for a gossipsub msg is not too big.

Debug instance for the gossipsub behaviour

---

core/src/transport/memory.rs

Signal the end of stream as `None` instead of producing a broken pipe error. This restores the behaviour prior to PR #1196. I could not find a motivation for this particular change in the PR and the previous implementation looks correct to me.

memory: Do not return broken pipe error on EOF.

---

CHANGELOG.md
Cargo.toml
protocols/noise/CHANGELOG.md
protocols/noise/Cargo.toml
protocols/noise/src/io/handshake.rs
protocols/noise/src/lib.rs
src/lib.rs

This is step 2 in resolving https://github.com/libp2p/rust-libp2p/issues/1631. With this PR, `rust-libp2p` is now compatible with the other `libp2p-noise` implementations. As a conservative option, if one does not wish to migrate to the spec-compliant handshakes with this release, a feature flag `send-legacy-handshake` is provided by `libp2p-noise`. The plan is to provide an analogous flag `recv-legacy-handshake` with a future release that removes support for receiving legacy handshakes _by default_. In this way the two feature flags allow delaying this transition in downstream projects, if necessary. Of course, eventually these flags should be removed.
As evidence and test that this release of `libp2p-noise` provides interoperability, the `build_development_transport` used by all …

[libp2p-noise] Disable sending of legacy handshake payloads (by default).

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs
protocols/kad/src/kbucket.rs

~~Instead of only returning non-empty kbuckets via `Kademlia::kbuckets`,
return empty ones as well.~~
~~Doing so enables consumers to (1) reason about each and every bucket and
(2) depend on a stable order of the buckets.~~
Add `KBucketRef::range` exposing the minimum inclusive and maximum
inclusive `Distance` for the bucket
More specifically within substrate I would like to expose the following metric:
```
HELP Number of nodes per protocol and Kademlia kbucket
substrate_sub_libp2p_kademlia_num_nodes_per_kbucket{protocol="sub", bucket="255"} 20
```

protocols/kad: Expose kbucket distance range

---

src/lib.rs

Good morning,
When updating to 0.23, I have a build error because I don't have the feature "noise" enabled.
The `feature = "noise"` tag was only added to the doc `cfg_attr` and not to `cfg`.
I don't know how it could be achieved, but it might be interesting to consider also implement (and automate) some kind of verification that the library compiles with different combination of features when running tests before releasing a new version.
> PS: thank you for this rust implementation of libp2p, it was really useful for my masterthesis ! ;)

add missing feature flag for "noise" to build_tcp_ws_noise_mplex_yamux and build_development_transport

---

swarm/src/toggle.rs

At present there is no way to get access to the inner `NetworkBehaviour`, which means you can't make any behaviours toggleable if you want to be able to call functions on them.

Add as_ref and as_mut functions to Toggle

---

protocols/ping/CHANGELOG.md
protocols/ping/src/handler.rs
protocols/ping/src/lib.rs
protocols/ping/src/protocol.rs
protocols/ping/tests/ping.rs

This addresses https://github.com/libp2p/rust-libp2p/issues/1601. Pings are now sent over a single substream, as it is done in other libp2p implementations. A few points worth noting:
* Since each peer sends its pings over a single, dedicated substream, every peer that participates in the protocol has effectively two open substreams. This seems to be in-line with other implementations.
* I tested interoperability with the `ipfs ping` command against `rust-libp2p` nodes using the ping example.
* To keep backward-compatibility and not unnecessarily close connections, with the default configuration of `max_failures` set to `1`, the first outbound ping failure is "free" and "silent". A node using the old protocol will close inbound substreams prematurely after responding to a ping, causing a …

[ping] Refactor the ping protocol for conformity.

---

protocols/request-response/CHANGELOG.md
protocols/request-response/Cargo.toml
protocols/request-response/src/handler.rs
protocols/request-response/src/handler/protocol.rs
protocols/request-response/src/lib.rs
protocols/request-response/src/throttled.rs
protocols/request-response/tests/ping.rs
swarm/src/behaviour.rs

Wraps the existing `RequestResponse` behaviour and applies strict limits to the number of inbound and outbound requests per peer.
The wrapper is opt-in and if not used, the protocol behaviour of `RequestResponse` does not change. This PR also does not introduce an extra protocol, hence the limits applied need to be known a priori for all nodes which is not always possible or desirable. As mentioned in #1687 I think that we should eventually augment the protocol with metadata which allows a more dynamic exchange of requests and responses.
This PR also replaces the two oneshot channels with a single one from the [scambio](https://crates.io/crates/scambio) crate which saves one allocation per request/response. If not desirable because the crate has seen less testing the first commit could be …

Add `Throttled` to libp2p-request-response.

---

swarm/CHANGELOG.md
swarm/src/protocols_handler/one_shot.rs

The `OneShotHandler` `keep_alive` property is altered on incoming and
outgoing reqeusts. By default it is initialized in `KeepAlive::Yes`. In
case there are no incoming or outgoing requests happening, this state is
never changed and thus the handler keeps the underlying connection alive
indefinitely.
With this commit the handler is initialized with `KeepAlive::Until`. As
before the `keep_alive` timer is updated on incoming requests and set to
`KeepAlive::Yes` on outgoing requests.
---
Related to https://github.com/paritytech/polkadot/issues/1544.

swarm/one_shot: Initialize handler with KeepAlive::Until

---

protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs

Add some public api to allow implementing the ipfs pubsub api
Basically
-pubsub ls https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-ls
lists topics that we are currently listening to
-pubsub peers https://docs.ipfs.io/reference/http/api/#api-v0-pubsub-peers
lists peers we are peered to for a single topic, or overall

Public gossipsub api

---

protocols/request-response/tests/ping.rs

The codec impl did not check that it actually read any bytes in `read_request` and `read_response`. The used `read_one` function does not error on EOF either, so instead of signalling connection loss the codec could produce empty `Ping` or `Pong` messages.

Fix ping test in request-response.

---

protocols/request-response/CHANGELOG.md
protocols/request-response/src/handler.rs

Upon reviewing https://github.com/libp2p/rust-libp2p/pull/1698 I double-checked the analogous handling in `request-response` which seemed to lack a condition, resulting in an indefinite keep-alive. More generally and judging from prior experience from other handlers where the keep-alive handling has been tricky to get right, it seems this keep-alive handling may better be done in a more general manner in `libp2p-core`, for all connection handlers. Not sure yet how realistic that is though.

Fix connection keep-alive for request-response.

---

core/src/transport/upgrade.rs
muxers/yamux/src/lib.rs

Allow overriding the yamux mode which is currently selected depending on whether an inbound or outbound upgrade happens. Also add a method `Builder::multiplex_ext` which accepts a function which is applied to all available connection info and returns the actual upgrade.
For context see #1690.

Custom yamux mode

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs
protocols/kad/src/record.rs
protocols/kad/src/record/store/memory.rs

So far, provider records are stored without their addresses and the addresses of providers are obtained from the routing table on demand. I don't remember whether this was ever done on purpose or just an oversight as part of a larger amount of work. In any case, this approach has two shortcomings:
1. We can only return provider records whose provider peers happen to currently be in the local routing table.
2. The local node never returns itself as a provider for a key, even if it is indeed a provider.
These issues are addressed here by storing the addresses together with the provider records, falling back to
addresses from the routing table only for backward-compatibility with existing implementations of `RecordStore` that use persistent storage and may thus have records that persist …

[kad] Store addresses of provider records.

---

protocols/request-response/CHANGELOG.md
protocols/request-response/src/lib.rs
protocols/request-response/tests/ping.rs

Can be enabled again after #1706 is resolved.

Disable `RequestResponse::throttled`.

---

Cargo.toml
protocols/mdns/CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/mdns/src/behaviour.rs
protocols/mdns/src/lib.rs
protocols/mdns/src/service.rs
src/lib.rs

Allow libp2p-mdns to use either async-std or tokio to drive required UDP
socket.
As far as I can tell the two features (`mdns-async-std`, `mdns-tokio`)
and the corresponding tests are additive.
Closes https://github.com/libp2p/rust-libp2p/issues/1318

protocols/mdns: Make libp2p-mdns socket agnostic

---

swarm/src/protocols_handler.rs
swarm/src/protocols_handler/dummy.rs
swarm/src/protocols_handler/map_in.rs
swarm/src/protocols_handler/map_out.rs
swarm/src/protocols_handler/multi.rs
swarm/src/protocols_handler/select.rs
swarm/src/toggle.rs

This PR forwards calls to some `ProtocolsHandler` methods that were previously not implemented in wrappers such as `MapInEvent`.
~~It is [unclear](https://github.com/twittner/rust-libp2p/blob/a8b990c5c11dee82477e243f77f0d9211b444228/swarm/src/protocols_handler/multi.rs#L160) though how this can be implemented in some handlers such as `MultiHandler` as the information at hand does not enable it to decide which handler to forward the call to.~~
NB that there is no guarantee at all that a `listen_protocol` call will eventually be followed by a call to either `inject_fully_negotiated_inbound` or `inject_listener_upgrade_err`.
For context see #1707.

Implement ProtocolsHandler methods in wrappers.

---

CHANGELOG.md
Cargo.toml
core/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/deflate/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/noise/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/plaintext/CHANGELOG.md
protocols/request-response/CHANGELOG.md
protocols/secio/CHANGELOG.md
swarm/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

Let me know in case you want any additional notes in the root level `CHANGELOG.md` or want any other pull requests to be included in the release.

*: Prepare v0.24.0 release

---

protocols/kad/CHANGELOG.md
protocols/kad/Cargo.toml
protocols/kad/src/kbucket.rs

Compiling libp2p-kad for `--target wasm32-unknown-unknown` fails with
the cryptic error message `cannot infer type for type usize`.
Explicitly converting to `usize` solves the issue.
```
961error[E0283]: type annotations needed
962   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.22.0/src/kbucket.rs:123:19
963    |
964123 |         if self.0 == u8::MAX.into() {
965    |                   ^^ cannot infer type for type `usize`
966    |
967    = note: cannot satisfy `usize: std::cmp::PartialEq<_>`
```
I am not familiar enough with `wasm32-unknown-unknown` to know the exact cause. In case you deem it to be worth the effort, I am happy to dig deeper into this.
Likely related to https://github.com/rust-lang/rust/issues/71584 and …

protocols/kad/src/kbuckets: Explicitly convert u8 to usize

---

core/src/network.rs

When doing address translation we want to keep the discovered external address but keep the local port. If we are listening on multiple addresses (with the same port) we end up with a bunch of duplicates.

core: remove duplicates when performing address translation

---

docs/release.md

In order to stay consistent across releases and also to enable possibly anyone with the correct access rights to release libp2p, this pull request adds a release documentation to the repository.
I have never cut a release of rust-libp2p. This documentation is based on past discussions and the git commit history. To reviewers: Please ensure this is in line with how you handled releasing for the last couple of versions.

docs/release.md: Add release documentation

---

CHANGELOG.md
Cargo.toml
protocols/noise/CHANGELOG.md
protocols/noise/Cargo.toml
protocols/noise/src/io/handshake.rs
protocols/noise/src/lib.rs

This is the final step for the migration, except for removing the legacy configuration options eventually in the distant future. There is no rush with this PR - indeed some time should pass since the latest release (`0.23`) before this is considered for merge and release.

[noise] Remove (by default) support for receiving legacy handshakes.

---

core/src/lib.rs
core/src/network.rs
swarm/src/lib.rs

Previously, only dedicated implementations of `Executor` could be passed to `set_executor` of `NetworkConfig`. To pass a closure, one had to use `executor_fn`. Unfortunately, that function isn't exposed on the `SwarmBuilder` and hence cannot be used from the outside.
With this patch, any closure that takes a future can be passed as an executor.
This allows us to:
- simplify the `build` function of `NetworkConfig` by removing the `SpawnImpl`
- use functions like `tokio::spawn` or `async_std::task::spawn` as the executor on the `SwarmBuilder` because they share the same interface
I believe this is a breaking change because we have to remove certain `impl` blocks from `libp2p-core`.

Allow any closure to be passed as an executor

---

protocols/kad/CHANGELOG.md
protocols/kad/src/protocol.rs

For better interoperability by default, picking up the suggestion of @mxinden  in https://github.com/libp2p/rust-libp2p/issues/1622.

[kad] Increase default payload limits.

---

core/CHANGELOG.md
core/src/connection/listeners.rs
core/src/transport/memory.rs

Previously a `Listener` would return its own address as the
`remote_addr` in the `ListenerEvent::Upgrade` event.
With this commit a `Listener` returns the dialer address as the
`remote_addr` in the `ListenerEvent::Upgrade` event. To do so a
`DialFuture` registers a port with the global `HUB` at construction
which is later on unregistered in the `Drop` implementation of the
dialer's `Chan`. The sending side of the `mpsc::channel` registered in
the `HUB` is dropped at `DialFuture` construction, thus one can not dial
the dialer port. This mimics the TCP transport behaviour preventing both
dialing and listening on the same TCP port.
Closes https://github.com/libp2p/rust-libp2p/issues/1721.

core/transport/memory: Return dialer address in Upgrade event

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/tests/smoke.rs

Small improvement for `protocols/gossipsub/tests/smoke.rs` providing more information on failure, hopefully helping us to track down the CI failures.
I am able to reproduce https://github.com/libp2p/rust-libp2p/issues/1725 occasionally but haven't found the cause (yet).

protocols/gossipsub/tests/smoke: Improve wait_for reporting

---

core/CHANGELOG.md
core/src/network.rs
core/src/network/event.rs
core/tests/network_dial_error.rs
swarm/src/lib.rs

This PR is a small simplification to the handling of pending incoming connections. Instead of handing out a mutable borrow to the connection pool in the `IncomingConnectionEvent`, so one can call `IncomingConnectionEvent::accept()`, just provide `Network::accept()`. That this is a simplification can also easily be seen from the LOC diff.

[core] Simplify accepting incoming connections.

---

CHANGELOG.md
core/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/deflate/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/noise/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/plaintext/CHANGELOG.md
protocols/request-response/CHANGELOG.md
protocols/secio/CHANGELOG.md
swarm/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

Prepare release of `libp2p-v0.25` and all unreleased sub-crates. Since changelogs and versions are already set accordingly, this PR is just a formality for visibility of the release(s).

Prepare release of `libp2p-v0.25`.

---

CHANGELOG.md
muxers/yamux/CHANGELOG.md

Part 2 of the `libp2p-yamux` upgrade process.

Prepare release of `libp2p-v0.26`

---

CHANGELOG.md
muxers/yamux/CHANGELOG.md

This is step 3 of the `libp2p-yamux` upgrade process.

Prepare release of `libp2p-0.27.0`.

---

CHANGELOG.md
muxers/yamux/CHANGELOG.md

This release marks the end of the `libp2p-yamux` upgrade process.

Prepare `libp2p-v0.28.0`.

---

CHANGELOG.md
Cargo.toml
core/CHANGELOG.md
core/Cargo.toml

With b601ed4 libp2p-core requires the `Ord` bound on `Multiaddr`. This
bound is only implemented with parity-multiaddr `0.9.2`. Make sure
libp2p-core requires at least parity-multiaddr `0.9.2`.
I am not sure it is worth the patch release of both libp2p-core and libp2p. Let me know. Happy to do the release.

 core/Cargo.toml: Require parity-multiaddr 0.9.2 for Ord bound

---

.github/dependabot.yml

Closes https://github.com/libp2p/rust-libp2p/issues/1743.
According to the [post-acquisition-by-github docs](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates) this should work without any further configuration.

.github: Add dependabot.yml

---

Cargo.toml
protocols/plaintext/CHANGELOG.md
protocols/plaintext/Cargo.toml
protocols/plaintext/src/lib.rs

Don't log errors happening after plaintext handshake as errors happening
during plaintext handshake.

protocols/plaintext: Remove wrong debug log

---

CHANGELOG.md
Cargo.toml
protocols/plaintext/CHANGELOG.md
protocols/plaintext/Cargo.toml
protocols/plaintext/src/handshake.rs
protocols/plaintext/src/lib.rs

Only prefix handshake messages with the message length in bytes as an
unsigned varint. Return a plain socket once handshaking succeeded.
Tested compatibility with https://github.com/mxinden/libp2p-perf.
Fixes https://github.com/libp2p/rust-libp2p/issues/1760

protocols/plaintext: Do not UVI encode goodput 

---

swarm/src/protocols_handler.rs

`Send` and `'static` are already implied by `InboundUpgradeSend`.
Hope I am not missing something.

swarm/src/protocols_handler.rs: Remove redundant trait bound

---

Cargo.toml
muxers/mplex/CHANGELOG.md
muxers/mplex/Cargo.toml
muxers/mplex/src/codec.rs
muxers/mplex/src/config.rs
muxers/mplex/src/io.rs
muxers/mplex/src/lib.rs

This is a rather substantial refactoring of `libp2p-mplex`, though the control-flow skeleton remains the same, as dictated by the `StreamMuxer` API. In the context of looking into https://github.com/libp2p/rust-libp2p/issues/1758, besides a bug in `libp2p-ping` that only occurs with mplex and for which I will open a separate PR, the following two problems in `libp2p-mplex` became apparent and are intended to be addressed here:
* Avoid stalls caused by a read operation on one substream reading (and buffering) frames for another substream without
notifying the corresponding task. While testing https://github.com/libp2p/rust-libp2p/issues/1758, even when the `ping_pong` tests ran through, there were occasional stalls in between. It turned out that, when a read operation for one substream …

[mplex] Refactoring with Patches

---

protocols/ping/CHANGELOG.md
protocols/ping/Cargo.toml
protocols/ping/src/protocol.rs
protocols/ping/tests/ping.rs

After sending the ping and before awaiting the pong, the stream must be flushed to guarantee the data is sent before awaiting the reply. This is not necessary with `libp2p-yamux` where every sent frame is flushed, but with mplex it may remain sitting in a buffer otherwise. This problem was revealed by https://github.com/libp2p/rust-libp2p/issues/1758 together with some other mplex issues addressed in https://github.com/libp2p/rust-libp2p/pull/1769. This PR is on top of #1769 since the tests randomise usage of mplex and yamux and only pass consistently with these patches. For a proper diff (it is small), see [here](https://github.com/romanb/rust-libp2p/compare/patch-mplex...romanb:ping-mplex).
Together with #1769, closes #1758.

[ping] Add missing flush after write.

---

misc/multistream-select/CHANGELOG.md
misc/multistream-select/src/dialer_select.rs
misc/multistream-select/src/length_delimited.rs
misc/multistream-select/src/listener_select.rs
misc/multistream-select/src/negotiated.rs
misc/multistream-select/src/protocol.rs

There appears to still be an edge-case in `multistream-select` whereby the `remaining` data to send w.r.t. protocol  is successfully written before a `poll_read` on a `Negotiated` stream, but where the subsequent `poll_flush()` is pending. Now `remaining` is empty and the next `poll_read()` will go straight to reading from the underlying I/O stream, despite the flush not having happened
yet, which can lead to a form of deadlock during protocol negotiation. This seems to be the cause for the sporadic upgrade timeouts in https://github.com/libp2p/rust-libp2p/issues/1629.
It was a happy coincidence that I looked into https://github.com/libp2p/rust-libp2p/issues/1629 again just before `async-io-1.1.5` was released, because up to `1.1.4`, write operations would occasionally yield without …

[multistream-select] Require remaining negotiation data to be flushed.

---

protocols/mdns/src/service.rs

Also add warn if parsing of a packet fails, so problems with for example packet
sizes can more easily be detected.
Reasoning:
The previous 2048 bytes is already larger than the recommend size by
[rfc6762](https://tools.ietf.org/html/rfc6762#page-46), which recommends
a packet size that fits within the interface MTU.
Nevertheless the rfc also states, that if more data needs to be
transmitted one should rely on IP fragments, which would only pose
problems when interfacing with devices not understanding IP fragments.
The standard also imposes a strict upper limit of 9000 bytes.
Therefore raising `recv_buffer` to 4096 seems sensible, given that we
already exceed the recommend size and given that we are not restricting
the size when sending in any way. Meaning the implementation already
sends …

Fix #1778: Double mdns recv_buffer to 4096 bytes

---

core/src/transport.rs
core/src/transport/boxed.rs
core/tests/network_dial_error.rs
misc/multistream-select/CHANGELOG.md
misc/multistream-select/Cargo.toml
misc/multistream-select/src/negotiated.rs
misc/multistream-select/tests/transport.rs
protocols/gossipsub/tests/smoke.rs
protocols/kad/src/behaviour/test.rs
protocols/ping/tests/ping.rs
protocols/request-response/tests/ping.rs
src/lib.rs
swarm/src/lib.rs

Fixes a panic when using the `V1Lazy` negotiation protocol, a regression introduced in [1484](https://github.com/libp2p/rust-libp2p/pull/1484/files#diff-6ce2135f99a1031d8c2df76296d2be52L122-R136)(Upgrade to stable futures). Thereby adds integration tests for a transport upgrade with both `V1` and `V1Lazy` to the `multistream-select` crate to prevent future regressions.
As a small refactoring on the side, I changed `Transport::boxed` to always also box the `StreamMuxer` and the transport errors, as this is how boxed transport are pretty much always used. I don't think it is necessary to support boxing of a transport at various levels of granularity. Now, when you want a boxed transport you just need to tack on `.boxed()` at the end of the transport builder and get a boxed transport with a …

[multistream-select] Fix panic with `V1Lazy` (regression) and more convenient transport boxing.

---

CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/mdns/src/service.rs
transports/tcp/CHANGELOG.md
transports/tcp/Cargo.toml
transports/tcp/src/lib.rs

Signed-off-by: koushiro <koushiro.cqx@gmail.com>
The crate [get_if_addrs](https://github.com/maidsafe-archive/get_if_addrs) is no longer maintained by its authors.
I think the [if-addrs](https://github.com/messense/if-addrs) (forked from [get_if_addrs](https://github.com/maidsafe-archive/get_if_addrs)) is a good alternative.
If we find a better library written in pure rust later, we can use it instead of `if-addrs` (see #1489)

Replace `get_if_addrs` with `if-addrs`

---

CHANGELOG.md
Cargo.toml
swarm/CHANGELOG.md
swarm/Cargo.toml
swarm/src/protocols_handler/node_handler.rs

> Futures managed by FuturesUnordered will only be polled when they
generate wake-up notifications. This reduces the required amount of work
needed to poll large numbers of futures.
https://docs.rs/futures/0.3.5/futures/stream/struct.FuturesUnordered.html
Instead of iterating each inbound and outbound upgrade looking for one
to make progress, use a `FuturesUnordered` for both pending inbound and
pending outbound upgrades. As a result only those upgrades are polled
that are ready to progress.

swarm/src/protocols_handler: Use FuturesUnordered in NodeHandlerWrapper

---

Cargo.toml

Follow up to https://github.com/libp2p/rust-libp2p/pull/1788.

Cargo.toml: Bump libp2p-tcp patch version

---

swarm/CHANGELOG.md
swarm/src/protocols_handler/multi.rs

At the moment the `ProtocolsHandler::listen_protocol()` implementation of the `MultiHandler` discards configured timeouts and upgrade protocol versions on the inner handlers. The former results in the `MultiHandler` always having a default `10` second timeout on inbound substream upgrades, regardless of the configuration on the inner handlers. The latter results in the `MultiHandler` always using the `upgrade::V1` negotiation protocol for inbound substream upgrades, which may not match what the inner handlers use for their corresponding outbound substreams - of course it should still be the same version used in all handlers, but it may not be `V1`. So this PR does the following:
1. The `MultiHandler` uses the maximum of all configured inbound timeouts on the inner handlers. Typically …

[swarm] MultiHandler: Respect inbound timeouts and upgrade versions.

---

muxers/mplex/Cargo.toml
muxers/mplex/src/codec.rs
muxers/mplex/src/config.rs
muxers/mplex/src/io.rs

This PR picks up a discussion from https://github.com/libp2p/rust-libp2p/pull/1769#discussion_r494942944 about splitting the shared receive buffer per substream. This split allows more efficient reading from the buffer for a particular substream, to efficiently drop all still buffered frames for a particular stream when it is dropped, and to reset only the offending substream if it reaches its buffer limit with `MaxBufferBehaviour::ResetStream`. Previously this was implemented as `MaxBufferBehaviour::CloseAll` and resulted in the entire connection closing. The buffer split should generally be advantageous whenever not all substreams are read at the same pace and some temporarily fall behind in consuming their data.

[mplex] Split the receive buffer per substream.

---

muxers/mplex/Cargo.toml
muxers/mplex/src/codec.rs
muxers/mplex/src/io.rs

This PR builds on https://github.com/libp2p/rust-libp2p/pull/1784 (proper diff [here](https://github.com/romanb/rust-libp2p/compare/mplex-split-buffer...romanb:mplex-polish?expand=1)), making a few further small improvements:
* Replace use of `fnv` with `nohash-hasher` to avoid unnecessary hashing of substream IDs.
* Improve logging through randomly generated connection IDs in the same way as in Yamux.
* More granular execution of pending flushes for newly opened outbound streams before reading. Otherwise there is a theoretical possibility of both ends being unnecessarily blocked on reading due to attempting to flush and both sides cannot flush for some reason. It is only necessary to flush before a read if the particular substream for which the read happens has just been opened, but not …

[mplex] Small enhancements.

---

CHANGELOG.md
core/CHANGELOG.md
misc/multiaddr/CHANGELOG.md
misc/multistream-select/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/deflate/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/noise/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/plaintext/CHANGELOG.md
protocols/pnet/CHANGELOG.md
protocols/request-response/CHANGELOG.md
protocols/secio/CHANGELOG.md
swarm/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

Release of `libp2p-0.29` and all unreleased sub-crates.

Prepare release v0.29.

---

misc/multistream-select/CHANGELOG.md
misc/multistream-select/Cargo.toml
misc/multistream-select/src/dialer_select.rs

As suggested by @mxinden in https://github.com/libp2p/rust-libp2p/issues/1795#issuecomment-710051380, in order to later change the "ls" responses for spec-compliance, this PR temporarily disables that negotiation strategy for the dialer. I thereby propose to immediately release this as a patch release in order to speed up the process. The next, follow-up release will obviously be not backward-compatible and require the latest patch version released here to already be deployed. I would like to pick up this new patch version already in https://github.com/paritytech/substrate/pull/7341.

[multistream-select] Temporarily disable "parallel" negotiation.

---

CHANGELOG.md
Cargo.toml
core/CHANGELOG.md
core/Cargo.toml

See https://github.com/paritytech/substrate/pull/7341#discussion_r508516095 for motivation.
I guess dependabot didn't spot this given the `pre.4` suffix.

core/Cargo.toml: Update to ed25519-dalek v1.0.1

---

CHANGELOG.md
core/CHANGELOG.md
core/Cargo.toml

-  *: Update date in changelogs 
-  core/Cargo.toml: Bump multistream-select to v0.8.4

Prepare v0.29.1

---

muxers/mplex/CHANGELOG.md
muxers/mplex/Cargo.toml
muxers/mplex/src/io.rs

Version  `0.23.0` started [treating duplicate `Close` frames for a substream as a protocol violation](https://github.com/libp2p/rust-libp2p/pull/1769#discussion_r493604381). As there seem to be libp2p implementations that occasionally send such frames (cf. https://github.com/sigp/lighthouse/issues/1832#issuecomment-717859849) and it is a harmless redundancy, I prefer and propose here again to be lenient about such redundant frames rather than requiring other implementations to change, especially since this may be considered a regression compared to previous versions of `libp2p-mplex`. This PR prepares release `libp2p-mplex-0.23.1`.

[mplex] Revert to being lenient with duplicate Close frames.

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/handler.rs

This is a proposal for closing https://github.com/libp2p/rust-libp2p/issues/1611. In order to avoid adding peers to the local routing table which use a different protocol name and thus actually a different overlay network, only update the local routing table for newly established connections once the associated connection handler reports that the protocol has been confirmed. The configured protocol is confirmed on a connection once the first inbound or outbound substream is successfully negotiated.

[kad] Update local routing table on new connections after protocol confirmation.

---

examples/ipfs-private.rs
muxers/mplex/CHANGELOG.md
muxers/mplex/src/config.rs
muxers/yamux/CHANGELOG.md
muxers/yamux/src/lib.rs
protocols/gossipsub/tests/smoke.rs
protocols/kad/src/behaviour/test.rs
protocols/ping/tests/ping.rs
protocols/request-response/tests/ping.rs
src/lib.rs

This is a proposal for streamlining the configuration APIs of `libp2p-mplex` and `libp2p-yamux`, i.e. to close https://github.com/libp2p/rust-libp2p/issues/1531. I made the following choices:
* For all configuration options that exist for both multiplexers and have the same semantics, use the same names for the
configuration.
* Rename `yamux::Config` to `YamuxConfig` for consistency with the majority of other protocols, e.g. `MplexConfig`, `PingConfig`,  `KademliaConfig`, etc.
* Completely hide `yamux` APIs within `libp2p-yamux`. This is a trade-off. It allows to fully control the libp2p API and streamline it with other muxer APIs, consciously choosing e.g. which configuration options to make configurable in libp2p and which to fix to certain values (e.g. we currently always fix …

[mplex, yamux] Streamline configuration API.

---

muxers/mplex/CHANGELOG.md
muxers/mplex/src/config.rs
muxers/mplex/src/io.rs

This PR is a small follow-up to https://github.com/libp2p/rust-libp2p/issues/1814#issuecomment-722355848. It contains the following changes:
* The default `MplexConfig` uses `MaxBufferBehaviour::Block` as I think it is the better default.
* Whenever we may have entirely filled a substream buffer in the context of either waiting for the next inbound stream (`poll_next_stream`) or reading from a particular substream (`poll_read_stream`), we yield the current task, allowing it to be polled again to have a chance to read from the buffers before the `MaxBufferBehaviour` takes effect.
* Documentation tweaks.

[mplex] Tweak default config and yield before exceeding buffer limits.

---

CHANGELOG.md
core/CHANGELOG.md
misc/multistream-select/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/deflate/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/noise/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/plaintext/CHANGELOG.md
protocols/request-response/CHANGELOG.md
protocols/secio/CHANGELOG.md
swarm/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

I would like to cut a new release of libp2p - v0.30.0.
I suggest including https://github.com/libp2p/rust-libp2p/pull/1825 and https://github.com/libp2p/rust-libp2p/pull/1823. Anything else you would like to be included?
I would suggest not yet rolling out the second step of the `ls` upgrade (https://github.com/libp2p/rust-libp2p/pull/1811), but instead leaving more time for v0.29.1 to be rolled out.

*: Update changelogs to release v0.30.0

---

CHANGELOG.md
Cargo.toml
protocols/plaintext/CHANGELOG.md
protocols/plaintext/Cargo.toml
protocols/plaintext/src/handshake.rs
protocols/plaintext/src/lib.rs

When the plaintext protocol handshake finishes and the `Framed` I/O used during the handshake is discarded in favor of the underlying I/O stream, the remaining read buffer of `Framed` must be retained, as it may have buffered data beyond the end of the handshake. This problem manifests itself in potential stalls / timeouts during protocol negotiation, because a peer does not necessarily wait for confirmation of a protocol before it sends the proposal for the next protocol upgrade. E.g. `/multistream/1.0.0 \n /mplex/6.7.0` for the mplex upgrade may already be received and buffered by the `Framed` of the plaintext handshake by a peer before the handshake is complete. That peer will read the final handshake frame but then discard the remaining read buffer of `Framed`, leaving the remote …

[plaintext] Retain remaining read buffer after handshake.

---

misc/multiaddr/src/lib.rs

Buffer allocated in `visit_seq` does not have an upper limit. Limit buffer capacity to 4096.

Limit buffer capacity in multiaddr visit_seq

---

misc/multiaddr/Cargo.toml
misc/multiaddr/src/from_url.rs
misc/multiaddr/src/lib.rs

multiaddr: feature gate url dependency

---

misc/core-derive/src/lib.rs
protocols/gossipsub/src/behaviour.rs
protocols/identify/src/identify.rs
protocols/kad/src/behaviour.rs
protocols/request-response/src/throttled.rs
swarm/CHANGELOG.md
swarm/src/behaviour.rs
swarm/src/lib.rs
swarm/src/registry.rs

It is currently not possible to add external addresses to a `Swarm` that are retained forever. All added or observed external addresses are added to an ordered list with a finite score (`1`) for every new addition and thus subject to being purged eventually. It is desirable to be able to add addresses to this collection that are retained until explicitly removed and always sorted at the beginning, not influencing the existing semantics for the additional finite scores and expiring addresses. It also seems desirable to let the score of a particular address report / observation be chosen freely, instead of being fixed to `1`. The motivation relates to https://github.com/paritytech/substrate/issues/7518.
To that end, this PR extends the address score arithmetic used for external addresses …

[swarm] Configurable and "infinite" scores for external addresses.

---

core/CHANGELOG.md
core/src/connection.rs
core/src/connection/pool.rs
core/src/network.rs
core/src/network/peer.rs
core/tests/connection_limits.rs
core/tests/network_dial_error.rs
core/tests/util.rs
swarm/CHANGELOG.md
swarm/src/lib.rs

The initial motivation for the work in this PR is https://github.com/libp2p/rust-libp2p/issues/1839. However, the PR goes a bit further than to just add a single counter to have a more streamlined API. Thus, in order to better track different connection counts and permit configurable limits for these counts and make these available for inspection in an efficient manner (i.e. without linear counting operations), I introduced dedicated connection counters via a `ConnectionCounters` structure maintained by the internal connection pool but exposed on the API via the `NetworkInfo`. All connection states that are counted in this way can also have effective configurable limits.
All limits are now configured through a `ConnectionLimits` structure. The new configurable limits are
* …

[core/swarm] Refactor and extend configurable connection limits.

---

.github/workflows/ci.yml
core/src/connection.rs
core/src/connection/listeners.rs
core/src/connection/manager.rs
core/src/connection/pool.rs
core/src/network.rs
core/src/network/peer.rs
core/src/peer_id.rs
core/src/transport.rs
core/src/transport/memory.rs
core/src/transport/upgrade.rs
misc/multiaddr/src/errors.rs
misc/multiaddr/src/lib.rs
misc/multiaddr/src/protocol.rs
misc/multistream-select/src/lib.rs
misc/multistream-select/src/negotiated.rs
misc/multistream-select/src/protocol.rs
muxers/mplex/src/codec.rs
protocols/kad/CHANGELOG.md
protocols/kad/src/record.rs
protocols/mdns/src/service.rs
protocols/pnet/src/lib.rs

This pull request fixes _deny_ level and some _warning_ level [clippy](https://github.com/rust-lang/rust-clippy) lints and enables clippy to run on each pull request and each commit on `master`.
In my eyes clippy is a helpful tool. Given that (for now) it is set to fail on _deny_ level lints only, I doubt it will be too annoying.
Let me know what you think.

*: Apply clippy suggestions and enable clippy on CI

---

misc/multistream-select/CHANGELOG.md
misc/multistream-select/src/dialer_select.rs
misc/multistream-select/src/lib.rs
misc/multistream-select/src/listener_select.rs
misc/multistream-select/src/negotiated.rs
misc/multistream-select/src/protocol.rs
protocols/kad/src/behaviour/test.rs

Closes https://github.com/libp2p/rust-libp2p/issues/1853. The remaining optimisation for `V1Lazy` for a listener in the negotiation, whereby the listener delays flushing of the multistream version header, is hereby removed. The only remaining effect of `V1Lazy` as compared to `V1` is on the side of the dialer, which delays flushing of its singular protocol proposal (i.e. if it has no alternatives) in order to send it together with the first application data, e.g. a request, or an attempt is made to read from the negotiated stream, which similarly triggers a flush of the pending protocol proposal, as before. This permits `V1Lazy` dialers to be interoperable with `V1` listeners. The remaining theoretical pitfall whereby  application data gets misinterpreted as another protocol proposal by a …

[multistream] Make the lazy variant more interoperable.

---

swarm/CHANGELOG.md
swarm/src/lib.rs
swarm/src/protocols_handler/node_handler.rs

It is desirable to configure the substream upgrade protocol (i.e. multistream-select protocol) to use for substreams in general. Since introducing configuration options for the substream upgrade protocol to all libp2p protocol crates seems to be noisy and likely unnecessary, this PR proposes a configuration option for the `Swarm` that will apply to all (outbound) substreams. In this way, one can configure the upgrade protocols in a single place, once for the transport and once for the substreams.

[swarm] Permit configuration override for the substream upgrade protocol to use.

---

swarm/CHANGELOG.md
swarm/Cargo.toml
swarm/src/lib.rs

Commit 335e55e6 removed the `ConnectionInfo` trait in favor of `PeerId`s. Commit
1bd013c8 removed `ExpandedSwarm::connection_info` as it would only return the
`PeerId` that the caller is already aware of.
One could use `ExpandedSwarm::connection_info` not only to retrieve the
`ConnectionInfo` for a given peer, but also to check whether the underlying
`Network` has a connection to the peer.
This commit exposes the `is_connected` method on `Network` via `ExpandedSwarm`
to check whether the `Network` has an established connection to a given peer.
---
One could as well expose other read-only methods on `Network` like `is_dialing`
and `is_disconnected`. For now this pull request only restores the status-quo.
Let me know what you prefer.

swarm: Add ExpandedSwarm::is_connected

---

.github/workflows/ci.yml

The `broken_intra_doc_links` lint stabilized with Rust `v1.48`, thus the
special usage of `nightly` is not needed anymore in the pipeline step.
Fixes https://github.com/libp2p/rust-libp2p/issues/1864.

.github/workflow: Don't require nightly for doc link check

---

misc/multistream-select/src/listener_select.rs
misc/multistream-select/src/tests.rs

Context: https://github.com/paritytech/substrate/pull/7478#issuecomment-736803765
When `V1Lazy` is used and the listener does not support the optimistic (and singular) proposal of the dialer, it currently happens that dialer and listener get a different outcome of the negotiation. The dialer eventually detects the failed negotiation as soon as it tries to read from the stream, but the listener either encounters an invalid message or unexpected premature EOF, depending on the payload that the dialer sent prematurely after its protocol proposal. In these cases the listener must be lenient and fail the negotiation "normally", i.e. not with a protocol violation or an I/O error. The tests have been expanded to make sure both versions behave uniformly in this manner w.r.t. failed negotiations. …

[multistream-select] Listener conformity for failed negotiations.

---

CHANGELOG.md
Cargo.toml
examples/chat-tokio.rs
examples/chat.rs
examples/distributed-key-value-store.rs
examples/mdns-passive-discovery.rs
protocols/mdns/CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/mdns/src/behaviour.rs
protocols/mdns/src/dns.rs
protocols/mdns/src/lib.rs
protocols/mdns/src/service.rs
src/lib.rs

Currently the mdns behaviour will panic if no adapter is available. To test on linux use the following commands:
```sh
sudo ifconfig wlan0 down
cargo run --example mdns-passive-discovery
sudo ifconfig wlan0 up
```
~Depends on https://github.com/paritytech/ip-watch/pull/1~
cc @Demi-Marie @rklaehn

Adds support for handling interface changes to mdns behaviour.

---

.github/workflows/ci.yml
core/Cargo.toml
core/benches/peer_id.rs

I hope these somewhat simple benchmarks can back up discussions in https://github.com/libp2p/rust-libp2p/pull/1874 and https://github.com/libp2p/rust-libp2p/pull/1865 with data.
```
$ cd core/
$ cargo bench
[...]
from_bytes              time:   [187.15 ns 187.88 ns 188.79 ns]                                                       
change: [-11.163% -10.359% -8.9828%] (p = 0.00 < 0.05)                                        
Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
1 (1.00%) low mild
5 (5.00%) high mild
3 (3.00%) high severe
clone                   time:   [14.811 ns 14.868 ns 14.940 ns]                                                       
change: [-14.744% -14.274% -13.812%] (p = 0.00 < 0.05)                                        
Performance has …
```

core/benches: Add rudimentary benchmark for PeerId::from_bytes and clone

---

protocols/mdns/CHANGELOG.md
protocols/mdns/src/behaviour.rs
protocols/mdns/src/dns.rs
protocols/mdns/src/lib.rs
protocols/mdns/src/service.rs

Currently, when an MDNS response gets larger than 9000 bytes due to the number of addresses being encoded, a panic is triggered. See https://github.com/libp2p/rust-libp2p/issues/1872. There are primarily two approaches for dealing with the `9000` bytes MDNS packet size limit: Creating multiple packets or trimming the packet by dropping addresses. Since I didn't find any restriction in the MDNS specifications w.r.t. the number of multicast response packets that can be sent (we don't support or send unicast response packets, I think), I opted for the former. So we now prevent MDNS response packets becoming too large (> 9000 bytes) by using conservative upper bounds and creating multi-packet responses if necessary (effectively when there are more than 29 addresses to encode, which …

[mdns] Split response packets if necessary.

---

core/benches/peer_id.rs

Small follow up on https://github.com/libp2p/rust-libp2p/pull/1875 adding an altered version of the `sort_vec` benchmark suggested in https://github.com/libp2p/rust-libp2p/pull/1875#issuecomment-739893901.

core/benches: Add PeerId sort_vec benchmark

---

CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/request-response/CHANGELOG.md

This release includes new releases of `libp2p-request-response` ([changelog](https://github.com/libp2p/rust-libp2p/blob/master/protocols/request-response/CHANGELOG.md#070-unreleased)) and `libp2p-mdns` ([changelog](https://github.com/libp2p/rust-libp2p/blob/master/protocols/mdns/CHANGELOG.md#0260-unreleased)).

Prepare release of `libp2p-0.32`

---

CHANGELOG.md
Cargo.toml
transports/websocket/CHANGELOG.md
transports/websocket/Cargo.toml

After the upgrade to rustls 0.19, this is the minimum version required to build, avoiding temporarily puzzling compile errors if someone has `0.10.0` in a `Cargo.lock`. Prepares a patch release.

[websocket] Update minimum async-tls patch version.

---

protocols/request-response/CHANGELOG.md
protocols/request-response/src/lib.rs
protocols/request-response/src/throttled.rs
protocols/request-response/tests/ping.rs

A user of libp2p-request-response is guaranteed to receive an additional event
after receiving a request via `RequestResponseEvent::Message`.
After receiving the request:
- If the user responds in time and the connection is still alive, the
user can expect a `ResponseSent`.
- If the user drops the response channel, the user can expect an
`InboundFailure::ResponseOmission`.
- If the user does not respond in time, the user can expect an
`InboundFailure::Timeout`.
Thus far the user did not receive an event when the connection to the
peer closes. With this commit:
- If the connection to the peer closes before the users calls
`send_response` or after the user calls `send_response` but before the
response can be send on the network, the user can expect an
`InboundFailure::ConnectionClosed`.
--- …

protocols/request-response: Emit InboundFailure::ConnectionClosed

---

protocols/request-response/CHANGELOG.md
protocols/request-response/src/lib.rs

With `InboundFailure` and `OutboundFailure` implementing `Clone` a user of `libp2p-request-response` can handle a failure in one place, and record the failure for statistical purposes (e.g. a monitoring system) in a different place without the need to introduce a new structure for the latter code path.
While the above would benefit Substrate (see https://github.com/paritytech/substrate/pull/7478#discussion_r526867672) it does allow ambiguity in terms of where an error that has been cloned before should be handled. For more details see the discussion on Substrate linked before.

protocols/request-response: Derive Clone for {Inbound,Outbound}Failure

---

protocols/pnet/Cargo.toml
protocols/pnet/src/crypt_writer.rs
protocols/pnet/src/lib.rs

Issue #1890 
Patch the `salsa20` dependency of libp2p-pnet to the current version `v0.7` since `v0.6` depends on the deprecated crate  `stream-cypher`.

libp2p-pnet: patch salsa20 dependency

---

protocols/kad/src/handler.rs
protocols/request-response/src/handler/protocol.rs
swarm/CHANGELOG.md
swarm/src/behaviour.rs
swarm/src/lib.rs

With this pull request I would like to suggest removing the ability of a `NetworkBehaviour` to notify all `ProtocolHandler`s for a given peer with a single `NetworkBehaviourActionEvent`. More concretely I am suggesting to remove `NotifyHandler::All`. An
implementor of `NetworkBehaviour` can still notify all `ProtocolHandler`s for a given peer by emitting one `NotifyHandler` event per connection to that peer.
The general ability to notify all handlers for a peer forces events send from the behaviour to the handler to be `Clone`. Reason is that the swarm needs to forward a clone of the event to each handler. A behaviour that always sends events to a single peer only still has to guarantee that that event is `Clone`.
As a concrete example https://github.com/libp2p/rust-libp2p/pull/1838/ …

swarm: Remove NotifyHandler::All

---

CHANGELOG.md
core/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/deflate/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/noise/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/plaintext/CHANGELOG.md
protocols/pnet/CHANGELOG.md
protocols/request-response/CHANGELOG.md
protocols/secio/CHANGELOG.md
swarm/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

I propose to cut another release (`v0.33.0`) of rust-libp2p and all its dependencies. While it would be nice to get https://github.com/libp2p/rust-libp2p/pull/1886 into https://github.com/paritytech/substrate/pull/7478/ via this release https://github.com/paritytech/substrate/pull/7478/ is not blocked on it. My motivation is much rather the general goal of cutting small releases often instead of cutting large releases rarely.

*CHANGELOG.md: Prepare v0.33.0 release

---

docs/release.md

Some `Cargo.toml` files contain multiple `name` fields, e.g. the crate name and
the benchmark name (see
https://github.com/libp2p/rust-libp2p/blob/master/core/Cargo.toml). Only choose
the first one when constructing the tag.

docs/release: Only choose crate name not bench name

---

protocols/request-response/src/throttled.rs

Re-export `throttled`-specific response channel.

---

protocols/kad/src/kbucket/key.rs

- From<record::Key>
- From<Vec<u8>
- this will enable to use additional types in kad.get_closest_peers as it was possible in pre 0.33 version

Add From impl for kbucket::Key

---

misc/multiaddr/src/onion_addr.rs

I have no idea why, but the person who introduced this code decided to use `serde::export::Formatter`, which is a hidden export not supposed to be used, instead of `std::fmt::Formatter`, even though they're the same thing.
In serde 1.0.119, the `export` module is no longer public, which broke the build.

Fix compilation with serde 1.0.119

---

core/Cargo.toml
protocols/floodsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/kad/Cargo.toml
protocols/noise/Cargo.toml
protocols/plaintext/Cargo.toml

Not quite sure why dependabot assumed that `prost-build` is up to date in https://github.com/libp2p/rust-libp2p/pull/1906#issuecomment-758605604. Either way, I think we should use the same version of `prost` and `prost-build`.

*: Update to prost-build v0.7

---

Cargo.toml
protocols/mdns/Cargo.toml
transports/tcp/Cargo.toml
transports/uds/Cargo.toml

Now that `bytes` is up-to-date we can update to `tokio` `v1.0.1`. Replaces https://github.com/libp2p/rust-libp2p/pull/1907.
I would suggest we merge this before the new release (https://github.com/libp2p/rust-libp2p/pull/1918).

*: Update to tokio v1.0.1

---

CHANGELOG.md
core/CHANGELOG.md
misc/multiaddr/CHANGELOG.md
misc/multistream-select/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/deflate/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/noise/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/plaintext/CHANGELOG.md
protocols/request-response/CHANGELOG.md
swarm/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

I would like to release a new version of `libp2p` (`v0.34.0`) and new versions of its sub-crates.
I would suggest to wait for https://github.com/libp2p/rust-libp2p/pull/1917 to be merged before proceeding here. I don't think it is worth blocking the release for https://github.com/libp2p/rust-libp2p/pull/1916. https://github.com/libp2p/rust-libp2p/pull/1899 is blocked on a new release of `snow` (see https://github.com/libp2p/rust-libp2p/pull/1899#issuecomment-754096109).
@quininer @romanb do I understand correctly that we will hold off with https://github.com/libp2p/rust-libp2p/pull/1889 for now?
I do not plan to release a new version of `libp2p-secio` given its deprecation. Objections? I would even suggest removing the code in the future, only leaving a note with a reference to an older …

*: Prepare v0.34.0 release

---

protocols/gossipsub/src/lib.rs

Removes an extra O in gossipsub's docs.

Fix a typo in gossipsub

---

misc/multiaddr/CHANGELOG.md
misc/multiaddr/Cargo.toml
misc/multiaddr/src/onion_addr.rs

Backport https://github.com/libp2p/rust-libp2p/pull/1912 to `parity-multiaddr` `v0.9` as `v0.9.7`.

misc/multiaddr: Backport serde-related fix to v0.9

---

protocols/gossipsub/src/behaviour.rs

This addresses issue #1926. 
Currently, Gossipsub messages may not be published on a topic if there are no subscribed peers on that topic, however they are being added to a duplicate cache. If the messages are content-addressed, this prevents the user from attempting to republish the message in the future. 
This PR modifies the logic such that messages are only added to the caches (duplicate, memcache and published_messages) if the message could be published to at least one peer. 
Previously, a failed publish would be added the memcache. This meant that the router would gossip about a failed publish, such that if a peer joined the topic after the failed publish (but within the gossip history time window) the message could still be propagated to the newly connected peers. With this PR, a …

[Gossipsub] Prevent non-published messages being added to caches

---

protocols/request-response/src/lib.rs
protocols/request-response/tests/ping.rs

`is_pending_outbound` returns true if the connection
to the mentioned peer hasn't been established, yet.
Closes issue: #1885
Signed-off-by: Tejas Sanap <sanap.tejas@gmail.com>

is_pending_outbound fixes

---

CHANGELOG.md
Cargo.toml
src/lib.rs
swarm-derive/CHANGELOG.md
swarm-derive/Cargo.toml
swarm-derive/src/lib.rs
swarm-derive/tests/test.rs

This PR renames and moves `libp2p-core-derive` as `libp2p-swarm-derive`. This was a small left-over from the extraction of `libp2p-swarm` from `libp2p-core` in https://github.com/libp2p/rust-libp2p/pull/1188, i.e. the `NetworkBehaviour` used to be in `libp2p-core` but since the `derive(NetworkBehaviour)` is now `libp2p-swarm`-specific, rebranding `libp2p-core-derive` as `libp2p-swarm-derive` seems sensible.

[libp2p-core-derive -> libp2p-swarm-derive] Rename and move crate.

---

swarm/CHANGELOG.md
swarm/Cargo.toml
swarm/src/protocols_handler/one_shot.rs

This simply moves the `max_dial_negotiated` field of `OneShotHandler` into its config (and thus making it configurable). The default is set to the formerly hard-coded value of 8.

Allow OneShotHandler's `max_dial_negotiate` limit to be configurable.

---

swarm/CHANGELOG.md
swarm/src/lib.rs

Happened to test this `DialPeerCondition::Always` and found that it never works.

Fix DialPeerCondition::Always handling

---

Cargo.toml
protocols/deflate/CHANGELOG.md
protocols/deflate/Cargo.toml
protocols/deflate/src/lib.rs

Addresses https://github.com/libp2p/rust-libp2p/issues/1932, i.e. the possibility to read uninitialised memory.

[libp2p-deflate] Ensure read buffer is initialised.

---

protocols/request-response/src/lib.rs

Follow up to https://github.com/paritytech/substrate/pull/7957#discussion_r562855389.

protocols/req-resp: Document uniqueness of RequestIds

---

README.md

Links to the libp2p matrix and discord channels are broken. Instead of replacing them, I suggest to remove them for the following reasons:
- We already have Github issues for Rust specific questions.
- We already have the forum (https://discuss.libp2p.io) for general libp2p questions. 
- As far as I know, none of the core maintainers are active in the matrix nor discord channel, thus not being able to help out.
Closes https://github.com/libp2p/rust-libp2p/issues/1948

README: Remove dead-link badges

---

swarm/src/behaviour.rs

`NetworkBehaviour::inject_connected` is called for the first established
connection to a peer only. See `swarm/src/lib.rs`:
```rust
this.behaviour.inject_connection_established(&peer_id, &connection.id(), &endpoint);
if num_established.get() == 1 {
this.behaviour.inject_connected(&peer_id);
}
```
This commit adjusts the documentation accordingly.

swarm/behaviour: Document inject_connected called for first only

---

CHANGELOG.md
Cargo.toml
core/CHANGELOG.md
misc/multiaddr/CHANGELOG.md
misc/multistream-select/CHANGELOG.md
muxers/mplex/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/request-response/CHANGELOG.md
swarm-derive/CHANGELOG.md
transports/plaintext/CHANGELOG.md
transports/tcp/CHANGELOG.md

This release mainly consolidates a couple of patch releases.

[release] Prepare v0.35

---

CHANGELOG.md
Cargo.toml
muxers/yamux/CHANGELOG.md
muxers/yamux/Cargo.toml

This PR updates `libp2p-yamux` to use `yamux-0.8.1` in preparation for `yamux-0.9` (see https://github.com/paritytech/yamux/pull/115). Once this upgrade is released in `libp2p-0.35.1`, a PR for a libp2p update for substrate follows.

Update to yamux-0.8.1

---

README.md

Numerous projects in our org use rust-libp2p. Link to the whole org instead of one specific repository.

Link to the GitHub org instead of the project

---

Cargo.toml
protocols/floodsub/CHANGELOG.md
protocols/floodsub/Cargo.toml
protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/Cargo.toml
protocols/identify/CHANGELOG.md
protocols/identify/Cargo.toml
protocols/kad/CHANGELOG.md
protocols/kad/Cargo.toml
protocols/mdns/CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/ping/CHANGELOG.md
protocols/ping/Cargo.toml
protocols/request-response/CHANGELOG.md
protocols/request-response/Cargo.toml
swarm/CHANGELOG.md
swarm/Cargo.toml
swarm/src/protocols_handler.rs
swarm/src/protocols_handler/multi.rs
swarm/src/protocols_handler/node_handler.rs
swarm/src/protocols_handler/select.rs

Remove the option for a substream-specific multistream select protocol version override. The override at this granularity is no longer deemed useful (and probably never was), in particular because it can usually not be configured for existing protocols like `libp2p-kad` and others. There is a `Swarm`-scoped configuration for this version available since [1858](https://github.com/libp2p/rust-libp2p/pull/1858).
Closes #1859.

[swarm] Remove substream-specific protocol negotiation version.

---

protocols/mdns/src/service.rs

Considering that any software running on the local network of a machine can emit invalid mDNS packets, failing to parse a packet is a normal situation, and it feels exaggerated to emit a warning.

Parsing mDNS packet failure: warn -> debug

---

Cargo.toml

If you directly rely on libp2p crate, you cannot turn off some default-features even if you use `default-features = false`.

Don't leak default features

---

Cargo.toml
core/CHANGELOG.md
core/Cargo.toml
core/src/identity/ed25519.rs
core/src/identity/rsa.rs
core/src/identity/secp256k1.rs

This PR is just a small update to the `Debug` impls of public key types. Specifically, ed25519 `PublicKey` and secp256k1 `PublicKey` get a new, shorter `Debug` impl, rather than a derived one (which dumps details that are usually not relevant for a libp2p user), while RSAs `PublicKey` is just aligned with the others for uniformity of the syntax. Closes #1939.

[core] Shorten and unify Debug impls of public keys.

---

protocols/request-response/src/handler/protocol.rs
protocols/request-response/src/lib.rs
protocols/request-response/tests/ping.rs

This was already fixed at some point (https://github.com/libp2p/rust-libp2p/pull/1660) but it seems that recent changes unfortunately undid this again.
I added a test that verifies that the connection is closed for the dialing party.

Close response stream even if response cannot be sent

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs
protocols/kad/src/lib.rs

This PR adds `Kademlia::put_record_to` for storing a record at specific nodes, e.g. for write-back caching after a successful read. In that context, peers that were queried in a successful `Kademlia::get_record` operation but did not return a record are now returned in the `GetRecordOk::no_record` list of peer IDs as additional information which may be used to choose which of these peers to send (one of) the found records to.
The motivation for this PR originates in the discussion at https://github.com/libp2p/rust-libp2p/issues/1577, i.e. the inability for libp2p-kad itself to do write-back caching of records after successful lookups when a quorum > 1 is used. It is deemed best and the most flexible to provide the means to do so on the API. There may be other use-cases for targeted store …

[kad] Provide a targeted store operation.

---

protocols/relay/tests/lib.rs

In the `libp2p-relay` Kademlia discovery test, ignore Kademlia routing
update events when waiting for a ping from the destination node.
[Surfaced on CI](https://github.com/libp2p/rust-libp2p/pull/1992/checks?check_run_id=2087534314).

protocols/kad/tests: Ignore Kademlia routing update event

---

protocols/relay/tests/lib.rs

As previously mentioned (https://github.com/libp2p/rust-libp2p/pull/1998#issuecomment-799226013), CI surfaced yet another test flake introduced with https://github.com/libp2p/rust-libp2p/pull/1838. Sorry for the trouble this might have caused on other peoples end.

protocols/relay: Ignore IdentifyEvent::Error

---

CHANGELOG.md
core/CHANGELOG.md
misc/multiaddr/CHANGELOG.md
misc/multistream-select/CHANGELOG.md
muxers/mplex/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/relay/CHANGELOG.md
protocols/request-response/CHANGELOG.md
swarm/CHANGELOG.md
transports/deflate/CHANGELOG.md
transports/dns/CHANGELOG.md
transports/noise/CHANGELOG.md
transports/plaintext/CHANGELOG.md
transports/tcp/CHANGELOG.md
transports/uds/CHANGELOG.md
transports/wasm-ext/CHANGELOG.md
transports/websocket/CHANGELOG.md

I would like to cut a new release once https://github.com/libp2p/rust-libp2p/pull/1927 and https://github.com/libp2p/rust-libp2p/pull/1931 are merged. What do people think? Anything else you would like to see included?

*: Prepare v0.36.0 release

---

protocols/identify/CHANGELOG.md
protocols/identify/src/identify.rs

This PR picks up a suggestion of @mxinden from https://github.com/libp2p/rust-libp2p/pull/1999#pullrequestreview-614608033. When a new or expired listen address is reported by the `Swarm`, it can result in an active push of an identify message to all connected peers. Two points worth noting:
1. I've made this behaviour configurable and _disabled_ it by default. I think that having such new features opt-in initially avoids surprises and allows selective experimentation in a more controlled manner. Also, since listen addresses are often not directly reachable due to NAT, it may be better if it is selectively enabled for those nodes who are known to be deployed with publicly reachable listen addresses. Lastly, if there are potentially _a lot_ of connected peers, this kind of active push may …

[identify] Add configurable automatic push on listen addr changes.

---

CHANGELOG.md
Cargo.toml
transports/dns/CHANGELOG.md
transports/dns/Cargo.toml

Follow up to https://github.com/libp2p/rust-libp2p/pull/1994/:
> Versions <1.6.1 are vulnerable to a buffer overflow. See
> https://rustsec.org/advisories/RUSTSEC-2021-0003.html for details.

transports/dns: Require smallvec >= 1.6.1

---

protocols/mdns/src/behaviour.rs

Towards #2006 unblocks a new ipfs-embed release.

mdns: MdnsConfig derives Clone and Debug.

---

transports/wasm-ext/Cargo.toml

Fixes https://github.com/libp2p/rust-libp2p/issues/2020

Upgrade js-sys to fix compilation

---

examples/ping.rs
src/lib.rs
src/tutorial.rs

This commit extends the ping example in `src/tutorial.rs, by walking a
newcomer through the implementation of a simple ping node step-by-step,
introducing all the core libp2p concepts along the way.
With the ping tutorial in place, there is no need for the lengthy libp2p
crate level introduction, which is thus removed with this commit.

src: Move introduction to new tutorial.rs

---

transports/dns/src/lib.rs

Fix https://github.com/libp2p/rust-libp2p/issues/2022
See [this comment](https://github.com/libp2p/rust-libp2p/issues/2022#issuecomment-809733928)

Remove fqdn() function from libp2p-dns

---

README.md

I am proposing to link to the IPFS Code of Conduct in our README to make sure work on rust-libp2p is happening in a friendly and respectful environment.
Please get involved in case you have any suggestions or comments, either here in public or via a private mail.

README: Link to Code of Conduct

---

protocols/request-response/CHANGELOG.md
protocols/request-response/src/lib.rs

Implement std::error::Error for InboundFailure and OutboundFailure

---

protocols/identify/CHANGELOG.md
protocols/identify/src/handler.rs
protocols/identify/src/identify.rs

> Emit `IdentifyEvent::Pushed` event after successfully pushing identification
information to peer.
Small follow up on past discussion https://github.com/libp2p/rust-libp2p/pull/1999#discussion_r597082362.

protocols/identify: Emit Push event after successful identification push

---

.github/workflows/ci.yml

Instead of fully executing benchmarks, i.e. running multiple iterations,
each measured and recorded, only test that they compile and run them
with a single execution to make sure they work. The benefit is a reduced
CI runtime.
Flag documentation:
> To test that the benchmarks run successfully without performing the
measurement or analysis (eg. in a CI setting), use cargo test --benches.
https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html
The above assumes that (a) the benchmark results from CI are likely
noisy and thus (b) no one actually looks at the benchmark results.

.github: Only test benchmarks, don't run them

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml

With `rand` `v0.8.0` platform support changed [1] due to its upgrade to
`getrandom` `v0.2`. With `getrandom` `v0.2` `wasm32-unknown-unknown` is no
longer supported out of the box:
> This crate fully supports the wasm32-wasi and wasm32-unknown-emscripten
> targets. However, the wasm32-unknown-unknown target is not automatically
> supported since, from the target name alone, we cannot deduce which JavaScript
> interface is in use (or if JavaScript is available at all).
>
> Instead, if the "js" Cargo feature is enabled, this crate will assume that you
> are building for an environment containing JavaScript, and will call the
> appropriate methods. Both web browser (main window and Web Workers) and
> Node.js environments are supported, invoking the methods described above using
> the …

*: Drop generic wasm32-unknown-unknown support

---

CHANGELOG.md
core/CHANGELOG.md
muxers/yamux/CHANGELOG.md
protocols/floodsub/CHANGELOG.md
protocols/gossipsub/CHANGELOG.md
protocols/identify/CHANGELOG.md
protocols/kad/CHANGELOG.md
protocols/mdns/CHANGELOG.md
protocols/ping/CHANGELOG.md
protocols/relay/CHANGELOG.md
protocols/request-response/CHANGELOG.md
swarm/CHANGELOG.md

I would like to cut `libp2p` `v0.37.0`. Any objections? Anything you would like to see included which is not in `master` today?
I would suggest releasing https://github.com/libp2p/rust-libp2p/pull/2043 as a separate bug-fix release.

*: Prepare v0.37.0 release

---

protocols/mdns/CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/mdns/src/behaviour.rs

If you start listening after mdns joined a multicast group, the peers may not discover eachother until the 5min timeout expires.

Fix mdns taking a long time to discover peers.

---

CHANGELOG.md
Cargo.toml
protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/subscription_filter.rs

Add regex feature for gossipsub

---

CHANGELOG.md
Cargo.toml
transports/wasm-ext/CHANGELOG.md
transports/wasm-ext/Cargo.toml
transports/wasm-ext/src/websockets.js

Changes in https://github.com/libp2p/rust-libp2p/commit/45f07bf8639fd9056e4ffe52298ca113a0308951# now seem to append `/p2p/<peer>` to multiaddr passed to transports. The regex in transport/wasm-ext doesn't support this fully qualified format. Supporting extra suffixes in the regex fixes the issue, but I'm wondering if it it should match on `\/p2p\/.*` instead or just plainly accepting any suffix. Let me know what you prefer.

Fix transport/wasm-ext fully qualified p2p multiaddr

---

protocols/mdns/CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/mdns/src/behaviour.rs

mdns keeps rediscovering nodes. this PR changes that to only emit events for new nodes it discovered. In addition we make sure to only send a query if it is really needed. Some logging is added for debugging purposes.

Fix discovered event emission.

---

protocols/relay/examples/relay.rs

Add instructions on how to run a three node example where a listening
relay client listens via a relay server and a dialing relay client dials
the listening relay client via the relay server.
//CC @r-zig

protocols/relay/examples: Add client server instructions

---

README.md

This pull request removes the IRC link to freenode on the main README.md. This is motivated by:
1. I am not monitoring this channel. Unless someone else from the rust-libp2p community is, removing it should reduce disappointment for newcomers.
2. IPFS moving away from freenode (see https://github.com/ipfs/ipfs-docs/pull/787).

README: Remove freenode IRC link

---

muxers/mplex/CHANGELOG.md
muxers/mplex/src/codec.rs
muxers/mplex/src/io.rs

hi @mxinden,
I have opened this PR for closing issue: #2061
Do we also need write a test to check if we can actually use 60 bit stream ID?

muxers/mplex: Allow up to 60 bit long stream IDs

---

transports/dns/src/lib.rs

Closes https://github.com/libp2p/rust-libp2p/issues/2064

transports/dns: Document caveats of using the `trust-dns-resolver` crate

---

protocols/gossipsub/src/behaviour.rs
protocols/request-response/src/throttled.rs
swarm-derive/src/lib.rs
swarm/CHANGELOG.md
swarm/src/behaviour.rs
swarm/src/lib.rs
swarm/src/test.rs

Currently, we use a custom version of the [rust-libp2p](https://github.com/KomodoPlatform/rust-libp2p/tree/master) crate in the https://github.com/KomodoPlatform/atomicDEX-API project that allows us to disconnect peers from the network behaviour.
I would like to propose this functionality to allow the users to build their custom behaviors with the ability to disconnect peers.
Please look at the example of using `NetworkBehaviourAction::DisconnectPeer'`: https://github.com/KomodoPlatform/atomicDEX-API/blob/mm2.1/mm2src/mm2_libp2p/src/adex_ping.rs#L27
* Add 'NetworkBehaviourAction::DisconnectPeer'
* Add 'ExpandedSwarm::disconnect_peer_id'
* Add 'test_swarm_disconnect', 'test_behaviour_disconnect_all', 'test_behaviour_disconnect_one'

Add the ability for the behaviour to disconnect a peer

---

core/CHANGELOG.md
core/src/upgrade.rs
core/src/upgrade/from_fn.rs
core/src/upgrade/transfer.rs
protocols/floodsub/CHANGELOG.md
protocols/floodsub/src/protocol.rs
protocols/identify/src/protocol.rs
protocols/request-response/tests/ping.rs

This PR re-designs the above three functions to:
- allow for better composition
- remove footguns
- make them easier to use
We achieve this by:
1. Deprecating the `write_one` function
Semantically, this function is a composition of `write_with_len_prefix` and `io.close()`. This represents a footgun because the `close` functionality is not obvious and only mentioned in the docs. Using this function multiple times on a single substream will produces hard to debug behaviour.
2. Deprecating `read_one` and `write_with_len_prefix` functions
3. Introducing `write_length_prefixed` and `read_length_prefixed`
- These functions are symmetric and do exactly what you would expect, just writing to the socket without closing
- They also have a symmetric interface (no more custom errors, just …

Redesign `upgrade::{write_one, write_with_len_prefix, read_one}`

---

examples/chat-tokio.rs
examples/chat.rs
examples/distributed-key-value-store.rs
examples/gossipsub-chat.rs
examples/ipfs-private.rs
examples/ping.rs
protocols/identify/src/identify.rs
protocols/ping/tests/ping.rs
protocols/relay/examples/relay.rs
protocols/relay/tests/lib.rs
protocols/request-response/tests/ping.rs
src/tutorial.rs
swarm/CHANGELOG.md
swarm/src/lib.rs

This PR drafts a change that I'd like to suggest:
I think it would be useful if in case of `SwarmEvent`s associated with a listener (e.g. `SwarmEvent::NewListenAddr`), the event would include the id of the associated listener. 
It allows to map the event back to a previously called `swarm.listen_on()`. This is especially useful if `swarm.listen_on()` was called with an zeroed Multiaddress (e.g. `/ip4/0.0.0.0/tcp/0`), and the actual new address should be mapped back to the newly created listener, without blocking.
Since this information is already in the `NetworkEvent` that the ExpandedSwarm receives, I don't see a reason to not include it, especially since the user already has to deal with `ListenerId`s.

swarm/: include ListenerId in SwarmEvents

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs

Given the following scenario:
1. Remote peer X connects and is added to `connected_peers`.
2. Remote peer X opens a Kademlia substream and thus confirms that it supports
the Kademlia protocol.
3. Remote peer X is added to the routing table as `Connected`.
4. Remote peer X disconnects and is thus marked as `Disconnected` in the routing
table.
5. Remote peer Y connects and is added to `connected_peers`.
6. Remote peer X re-connects and is added to `connected_peers`.
7. Remote peer Y opens a Kademlia substream and thus confirms that it supports
the Kademlia protocol.
8. Remote peer Y is added to the routing table. Given that the bucket is already
full the call to `entry.insert` returns `kbucket::InsertResult::Pending {
disconnected }` where disconnected is peer X.
While peer X is in …

protocols/kad/behaviour: Remove false assert on connected_peers

---

core/Cargo.toml
protocols/floodsub/Cargo.toml
protocols/gossipsub/Cargo.toml
protocols/identify/Cargo.toml
protocols/kad/Cargo.toml
protocols/relay/Cargo.toml
transports/noise/Cargo.toml
transports/plaintext/Cargo.toml

Update `prost` and `prost-build` from v0.7 to v0.8. 
`prost-build` v0.7 depends on outdated version of `prost-types` with the issue https://github.com/tokio-rs/prost/issues/438:
>  Conversion from prost_types::Timestamp to SystemTime can cause an overflow and panic
cc: https://github.com/iotaledger/stronghold.rs/issues/228

*: patch prost / prost-build version to v0.8

---

protocols/kad/CHANGELOG.md
protocols/kad/src/behaviour.rs
protocols/kad/src/behaviour/test.rs

As per the discussion on #2121 
I can confirm that the bootstrap process seems to go a lot better now :-)
@izolyomi, I included you as `Co-authored-by` in the commit, but don't have an email address for it. Let me know if you want a change there.

Return the correct number of remaining bootstrap requests.

---

.github/dependabot.yml

Increase pull request limit to 9999, practically disabling the limit.
I think there is lots of benefit in keeping dependencies up-to-date.
I don't think @dependabot adds much noise.

.github/dependabot: Disable pull request limit

---

core/src/peer_id.rs
muxers/mplex/src/codec.rs
protocols/identify/src/handler.rs
protocols/identify/src/protocol.rs
protocols/kad/src/kbucket.rs
protocols/mdns/src/dns.rs
transports/noise/src/protocol/x25519.rs
transports/noise/src/protocol/x25519_spec.rs

Can drop individual commits if some of the changes are not wanted.
I purposely left everything in `relay` untouched to not interfere with https://github.com/libp2p/rust-libp2p/pull/2059 too much.

Deal with some clippy warnings

---

.cargo/config.toml
.github/workflows/ci.yml
protocols/relay/src/behaviour.rs
protocols/relay/src/handler.rs
protocols/relay/src/protocol/listen.rs
protocols/relay/src/protocol/outgoing_dst_req.rs
protocols/relay/src/protocol/outgoing_relay_req.rs
protocols/relay/src/transport.rs
transports/dns/src/lib.rs

Opened as a result of https://github.com/libp2p/rust-libp2p/pull/2139.
Might also want to change the GitHub configuration to pervent merge if clippy fails.

Enforce no clippy warnings through CI

---

core/src/identity.rs
core/src/identity/ed25519.rs
core/src/identity/secp256k1.rs

As a follow up on issue https://github.com/libp2p/rust-libp2p/issues/2091, I've just added a few sentences on using keys from an external source like an HD wallet or config file.
However, I didn't find related function names too consequent, sometimes it's `decode()`, sometimes `from_bytes()`, even in the same `ed25519` module.

Documented using external fixed keys for network identity

---

core/CHANGELOG.md
core/src/connection/pool.rs

I think it would be useful to be able to specify a total established connection limit, rather than just incoming and outgoing limits. 
If a user wants to set an incoming limit of 10 and an outgoing limit of 5, currently, this has a maximum connection limit of 15, but the ratio of incoming to outgoing is fixed. If a user wishes to specify the total and is happy to have a variable ratio of incoming/outgoing, I think this PR is useful to enable this at the `Network` level. 
This shouldn't break anything as its an optional addition to the `ConnectionLimit` struct.

Add a total established connection limit

---

protocols/floodsub/src/layer.rs
protocols/gossipsub/src/behaviour.rs
protocols/identify/src/identify.rs
protocols/mdns/src/behaviour.rs
protocols/ping/src/lib.rs
protocols/relay/tests/lib.rs
swarm/CHANGELOG.md
swarm/src/behaviour.rs
swarm/src/lib.rs
swarm/src/test.rs

See patches for details.
Not sure how controversial this proposal is :)

Make it easier to define implementations of `NetworkBehaviour`

---

examples/ipfs-private.rs
protocols/ping/CHANGELOG.md
protocols/ping/src/handler.rs
protocols/ping/tests/ping.rs
protocols/relay/tests/lib.rs
swarm/src/lib.rs

Fixes https://github.com/libp2p/rust-libp2p/issues/2109.

Don't force close connections if ping protocol is not supported by remote

---

protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/config.rs

This will allow capturing variables in these closures so that we can
make these functions aware of the forkId (necessary for altair).

Convert message_id_fn's to closures

---

protocols/mdns/CHANGELOG.md
protocols/mdns/Cargo.toml
protocols/mdns/src/behaviour.rs
protocols/mdns/src/dns.rs
protocols/mdns/src/lib.rs
protocols/mdns/tests/smoke.rs

> well it's multicast. so you are doubling the traffic (request sent to n peers and n responses to n peers is n + n2 packets. if you do the same thing on ip6 it's 2(n + n2) packets). if you are only listening on ip4 addresses, then it doesn't hurt as much as no one will respond to ipv6 mdns requests. (for the ip4 only case that would be 2n + n2)
cc @majchrzamemil I think the changes are reasonable, rebased your PR. But as I explained in #1989 enabling them both at the same time should remain optional and preferably only ip4 addresses should be broadcast on ip4 and ip6 addresses on ip6.
revived this effort as I have to do some work on mdns anyway. currently the timeout will expire on all machines at the same time flooding the network, but decided that that should be a separate PR.

IPv6 support for mDNS

---

misc/multistream-select/CHANGELOG.md
misc/multistream-select/Cargo.toml
misc/multistream-select/src/protocol.rs
muxers/yamux/CHANGELOG.md
muxers/yamux/src/lib.rs
protocols/gossipsub/src/types.rs
protocols/kad/src/protocol.rs

Unless restricted by orphan rules, implementing `From` is superior
because it implies `Into` but leaves the choice to the user, which
one to use. Especially for errors, `From` is convenient because that
is what `?` builds on.
Not sure if this needs a changelog entry?

Replace `Into` with `From`

---

swarm/src/behaviour.rs

With 45f07bf8639fd9056e4ffe52298ca113a0308951 `Network::dial` accepts a
`Multiaddr` with a `PeerId`. With that in mind the doc comment on
`NetworkBehaviourAction::DialAddress` is outdated.

swarm/src/behaviour: Update DialAddress doc comment

---

examples/chat.rs
examples/gossipsub-chat.rs
examples/ping.rs
src/tutorial.rs

With #2100, the tutorial and examples were changed to print not only one listening address, but instead each one that is reported via a `SwarmEvent::NewListenAddr`. This resulted in the docs not fitting the actual stdout prints, as they implied that there is only one listening address.
This PR fixes the docs, please feel free to nitpick my wording.

src/tutorial: Enhance docs on multiaddrs

---

protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs

Replaces https://github.com/libp2p/rust-libp2p/pull/2175.

protocols/gossipsub: Inconsistency in mesh peer tracking

---

swarm/CHANGELOG.md
swarm/src/protocols_handler.rs
swarm/src/protocols_handler/either.rs

Add implementation of a ProtocolsHandler that represents either of two
ProtocolsHandler implementations.

swarm/src/protocols_handler: Add EitherHandler

---

core/CHANGELOG.md
core/src/connection/manager.rs
core/src/connection/manager/task.rs
core/src/connection/pool.rs
core/src/network/peer.rs

This logic seems to be a leftover of
https://github.com/libp2p/rust-libp2p/pull/889 and unused today.

core/: Remove DisconnectedPeer::set_connected and Pool::add

---

misc/metrics/src/swarm.rs

Expose whether closed connection was a Dialer or Listener.

misc/metrics/src/swarm: Expose role on connections_closed

---

protocols/rendezvous/Cargo.toml

Fix https://github.com/libp2p/rust-libp2p/issues/2225

Update libp2p-rendezvous to fix build on nightly

---

core/src/connection/manager/task.rs
core/src/connection/pool.rs
core/src/identity/rsa.rs
core/src/peer_id.rs
core/src/signed_envelope.rs
misc/multistream-select/src/length_delimited.rs
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/protocol.rs
protocols/kad/src/handler.rs
protocols/kad/src/kbucket/entry.rs
protocols/kad/src/query/peers/fixed.rs
protocols/mdns/src/behaviour.rs
protocols/mdns/src/dns.rs
protocols/relay/src/behaviour.rs
protocols/relay/src/protocol/incoming_dst_req.rs
swarm-derive/src/lib.rs
swarm/src/behaviour.rs
swarm/src/lib.rs
swarm/src/protocols_handler.rs
swarm/src/registry.rs
transports/dns/src/lib.rs
transports/noise/src/io.rs
transports/noise/src/protocol/x25519.rs
transports/noise/src/protocol/x25519_spec.rs
transports/websocket/src/framed.rs

Mostly removing redundant `&` from references. This PR reduces the number of clippy warnings.

Fix clippy warnings

---

src/tutorial.rs

Previously `ping` events were not displayed.
Updated from: https://github.com/libp2p/rust-libp2p/blob/master/examples/ping.rs

Update ping tutorial: Output ping events

---

protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/error.rs

It's annoying to work with these error types, because they can't be used with the `?` operator. This fixes that

protocols/gossipsub: Implement std::error::Error for error types
