libp2p/rust-libp2p

libp2p-swarm/Cargo.toml, libp2p-swarm/README.md, libp2p-swarm/src/lib.rs
=> Add documentation and README to libp2p-swarm

libp2p-swarm/src/lib.rs
Again, conflict between two PRs.
=> Fix doctest in libp2p-swarm

libp2p-ping/Cargo.toml, libp2p-ping/README.md, libp2p-ping/src/lib.rs
=> Add documentation and README for libp2p-ping

libp2p-swarm/README.md, libp2p-swarm/src/lib.rs
Small improvements, plus explanations about muxing which I had forgotten.
=> More documentation for libp2p-swarm

datastore/README.md, datastore/src/lib.rs
=> Add documentation and README for datastore

rw-stream-sink/README.md, rw-stream-sink/src/lib.rs
=> Add doc and README for rw-stream-sink

libp2p-secio/Cargo.toml, libp2p-secio/README.md, libp2p-secio/src/lib.rs
=> Add documentation and README for secio

libp2p-peerstore/README.md, libp2p-peerstore/src/lib.rs
=> Documentation and README for peerstore

README.md
=> Add a README note about the stabilization of impl Trait

varint-rs/src/lib.rs
This was a stupid oversight by me.
=> Fix varint panicking on large numbers

libp2p-swarm/src/swarm.rs, libp2p-swarm/src/transport.rs
=> Fix using the wrong multistream endpoint

libp2p-swarm/src/connection_reuse.rs
=> Remove a println

libp2p-secio/Cargo.toml, libp2p-secio/src/codec/decode.rs, libp2p-secio/src/handshake.rs, libp2p-secio/src/lib.rs
=> Add logging to secio

identify/src/transport.rs, kad/Cargo.toml, kad/src/high_level.rs, kad/src/kad_server.rs, kad/src/lib.rs, kad/src/query.rs, swarm/src/connection_reuse.rs, swarm/src/lib.rs, swarm/src/swarm.rs, swarm/src/transport.rs, websocket/src/desktop.rs
Same PR as #157 but without the chat example, because the example itself needs improvements.
This PR adds logging to various crates, and applies minor bugfixes.
=> Various fixes and improvements

mplex/Cargo.toml, varint-rs/Cargo.toml
To allow compiling for wasm32-unknown-unknown.
=> Remove the dependency on rustc-serialize

.circleci/config.yml
Forces docker to pull the `rust` image every time.
=> Try fix circleci again

multistream-select/Cargo.toml, multistream-select/src/dialer_select.rs, multistream-select/src/lib.rs, multistream-select/src/listener_select.rs, multistream-select/src/protocol/listener.rs
=> Add log statements to multistream-select.

mplex/src/read.rs
=> Add missing check for read of 0 bytes.

core/src/swarm.rs
=> Use `loop` to poll `FuturesUnordered` after `push`.

ratelimit/Cargo.toml, ratelimit/src/lib.rs
=> Depend on `tokio-io` and `tokio-executor`.

libp2p/src/lib.rs
Only websockets are accepted. This fixes it.
=> Fix CommonTransport not accepting TCP/IP

identify/src/protocol.rs
Based over #249 
This used to be not the case, but we now have access to the remote's multiaddress from the closure of `swarm`. Therefore having it in the `IdentifyOutput` is redundant.
Also, if you use the `IdentifyTransport` then the multiaddress of the remote would be `/p2p/<peer id>`. This is not what you want to send back. The user has to handle this manually.
=> Remove the observed address from identify protocol

core/src/connection_reuse.rs, core/src/swarm.rs
Let's say for example that I send two items on a channel.
When we call `poll()` on the receiving side, it will yield `Ready(Some(item1))`. If we call `poll()` again, it will yield `Ready(Some(item2))`. If then we call `poll()` again, it will yield `NotReady` and register the current task to wake up the next time an item is ready.
However if we only call `poll()` once, then it will just yield the first item and that's it. The task will not wake up again if another item becomes ready.
Sometimes it's not a problem, because `poll()` is usually called from inside another `poll()` function, and this external `poll()` is called multiple times in a row. However if we try to combine two different streams or futures like we do in our code, it can become a problem.
This PR fixes the current code to …
=> Add loops around stream polling

peerstore/src/peerstore.rs
=> Add Peerstore::rm_addr methods

dns/src/lib.rs, multistream-select/src/length_delimited.rs, multistream-select/src/protocol/dialer.rs, multistream-select/src/protocol/listener.rs, multistream-select/src/protocol/mod.rs, multistream-select/src/tests.rs, secio/src/codec/decode.rs, secio/src/codec/encode.rs, secio/src/codec/mod.rs, secio/src/handshake.rs, secio/src/lib.rs, tcp-transport/src/lib.rs
Just me trying clippy again after their announcement that it's part of the `rustup` experience.
=> Some cleanup with clippy and rustfmt

.circleci/config.yml
This is a bit of an experiment to see if it works.
=> Add CircleCI build for win32

kad/Cargo.toml, kad/src/high_level.rs, transport-timeout/Cargo.toml, transport-timeout/src/lib.rs
=> Replaced tokio_time::Deadline with tokio::timer::Timeout

core/src/connection_reuse.rs, core/src/either.rs, core/src/swarm.rs, core/src/transport/interruptible.rs, core/src/unique.rs, core/src/upgrade/choice.rs, protocols/floodsub/src/lib.rs, transports/ratelimit/src/lib.rs, transports/relay/src/copy.rs, transports/tcp/src/lib.rs, transports/timeout/src/lib.rs
some simple fixes, left in my repo for some time...
=> add must_use for Future

transports/tcp/src/lib.rs
=> Populate TcpConfig with more config

core/src/nodes/collection.rs, core/src/nodes/swarm.rs
The user can add multiple addresses for a dial attempt, and they will be tried one after the other, but I forgot to implement the code that tries additional addresses when one fails.
Also includes a fix to `connected_multiaddresses` not being cleaned from old entries.
=> Fix additional addresses not tried

core/src/nodes/swarm.rs
The "expected" and "unexpected" peer IDs were reversed :man_facepalming:
=> Fix logic error in public key mismatch

protocols/secio/Cargo.toml, protocols/secio/src/lib.rs
=> Fix secio compied with --no-default-features

transports/uds/src/lib.rs
=> Deny relative addresses for UNIX domain sockets

protocols/secio/Cargo.toml
Integrates https://github.com/paritytech/rust-secp256k1/pull/14
=> Use paritytech/rust-secp256k1

muxers/yamux/Cargo.toml, transports/ratelimit/Cargo.toml
=> Use yamux and aio-limited from crates.io

protocols/ping/src/lib.rs
Fixed a sentence in `libp2p_ping`
=> minor typo in docs

core/src/upgrade/apply.rs, core/src/upgrade/denied.rs, core/src/upgrade/error.rs, core/src/upgrade/map.rs, core/src/upgrade/mod.rs, core/src/upgrade/or.rs
Adds doc-comments to the `core::upgrade` module.
=> Document the core::upgrade module

core/src/protocols_handler.rs, core/src/upgrade/map.rs, core/src/upgrade/mod.rs
Like #654, but for upgrade errors.
=> Fix mapping of upgrade errors.

core/src/lib.rs, protocols/ping/src/lib.rs, protocols/ping/src/protocol.rs
=> A few typos

protocols/secio/src/codec/decode.rs, protocols/secio/src/codec/mod.rs, protocols/secio/src/handshake.rs, protocols/secio/src/lib.rs
=> secio: Defer nonce verification.

misc/rw-stream-sink/src/lib.rs
Otherwise it may report the reading of 0 bytes which is interpreted as EOF by consumers of `std::io::Read::read`.
=> rw-stream-sink: Skip over empty stream items.

misc/rw-stream-sink/src/lib.rs
=> rw-stream-sink: Add regression test.

Cargo.toml, core/Cargo.toml, misc/mdns/Cargo.toml, misc/multiaddr/Cargo.toml, misc/multihash/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/ping/Cargo.toml, protocols/secio/Cargo.toml, protocols/secio/src/lib.rs, transports/dns/Cargo.toml, transports/relay/Cargo.toml
Unfortunately I couldn't update the cryptographic crates dependencies of secio (which is bad) because of the clusterfuck of traits imported from other libraries.
=> Update some dependencies

core/src/transport/and_then.rs
We poll the `Transport`'s dialing future, and once it succeeds we call the closure and transition our internal state to `B`. But then we return `NotReady` instead of polling the future returned by the closure.
=> Fix Transport::and_then

Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/multistream-select/Cargo.toml, misc/peer-id-generator/Cargo.toml, misc/rw-stream-sink/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/timeout/Cargo.toml, transports/uds/Cargo.toml, transports/websocket/Cargo.toml
=> Add metadata to all the Cargo.toml

core/src/protocols_handler/select.rs, core/src/upgrade/mod.rs, core/src/upgrade/select.rs
Also remove `InboundUpgrade.or_inbound` and `OutboundUpgrade.or_outbound`.
=> Rename `OrUpgrade` to `SelectUpgrade`.

protocols/identify/src/identify.rs, protocols/identify/src/periodic_id_handler.rs, protocols/identify/src/periodic_id_layer.rs
=> Rename PeriodicIdentification to PeriodicIdHandler

Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/websocket/Cargo.toml
Again, preparation for publication.
=> Add version numbers in the deps in Cargo.toml

protocols/identify/src/identify.rs, protocols/identify/src/lib.rs, protocols/identify/src/topology.rs
=> Add an IdentifyTopology

Cargo.toml, core/Cargo.toml, misc/mdns/Cargo.toml, misc/multiaddr/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/ping/Cargo.toml, transports/dns/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/websocket/Cargo.toml
I think the version numbers disappeared after a merge conflict.
=> Add version numbers of multi* deps

core/src/nodes/handled_node.rs, core/src/protocols_handler/dummy.rs, core/src/protocols_handler/map_in.rs, core/src/protocols_handler/map_out.rs, core/src/protocols_handler/mod.rs, core/src/protocols_handler/node_handler.rs, core/src/protocols_handler/select.rs, core/src/tests/dummy_handler.rs, protocols/floodsub/src/handler.rs, protocols/identify/src/listen_handler.rs, protocols/identify/src/periodic_id_handler.rs, protocols/kad/src/handler.rs, protocols/ping/src/dial_handler.rs, protocols/ping/src/listen_handler.rs
=> Don't allow handlers::poll() to return None

.circleci/config.yml
=> Add back an integration test

examples/chat.rs, protocols/floodsub/src/layer.rs, protocols/floodsub/src/lib.rs
=> Floodsub now produces FloodsubEvent

protocols/ping/src/lib.rs, protocols/ping/src/protocol.rs
The documentation was very outdated.
=> Documentation improve to ping and minor improvements

misc/core-derive/Cargo.toml, protocols/secio/Cargo.toml
=> Bump libp2p-secio and libp2p-core-derive

protocols/secio/Cargo.toml, protocols/secio/src/codec/decode.rs, protocols/secio/src/codec/encode.rs, protocols/secio/src/codec/mod.rs, protocols/secio/src/lib.rs, protocols/secio/src/stream_cipher.rs
cc #687 
I couldn't update `sha2` and `hmac` because `ed25519_dalek 0.8` publicly depends on old versions.
=> Update secio dependencies

Cargo.toml, protocols/secio/Cargo.toml, protocols/secio/src/algo_support.rs, protocols/secio/src/exchange/impl_ring.rs, protocols/secio/src/handshake.rs, protocols/secio/src/lib.rs
This release enables RSA signing by default, hence the `rsa_signing` feature has been removed.
=> Update ring to version 0.14

protocols/identify/src/protocol.rs
Right now we just drop the substream (which calls `destroy_substream`) without shutting it down properly (by calling `shutdown_substream`).
Fix #832
=> Properly close identify substreams

protocols/secio/src/lib.rs
=> Add SecioKeypair::ed25519_raw_key

core/src/protocols_handler/node_handler.rs
=> Properly shut down protocols handler on useless timeout

protocols/kad/Cargo.toml, protocols/kad/src/behaviour.rs
Don't add an address to the list if it is already there.
=> Avoid duplicate addresses in kbuckets

core/src/transport/dummy.rs, core/src/transport/mod.rs, src/lib.rs
Compiling for WASM with WebSockets disabled leads to a compilation error at the moment.
=> Fix compiling for WASM with websockets disabled

protocols/identify/src/identify.rs
Add an event when we sent back identification info, successfully or not.
=> Add IdentifyEvent::SendBack event

core/src/transport/memory.rs
Tests were interacting with each other.
=> Use different ports in the memory transport tests

core/tests/raw_swarm_dial_error.rs
Adds tests checking that dialing fails as expected.
=> Add dialing error tests for the raw swarm

CHANGELOG.md, Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/multiaddr/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/noise/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/websocket/Cargo.toml
=> Bump to v0.4

.circleci/config.yml
To reflect https://github.com/tomaka/rustc-emscripten/issues/5#issuecomment-466764262
=> Switch the WASM image to something else

examples/ipfs-kad.rs
the warnings about this method being deprecated noise build log a bit
=> examples: fix deprecated add_address

core/src/swarm.rs, protocols/identify/src/identify.rs, protocols/kad/src/behaviour.rs
Hi, just saw this todo while reading through the code
=> swarm: return references from external_addresses

protocols/kad/src/behaviour.rs
I'm a bit lost with which changes conflict with what, so I just based this over #1012.
Fixes a mistake in Kademlia where we wouldn't disconnect if we're listening.
=> Bugfix in Kademlia disconnected

core/src/swarm.rs
Fix #978 
Will be used for diagnostics in Substrate.
=> Add method to query external addresses

examples/chat.rs, examples/ping.rs
This was no longer the case after https://github.com/libp2p/rust-libp2p/pull/1032. Not sure whether this is the best or easiest way to do it, but it is the first thing that came to mind.
=> Update examples to print a listen address.

transports/dns/Cargo.toml, transports/dns/src/lib.rs, transports/tcp/Cargo.toml, transports/tcp/src/lib.rs, transports/uds/Cargo.toml, transports/uds/src/lib.rs, transports/websocket/Cargo.toml, transports/websocket/src/browser.rs, transports/websocket/src/desktop.rs
=> remove direct dependencies on multiaddr

protocols/kad/src/behaviour.rs, protocols/kad/src/handler.rs, protocols/kad/src/protocol.rs
=> Allow changing the Kademlia protocol name

CHANGELOG.md, Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/multiaddr/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/noise/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/wasm-ext/Cargo.toml, transports/websocket/Cargo.toml
Doesn't have to be merged right-now-right-now. We can merge other things before.
=> Publish version 0.8.0

core/src/upgrade/mod.rs, core/src/upgrade/optional.rs
Necessary for Substrate.
I can't believe there was no way to do that.
=> Add OptionalUpgrade

README.md
Couple of weeks back we replaced our hand-rolled network layer with libp2p, hence we would like to tell the world that we are now also using this awesome library :)
=> Add comit-rs to README

protocols/secio/Cargo.toml, transports/wasm-ext/Cargo.toml
=> Bump secio and wasm-ext crates

Cargo.toml, protocols/deflate/Cargo.toml, protocols/deflate/src/lib.rs, protocols/deflate/tests/test.rs, src/lib.rs
Add deflate protocol; fixes #955.
I hope I did this right, although I'm not 100% sure being so new to rust-libp2p and the surrounding ecosystem.
=> Add deflate protocol

CHANGELOG.md, Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/multiaddr/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/deflate/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/noise/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/wasm-ext/Cargo.toml, transports/websocket/Cargo.toml
Waiting for `soketto` to be published before we can publish this.
=> Publish v0.9.0

transports/wasm-ext/src/lib.rs
I'd like to use `wasm_ext` for Substrate's telemetry. Each message sent to the telemetry must be exactly one WebSocket frame. However, the `Connection` implements `AsyncRead`/`AsyncWrite` and is considered as a stream of bytes.
In order to make it possible to delimit WebSocket frames, the easiest solution is to make it guaranteed that one call to `write` is one call to the FFI's write.
That's the kind of things that a test could cover, however I don't know anything about the automated testing story of WASM.
=> Add comment to wasm_ext::Connection

transports/websocket/Cargo.toml, transports/websocket/src/error.rs, transports/websocket/src/tls.rs
Also ensure error types in libp2p-websocket are `Sync`.
Fixes #1162.
=> Update soketto dependency to 0.1.0.

examples/ipfs-kad.rs
From this list: https://github.com/ipfs/go-ipfs-config/blob/bdd9404aa82d111e90e0a2b5175daefa4bebbd63/bootstrap_peers.go#L22-L34
=> Update the IPFS bootnodes

protocols/kad/src/behaviour.rs, protocols/kad/src/behaviour/test.rs
It would be nice to know exactly which key was not found.
=> Report which key exactly was not found.

core/src/swarm.rs, core/src/swarm/behaviour.rs, core/src/swarm/registry.rs, core/src/swarm/swarm.rs, core/src/swarm/toggle.rs, misc/core-derive/src/lib.rs, misc/mdns/src/behaviour.rs, protocols/floodsub/src/layer.rs, protocols/identify/src/identify.rs, protocols/kad/src/behaviour.rs, protocols/ping/src/lib.rs
Allows testing the `NetworkBehaviour` by passing custom parameters to `poll`.
=> PollParameters is now a trait

CHANGELOG.md, Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/deflate/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/noise/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/wasm-ext/Cargo.toml, transports/websocket/Cargo.toml
To merge on top of https://github.com/libp2p/rust-libp2p/pull/1178.
=> Publish v0.10.0

CHANGELOG.md, Cargo.toml, core/Cargo.toml, protocols/noise/Cargo.toml
=> Publish v0.9.2 with zeroize

core/src/nodes/tasks/error.rs
=> Add missing copyright header.

CHANGELOG.md, Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/mdns/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/deflate/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/noise/Cargo.toml, protocols/observed/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, swarm/Cargo.toml, transports/dns/Cargo.toml, transports/ratelimit/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/wasm-ext/Cargo.toml, transports/websocket/Cargo.toml
To publish on crates.io after this PR is merged.
=> Publish v0.11.0

core/src/lib.rs, core/src/nodes/listeners.rs, core/src/nodes/network.rs, core/src/nodes/network/tests.rs, core/src/transport/and_then.rs, core/src/transport/map.rs, core/src/transport/memory.rs, core/src/transport/mod.rs, core/tests/network_dial_error.rs, transports/tcp/src/lib.rs, transports/uds/src/lib.rs, transports/wasm-ext/src/lib.rs, transports/websocket/src/framed.rs
PR on top of #1218 ~~(only the last commit https://github.com/libp2p/rust-libp2p/commit/715687bc7749986386362074e3fd94fc86755f94 is new)~~ to fix #1221.
=>  Replace `listen_addr` with `local_addr`.

protocols/floodsub/src/layer.rs, protocols/floodsub/src/protocol.rs
I had already done most of the work, but had paused it before of the lack of transfer functions at the time.
=> Fix floodsub with new futures

protocols/secio/src/algo_support.rs
That's a bit embarrassing. Good thing we didn't publish a version.
=> Revert CIPHERS set to null

transports/websocket/Cargo.toml, transports/websocket/src/framed.rs, transports/websocket/src/lib.rs
See https://github.com/paritytech/soketto/pull/11 for details.
=> Update to current soketto `develop`.

core/src/nodes/listeners.rs, core/tests/network_simult.rs, core/tests/transport_upgrade.rs, misc/multistream-select/src/length_delimited.rs, transports/uds/src/lib.rs
Tests should pass now. Remaining CI issues:
- Integration tests often fail with "Query finished with no closest peers."
- `ci/circleci: test` attempts to run a "Try the async-await feature" step which fails with `toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed`.
=> Fix remaining tests.

.circleci/config.yml
This reverts a change made early on in the `stable-futures`.
In order to get this PR, I just did a `git checkout master .circle/config.yml`.
=> Fix the regular tests for stable-futures

protocols/noise/src/io.rs
=> Backport #1347 to master

CHANGELOG.md, Cargo.toml, core/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/noise/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml
(note: this PR is towards master)
Fix #1363 
Also includes https://github.com/libp2p/rust-libp2p/pull/1347
=> Pin protobuf versin and publish 0.13.2

core/Cargo.toml, misc/rw-stream-sink/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/secio/Cargo.toml, transports/websocket/Cargo.toml
=> Bump rw-stream-sink to 0.2

protocols/kad/src/handler.rs
Right now whenever `poll()` of Kademlia is called, we set `keep_alive` to either `Until` or `Yes`.
The intent of this code code is that is updates `keep_alive` is response to something related to Kademlia happening.
Unfortunately, `poll()` can be called even if nothing happened.
I also changed the initial value of `keep_alive`. Right now it is set to `Yes` by default, but if nothing ever happens then that value will stay `Yes` forever and the connections will never die.
=> Don't set KeepAlive to Until all the time

core/src/nodes/collection.rs, core/src/nodes/network.rs, core/src/nodes/tasks/manager.rs, swarm/src/lib.rs
Amending #1391 to add a `Send` requirement on the executor.
=> Executor + Send

protocols/gossipsub/Cargo.toml
=> Add metadata to gossipsub

.github/workflows/ci.yml
I'm opening this PR quickly after merging #1430 in order to see if CI works.
If CI fails, I'll also fix any failure as part of this PR.
=> Propagate rustdoc links check to GH actions

CHANGELOG.md, Cargo.toml, protocols/kad/Cargo.toml, protocols/secio/Cargo.toml, swarm/Cargo.toml, transports/wasm-ext/Cargo.toml
To merge after https://github.com/libp2p/rust-libp2p/pull/1454
=> Publish 0.16.1

muxers/yamux/src/lib.rs
The API contract of Yamux is that the connection has to be polled until `None` or some `Err(_)` is returned. Therefore while closing we need to keep polling the connection. Only polling the control channel will not have an effect but `close` will always return `Poll::Pending` as the connection does not make progress.
=> Keep polling connection when closing.

protocols/mdns/src/behaviour.rs
Useful for diagnostic purposes.
=> Add Mdns::discovered_nodes

Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/multistream-select/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/deflate/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/gossipsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/mdns/Cargo.toml, protocols/noise/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/pnet/Cargo.toml, protocols/secio/Cargo.toml, swarm/Cargo.toml, transports/dns/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/wasm-ext/Cargo.toml, transports/websocket/Cargo.toml
=> Bump to 0.17.0

CHANGELOG.md
Administrative pull request.
Should probably have been part of the other version-release-related pull requests. I didn't handle this very well.
=> Update CHANGELOG.md with 0.17.0

protocols/gossipsub/src/handler.rs
Replaces https://github.com/libp2p/rust-libp2p/pull/1539.
(I can't merge master into @AgeManning branch.)
=> [Gossipsub] Correct max transmit size error handling (v2)

.github/workflows/ci.yml
While this PR does a small update, I opened it mainly to see if the CI continues to fail.
=> Update CI to clang-10

CHANGELOG.md, Cargo.toml, core/Cargo.toml, misc/core-derive/Cargo.toml, misc/multiaddr/Cargo.toml, misc/peer-id-generator/Cargo.toml, muxers/mplex/Cargo.toml, muxers/yamux/Cargo.toml, protocols/deflate/Cargo.toml, protocols/floodsub/Cargo.toml, protocols/gossipsub/Cargo.toml, protocols/identify/Cargo.toml, protocols/kad/Cargo.toml, protocols/mdns/Cargo.toml, protocols/noise/Cargo.toml, protocols/ping/Cargo.toml, protocols/plaintext/Cargo.toml, protocols/pnet/Cargo.toml, protocols/secio/Cargo.toml, swarm/Cargo.toml, transports/dns/Cargo.toml, transports/tcp/Cargo.toml, transports/uds/Cargo.toml, transports/wasm-ext/Cargo.toml, transports/websocket/Cargo.toml
I bumped `parity-multiaddr` to 0.9 as well because of the `multihash` upgrade.
=> Publish 0.19.0

src/lib.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
=> Fix tcp-tokio feature

README.md
Add marcopoloprotocol to the list
=> Update README.md, add a open source project

Cargo.toml, transports/websocket/Cargo.toml, transports/websocket/src/framed.rs, transports/websocket/src/lib.rs
Depends on https://github.com/paritytech/soketto/pull/19.
=> Update to soketto v0.4.0

protocols/gossipsub/CHANGELOG.md
Updates the changelog with #1583
=> Update the gossipsub changelog

examples/distributed-key-value-store.rs
This PR is related to https://github.com/libp2p/rust-libp2p/issues/1526.
I adapted the distributed-key-value-store example to also support provide and get providers queries.
Let me know if you'd prefer this in a whole other example. I also didn't rename the example as I'm not sure how to call it.
=> Examples: adapt distributed-key-value-store to also GET / PUT providers

CHANGELOG.md, muxers/yamux/CHANGELOG.md, muxers/yamux/Cargo.toml
See https://github.com/paritytech/yamux/pull/94.
=> yamux-0.5.0 upgrade

CHANGELOG.md, Cargo.toml, core/Cargo.toml, muxers/mplex/Cargo.toml, protocols/pnet/CHANGELOG.md, protocols/pnet/Cargo.toml, protocols/pnet/src/lib.rs, protocols/secio/Cargo.toml
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
=> Update some dependencies not detected by dependabot

Cargo.toml, examples/chat-tokio.rs
Basically, It took me a long time to figure out how to get libp2p swarm polling to work with tokio so I wanted to add an official example to help out any newcomers.
=> Add another chat example (but it uses tokio instead of async_std)

muxers/mplex/src/io.rs
This PR adds a new test to close https://github.com/libp2p/rust-libp2p/issues/345.
=> [mplex] Add test for closing substreams on error.

LICENSE, core/src/lib.rs
The QUIC branch that Demi worked on contains these changes.
Since they're completely off-topic to QUIC I don't think they should be part of a PR that adds support for QUIC.
But since I was also not going to throw away these changes, I extracted them here.
=> Some petty changes head of QUIC

CHANGELOG.md, Cargo.toml, core/CHANGELOG.md, misc/core-derive/CHANGELOG.md, misc/core-derive/Cargo.toml, misc/multistream-select/CHANGELOG.md, muxers/mplex/CHANGELOG.md, muxers/yamux/CHANGELOG.md, protocols/deflate/CHANGELOG.md, protocols/floodsub/CHANGELOG.md, protocols/gossipsub/CHANGELOG.md, protocols/identify/CHANGELOG.md, protocols/kad/CHANGELOG.md, protocols/mdns/CHANGELOG.md, protocols/noise/CHANGELOG.md, protocols/ping/CHANGELOG.md, protocols/plaintext/CHANGELOG.md, protocols/request-response/CHANGELOG.md, protocols/secio/CHANGELOG.md, swarm/CHANGELOG.md, transports/dns/CHANGELOG.md, transports/tcp/CHANGELOG.md, transports/uds/CHANGELOG.md, transports/wasm-ext/CHANGELOG.md, transports/websocket/CHANGELOG.md
Prepare release of `libp2p-v0.31` and all unreleased sub-crates.
=> Prepare release of `libp2p-v0.31` and all unreleased sub-crates.

core/src/connection/pool.rs, core/src/network/peer.rs, misc/multiaddr/src/from_url.rs
This PR just addresses some trivial clippy warnings that otherwise unnecessarily bloat PR diffs a bit.
=> Address some minor clippy warnings.

README.md
We've been on mainnet for a few weeks now, so seems reasonable to add here now
=> Add Forest to users list

CHANGELOG.md, Cargo.toml, protocols/mdns/CHANGELOG.md, protocols/mdns/Cargo.toml, transports/tcp/CHANGELOG.md, transports/tcp/Cargo.toml
Ensure to include https://github.com/ipfs-rust/if-watch/pull/6 to prevent issues like https://github.com/paritytech/substrate/issues/7794#issuecomment-778855202.
=> *: Require at least if-watch v0.1.8

protocols/request-response/src/handler/protocol.rs
Continuation of https://github.com/libp2p/rust-libp2p/pull/1987#discussion_r586205722.
An inbound upgrade should not be polled after the corresponding handler
has been dropped. Enforce this assumption by panicing in such case.
I am fine with this suggestion being rejected.
//CC @thomaseizinger @romanb
=> protocols/req-resp: Panic in inbound upgrade when handler dropped

README.md
Add notable users:
- ipfs-embed. Rust IPFS implementation with a focus on being embeddable into rust applications
- actyx, platform for writing manufacturing applications, based on rust-libp2p
@mxinden as discussed yesterday
=> Add notable users:

protocols/identify/src/identify.rs, protocols/kad/src/record/store/memory.rs
I can split them into two or three different PR's if you like, but because of the size of the changes, I didn't think it was worth it.
=> Derive debug

protocols/relay/src/behaviour.rs
=> Derive debug for RelayConfig.

protocols/gossipsub/src/behaviour.rs, protocols/gossipsub/src/behaviour/tests.rs, protocols/gossipsub/src/peer_score.rs
This just contains a few lint fixes and some spelling mistakes which leak via logs. 
I was doing this updates locally, but figured should push upstream.
=> [Gossipsub] Minor lint and spelling fixes

protocols/gossipsub/CHANGELOG.md, protocols/gossipsub/src/behaviour.rs, protocols/gossipsub/src/subscription_filter.rs
=> Silence gossipsub.
